### ISSUE TITLE
Mathlib `ton/crypto/smartcont/mathlib.fc` crashes

### ISSUE THREAD

**Issue by 0kenx** [ton-blockchain/ton#1019]
Mathlib `ton/crypto/smartcont/mathlib.fc` crashes when trying to use `fixed248_log2`.

## What behavior did you expect?
Should compile.

## What was the actual behavior?
```
Fift decompiler crashed
Error: Unknown opcode: b1111011
```

Compiled using Tact v1.3.1's default FunC compiler.

**Comment by anton-trunov** [comment]
This has been fixed in ton-opcode: https://github.com/tact-lang/ton-opcode/pull/16. This issue can be closed now
