### ISSUE TITLE
Customize log level/log output into runvm

### ISSUE THREAD

**Issue by JIoJIaJIu** [ton-blockchain/ton#103]
## Subject
I would like to hide `runvm*` output but keep other logs from fif file.

## Case
I have a integration test fif file that first invokes my smartcontract code (twice) with external message (`recv_external`) and then invokes again (twice) with `method_id` call. I would like to compare output datas from the last 2 calls and debug c4 changes between first 2 calls (`recv_external`). But cause my smartcontract code is growing and has multiple calls my stdout is full by `execute ...` TVM lines, that makes debugging is painful

## Proposal
I would like to customize `runvm*` calls with configuration where I can [point log_stream settings](https://github.com/ton-blockchain/ton/blob/29deff15c3cfbdfdb73cae37cde0831e9f079e01/crypto/fift/words.cpp#L2150) based on the stack values , also it would be great just to support passing `skip_logs` flags for hiding `execute ...` lines 

```
-1 code c4 Maybe(params) runvm

params:$_
  skip_log: (Either BoolTrue BoolFalse)
```

**Comment by JIoJIaJIu** [comment]
As a workaround there is possible to use `constant` for storing needful variables and output them at the end of the input, for avoiding dig into whole logs

**Comment by bny6613** [comment]
I faced the same thing when debbuged scripts. Since vm output is written to stderr, you can simply redirect it to /dev/null. `fift -s test.fif 2>null`.

**Comment by JIoJIaJIu** [comment]
Awesome, thank you @bny6613, haven't noticed that it's error stream
Hence it  completely solves my issue stylishly, but maybe the feature can be needed to filter logs per runvm invocation, so I left it unclosed on ton decision
