### ISSUE TITLE
[Question] How to estimate fees programmatically before sending message

### ISSUE THREAD

**Issue by APshenkin** [ton-blockchain/ton#104]
Hi!

Is there a way to estimate fees programmatically before sending message?

Use case for this:
I have N grams on wallet and I want to send all grams to other account. Currently it's not possible because now when we form a message we indicate only the amount for transfer.

**Comment by ton-blockchain** [comment]
Hi. It is planned to support this for simple cases in tonlib.
In general case, it is impossible because you have to actually run the transactions to know the fee and you don't know the state of a smart contract in advance.

**Comment by APshenkin** [comment]
@ton-blockchain 
Thank you for information.

Yes, we don't know the state of a smart contract, but we have it in our nodes :)

I can compare this with methods in ethereum. They have `eth_call` and `eth_estimateGas` for cases like this. This methods run your message on current state, but don't add them in blockchain.

So using this methods you can estimate fees required for message before sending.

It would be fantastic if TON will also have methods like this :)

**Comment by ton-blockchain** [comment]
That is exactly what is planned.
Also, it is not always possible to ensure that your message will be executed in the same way on the blockchain.
For example, the smart contract may use c7 register with now, rand_seed and other data which are hard to predict. Even the data of the smart contract itself could be already different if some other message was processed first.
