### ISSUE TITLE
Error after full node installation

### ISSUE THREAD

**Issue by 0x090909** [ton-blockchain/ton#1055]
<img width="992" alt="Screenshot 2024-07-12 at 18 42 25" src="https://github.com/user-attachments/assets/20f36a28-3b0d-46cb-afa6-b4bf0449e683">

Installed with: 

`sudo bash install.sh  -d -m full`

**Comment by yungwine** [comment]
Hi! Please, reinstall the MyTonCtrl using the following guide: https://docs.ton.org/participate/run-nodes/full-node#install-the-mytonctrl
