### ISSUE TITLE
No primops for working with substrings

### ISSUE THREAD

**Issue by kirelagin** [ton-blockchain/ton#107]
The “List of Fift stack value types” section of the documentation states that `String` is a UTF-8 string, however, apparently, there are no primops for working with UTF-8 string, so it is impossible to implement functions like “take the first `n` characters of a string” or “check that the string starts with the given prefix”. Implementing the entire UTF-8 logic in Fift doesn’t appear to be practical.

There is an undocumented `$|` word, but, unfortunately, the implementation works with raw bytes rather than UTF-8 characters:

```
"подуй" 5 $| .s
"по�" "�уй"
 ok
```

Do you think you will be able to fix this or would you be open to someone contributing UTF-8 primops?

**Comment by ton-blockchain** [comment]
We have added words `$Len` and `$Split` into commit b978e27b2f2ca6e4403843b9d6bf3f407bf63499, in case somebody needs them.
