### ISSUE TITLE
How much TON will cost to deploy a smart contract on ton?

### ISSUE THREAD

**Issue by abn2357** [ton-blockchain/ton#1089]

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)
Regards.

**Comment by EmelyanenkoK** [comment]
Check docs.ton.org
