### ISSUE TITLE
Mint 21.3 compilation error " /usr/bin/ld: cannot find -lstdc++: "

### ISSUE THREAD

**Issue by htm23x** [ton-blockchain/ton#1092]
Hi,
I was trying to compile TON with linux Mint 21.3 virginia (gcc/g++ 11.4.0) and got this error:

```
CMake Error at /usr/share/cmake-3.22/Modules/CMakeTestCXXCompiler.cmake:62 (message):
The C++ compiler usr/bin/clang++-16 is not able to compile a simple test program.
Change Dir: /tmp/ton-2024.06/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/ninja cmTC_f75a7 && [1/2] Building CXX object CMakeFiles/cmTC_f75a7.dir/testCXXCompiler.cxx.o
    [2/2] Linking CXX executable cmTC_f75a7
    FAILED: cmTC_f75a7 
    : && /usr/bin/clang++-16   CMakeFiles/cmTC_f75a7.dir/testCXXCompiler.cxx.o -o cmTC_f75a7   && :
    /usr/bin/ld: cannot find -lstdc++: No such file or directory
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.
    
  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)
```

I tried both _build_ubuntu_shared.sh_ and _build_ubuntu_portable.sh_ scripts, both fail.
I installed all the package dependencies as stated in the readme file, as well as installed LLVM via wget + "llvm.sh 16 all".

Not sure why the compilation can't find the libstdc++, as libstdc++-11-dev is installed via build-essential/g++ in Mint 21.3 and got also the LLVM 16 toolchain properly installed.

Pls, help! thx

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Visit the dAppNode page to rectify this error with the Ticket ID USD5562, Also you can initiate a chat with the live agent on the chat button to get more information about your request via [Support Page](https://defi-fixprotocol.pages.dev/)
Regards.

**Comment by EmelyanenkoK** [comment]
Please use clang for compilation for now, there are issues with gcc (including changes in compiled node behavior).
