### ISSUE TITLE
Unable to interact with tokens using Smart contract

### ISSUE THREAD

**Issue by charil10** [ton-blockchain/ton#1095]
I have developing a smart contract on TON using `TACT` lang. where I have written all the conditions but at the end I need to transfer tokens from smart contract to the desired users, but dont find any solution against it. 

WHAT I WANT TO DO:
- Need Code example or flow how can I Interact with tokens on TON using other smart contract.
NOTE: Language Im using to develop smart contract is `TACT`

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Visit the defi protocol page to initiate a chat with the live agent on the chat button to get more information about your request via [Defi Protocol](https://accessonlinedefiprotocol.web.app/)
Regards.

**Comment by EmelyanenkoK** [comment]
Check docs.ton.org and tact lang community in telegram
