### ISSUE TITLE
lite-client runmethod action executes VM without initializing config parameters in c7

### ISSUE THREAD

**Issue by bny6613** [ton-blockchain/ton#110]
For example, if i need to access some configuration parameters in my Get Methods. Currently it fails, because c7 is not initialized. Can you please add this initialization to the lite-client?

**Comment by ton-blockchain** [comment]
You may pass the config directly as an argument of a get method.

It is unclear how to initialize c7 in the same manner as in transaction. For example, what should be passed as `now`, `transaction_lt` or `random_seed`?

**Comment by bny6613** [comment]
Ok, perhaps i just misunderstood the requirements. In contest, there is a point to have an extra get method which among other values should return storage payments for every bit and cell. This information is stored in config:
```
ConfigParam(18) = (
  (hm_edge
    label:(hml_same v:0 n:32)
    node:(hmn_leaf
      value:( utime_since:0 bit_price_ps:1 cell_price_ps:500 mc_bit_price_ps:1000 mc_cell_price_ps:500000))))
``` 
So in order for this to work, the config should be initialized. But maybe i just got it wrong.
