### ISSUE TITLE
Can't receive state for wallet that was created using fift files from tonlib

### ISSUE THREAD

**Issue by APshenkin** [ton-blockchain/ton#111]
Here is an example of created wallet
0f-tGs1HBweSDCLnvVSih4J9zf5knXEdxLYkveHwizYkkDBf
kf-tGs1HBweSDCLnvVSih4J9zf5knXEdxLYkveHwizYkkG2a

when trying to get wallet state for it tonlib returns
```
{
    "@type": "error",
    "code": 400,
    "message": "ACCOUNT_TYPE_UNEXPECTED: not a Wallet"
}
```

Wallet was created using `new-wallet.fif` file

**Comment by APshenkin** [comment]
Also what is the difference between `testWallet.getAccountState` and `wallet.getAccountState` ?

**Comment by APshenkin** [comment]
If use `new-wallet-v2.fif` then it returns state.

Does this mean, that `new-wallet.fif` is no longer supported and it's recomended to create wallets from `new-wallet-v2.fif`

In this case, how will the wallet code be updated in the future? If it will change often and tonlib will support only latest version it will be hard to maintain it in services

**Comment by APshenkin** [comment]
And as I understand difference between `new-wallet-v2.fif` and `new-wallet.fif` is that in `new-wallet-v2.fif` there is expiration time for generated send messages, correct?

**Comment by ton-blockchain** [comment]
Both accounts should be supported.
The first one is `testWallet` and the second is `wallet`.

To get an account state it is better to use `generic.getAccountState`. Otherwise, the type of requested account should match the actual type of account.

**Comment by APshenkin** [comment]
Thanks for response!
