### ISSUE TITLE
cc0eb453cb3bf69f92693160103d33112856c056

### ISSUE THREAD

**Issue by mostafafeizi1352** [ton-blockchain/ton#1112]
https://github.com/ton-blockchain/ton/blob/cc0eb453cb3bf69f92693160103d33112856c056/crypto/block/block.tlb#L155-L157

**Comment by knox0506** [comment]
> https://github.com/ton-blockchain/ton/blob/cc0eb453cb3bf69f92693160103d33112856c056/crypto/block/block.tlb#L155-L157

ty
