### ISSUE TITLE
error: ‘td::Ed25519’ has not been declared

### ISSUE THREAD

**Issue by zababurinsv** [ton-blockchain/ton#112]
Hi 
I compile the client as written in readme.
Everything is fine on the first computer.
An error occurred on the second computer.

Why does this error appear?

/home/sergey/lite-client/crypto/vm/tonops.cpp: In function ‘int vm::exec_ed25519_check_signature(vm::VmState*, bool)’:
/home/sergey/lite-client/crypto/vm/tonops.cpp:269:7: error: ‘td::Ed25519’ has not been declared
   td::Ed25519::PublicKey pub_key{td::SecureString(td::Slice{key, 32})};
       ^~~~~~~
/home/sergey/lite-client/crypto/vm/tonops.cpp:270:14: error: ‘pub_key’ was not declared in this scope
   auto res = pub_key.verify_signature(td::Slice{data, data_len}, td::Slice{signature, 64});
              ^~~~~~~
crypto/CMakeFiles/ton_crypto.dir/build.make:426: recipe for target 'crypto/CMakeFiles/ton_crypto.dir/vm/tonops.cpp.o' failed
make[3]: *** [crypto/CMakeFiles/ton_crypto.dir/vm/tonops.cpp.o] Error 1
CMakeFiles/Makefile2:1656: recipe for target 'crypto/CMakeFiles/ton_crypto.dir/all' failed
make[2]: *** [crypto/CMakeFiles/ton_crypto.dir/all] Error 2
CMakeFiles/Makefile2:167: recipe for target 'CMakeFiles/test-cells.dir/rule' failed
make[1]: *** [CMakeFiles/test-cells.dir/rule] Error 2
Makefile:188: recipe for target 'test-cells' failed
make: *** [test-cells] Error 2

Regards
Sergey

**Comment by zababurinsv** [comment]
It is installed
openssl version
OpenSSL 1.1.1a  20 Nov 2018

**Comment by ton-blockchain** [comment]
And does zlib (zlib1g-dev) is installed?

**Comment by zababurinsv** [comment]
Yes... and env(....)
Maybe I did something wrong ...
I at wasm want to write for ton. This could be a problem. 
I'll check it tomorrow.
