### ISSUE TITLE
Cell (Builder) size limits

### ISSUE THREAD

**Issue by Tynik** [ton-blockchain/ton#113]
Hello, could you help me please?
How can I send more than 3 public keys in StateInit message if currently there is a limit for a message < 256 or max 4 refs.? How can I split the big init message and receive chunks in *.fc?

**Comment by Tynik** [comment]
I tried to do it with refs, but after I have known that there is a limit for refs in cell.
```
<b b{0011} s, number_signs 2 * 2 + roll ref, { 2 roll ref, } number_signs times swap dict, b>
```

**Comment by bny6613** [comment]
You can to put them all into dict (hashmap) first and then store it inside message body.

**Comment by Tynik** [comment]
> You can to put them all into dict (hashmap) first and then store it inside message body.

thank you!

**Comment by Tynik** [comment]
@bny6613 
could you help me please again( I can't find a good example to add a public key to dict. I tried a lot of solutions but it does not work(

I think that I need to create the Slice (in this context it's <b b> empty and I think it will be work as the simple solution and 1 as a key in the dict - I think), but I get the next error:
[ 1][t 0][1570643617.519623995][words.cpp:2856] multi-sign-wallet.fif:29: add_public_key: not a cell slice
How it can be done?
```
{ @' public_keys 256 idict!+ not abort"cannot add a new public key"
  =: public_keys
} : add_public_key

<b b> 1 add_public_key
```

**Comment by bny6613** [comment]
You almost right, just need to convert it to slice (`<s`) before adding to dict, since it accept Slice as a value. Here is an example:
```
newkeypair <b swap B, b> <s 1 add_public_key 
```

**Comment by Tynik** [comment]
Thank you very much! It works! Awesome!
@bny6613
