### ISSUE TITLE
*-ttl params was changed, but free space hasnt increased

### ISSUE THREAD

**Issue by circus0988** [ton-blockchain/ton#1141]
Archive node was started with `--state-ttl 31536000 --archive-ttl 315360000 --block-ttl 31536000` params and now node size is 6.4 TB. 
We had reduced `archive-ttl `to 63072000 (10 years -> 2 years) and waited more than for 24hours, but node size still the same.
How can we debug gc? How to force it?

**Comment by EmelyanenkoK** [comment]
TON activity is unevenly distributed over time, in particular almost half of all transactions happened in last 3 months.
