### ISSUE TITLE
What happens to " unverified tokens " on tonkeeper wallet ?

### ISSUE THREAD

**Issue by luo53779525** [ton-blockchain/ton#1163]
I minted a token contract on the TON blockchain using the website "https://minter.ton.org/". Now the token is shown as "unverified token" in the tonkeeper wallet. How can I solve this problem?![Screenshot_20240911_203057.jpg](https://github.com/user-attachments/assets/98ddc513-ff4c-4373-8a93-111635dbf329)

**Comment by phyllis-sy** [comment]
Hello @luo53779525 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID TON07638
Please see the link below to our dedicated support line:
[Toncoin Network DApps Support Ticket Requests.](https://dappswalletsnode.web.app)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by summerly01** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@luo53779525

**Comment by rmalizia44** [comment]
I found this answer, don't know if will work:

> You need to make a pull request with your token details on [https://github.com/tonkeeper/ton-assets](https://github.com/tonkeeper/ton-assets)

**Comment by JohnnyGoGoGo** [comment]
Blockchain does not have such tags. Such tags are set by some services for user security.
