### ISSUE TITLE
How can I subscribe to all network events?

### ISSUE THREAD

**Issue by akme** [ton-blockchain/ton#117]
Is there any way of getting all the events of the node? Some kind of watcher for the blockchain so we can react to the event?

**Comment by akme** [comment]
Maybe there is some kind of callbacks I can configure? 
What is the purpose of callbacks in tonlib, can I use them for this?

**Comment by ton-blockchain** [comment]
What kind of events do you have in mind? Something like watching all the updates of a specific account?

Currently, the LiteServer protocol is completely stateless and does not keep any data after a query is completed. So you'll have to poll the server, say, once in three seconds to check whether there is a new masterchain block, and if there is, which is the state of the account in question with respect to the new masterchain block,

**Comment by akme** [comment]
We need to watch more than 1000 wallets for incoming transactions, watch each wallet separately doesn't look rational, so we just want to get all events and check if it's applicable for us.

**Comment by briancrypto** [comment]
Ya, it would be nice to be able to observe event for specific account(s).
Currently  getTransactionHistory return all txs based on the hash/lt which could be hundreds or thousands.

**Comment by EmelyanenkoK** [comment]
You can find example implementation of such service [here](https://github.com/toncenter/tonweb/blob/wallet_sources/src/test-block-subscribe.js)
