### ISSUE TITLE
I cannot create Ton project using"npm create ton@latest" 

### ISSUE THREAD

**Issue by lucaslee129** [ton-blockchain/ton#1179]
Hi, Team. How are you?
I am here to get help from you. While creating the ton project using "npm create ton@latest" command.
I am using Windows10 and node version 20.
I think I used the possible ways including reinstall, changing the node version, etc.
I will attach the screenshot here. Please help me. Thanks.
![photo_2024-09-16_21-07-40](https://github.com/user-attachments/assets/bca12a03-032a-4122-b0b3-a57293dfe555)

**Comment by bladimirviverosgutierre0211** [comment]
Hola espero solucionar ese problema

**Comment by Reedme-21** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@lucaslee129

**Comment by lucaslee129** [comment]
The problem was fixed after one day automatically. But I am not sure what the reason is still.

Thanks for your kind support, @everyone.
