### ISSUE TITLE
Can't recover stakes and bonuses

### ISSUE THREAD

**Issue by ashkov** [ton-blockchain/ton#118]
Today can't recover stakes and bonuses to the validator wallet.
`runmethod -1:C7EAFBC106A7AA4BA3D16007C6AC64CAAC1078B4A43577339E246F466405E896 compute_returned_stake`
 gives result,
The seqno is increasing on each query. But I can't see any withdraw of gramms.
Yesterday it worked.

Difference with the early attempts is that I tried to make two consequential participations in elections. 
But In 'compute_returned_stake' I saw only one stake for a long time. And I can't withdraw even one. Now, there is a sum for both stakes, but I can't still withdraw them. I looked through the transactions and saw that I paid small fees for each request for withdraw. But still can't achieve anything.

**Comment by ashkov** [comment]
Stakes recovered after 3 days. Now new stakes hung again.

I think it is a bug.

Can we recover stakes more often?

**Comment by EmelyanenkoK** [comment]
Not relevant anymore: in current network (in contrast to testnet1) elector contract works as expected.
