### ISSUE TITLE
> feel free to do a PR about it

### ISSUE THREAD

**Issue by Marazali75** [ton-blockchain/ton#1188]
> feel free to do a PR about it

_Originally posted by @Marazali75 in https://github.com/gdamdam/awesome-decentralized-web/issues/67#issuecomment-2364130361_

**Comment by Rezacb0413** [comment]
> > feel free to do a PR about it
> 
> 
> 
> _Originally posted by @Marazali75 in https://github.com/gdamdam/awesome-decentralized-web/issues/67#issuecomment-2364130361_
