### ISSUE TITLE
<!-- Describe the issue -->

### ISSUE THREAD

**Issue by mhmdmir76** [ton-blockchain/ton#1190]
Hey
I Depo some Toncoin to Cwallet but forgot to fill the Memo
Im from iran and cant KYC
What should i do?

**Comment by Reedme-21** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@mhmdmir76

**Comment by JohnnyGoGoGo** [comment]
Not a suitable place. Please contact technical support of the service you are using.
