### ISSUE TITLE
7.80

### ISSUE THREAD

**Issue by Manoj70184** [ton-blockchain/ton#1195]

**Comment by Manoj70184** [comment]
7.8 ton sent to in your ton wallet in a mistake please give me my ton in my wallet my address UQBYBklNFSBcmBz8DiwV5KY9aX3DnxmOBHb0EClFkpJZBx_2 
![Screenshot_2024-09-22-08-02-11-245_com ton_keeper](https://github.com/user-attachments/assets/399f819a-05ee-480f-839b-36eacf19bc9b)

**Comment by nodesupport1** [comment]
@Manoj70184 You may need to contact the support team of the platform where the mistake occurred to request a refund or assistance with the transfer. They should be able to help you resolve the issue with the mistaken transfer. I'll have to refer you to the official support live chat with the ticket ID TON07638
Please see the link below to our dedicated support line:
[Ton Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by Reedme-21** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@Manoj70184

**Comment by JohnnyGoGoGo** [comment]
Not a suitable place. Please contact technical support of the service you are using.
