### ISSUE TITLE
Tokens not verified

### ISSUE THREAD

**Issue by Rzroheet** [ton-blockchain/ton#1199]
< give me my tons ? -->

**Comment by Reedme-21** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@Rzroheet

**Comment by Rahmad297** [comment]
Apes aja nih

**Comment by Rahmad297** [comment]
Sulit dah
