### ISSUE TITLE
Built target rocksdb *** [all] Error 2

### ISSUE THREAD

**Issue by roma4u** [ton-blockchain/ton#12]
I get an error while building the application:
`[ 57%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/utilities/transactions/optimistic_transaction.cc.o
[ 57%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/utilities/transactions/pessimistic_transaction.cc.o
[ 57%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/utilities/transactions/pessimistic_transaction_db.cc.o
[ 57%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/utilities/transactions/snapshot_checker.cc.o
[ 57%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/utilities/transactions/transaction_base.cc.o
[ 57%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/utilities/transactions/transaction_db_mutex_impl.cc.o
[ 57%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/utilities/transactions/transaction_lock_mgr.cc.o
[ 57%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/utilities/transactions/transaction_util.cc.o
[ 57%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/utilities/transactions/write_prepared_txn.cc.o
[ 57%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/utilities/transactions/write_prepared_txn_db.cc.o
[ 57%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/utilities/transactions/write_unprepared_txn.cc.o
[ 59%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/utilities/transactions/write_unprepared_txn_db.cc.o
[ 59%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/utilities/ttl/db_ttl_impl.cc.o
[ 59%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/utilities/write_batch_with_index/write_batch_with_index.cc.o
[ 59%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/utilities/write_batch_with_index/write_batch_with_index_internal.cc.o
[ 59%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/port/port_posix.cc.o
[ 59%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/env/env_posix.cc.o
[ 59%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/env/io_posix.cc.o
[ 59%] Linking CXX static library librocksdb.a
[ 59%] Built target rocksdb
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
~/ton/ton-node
`

**Comment by roma4u** [comment]
`git submodule update`
resolved the issue

**Comment by Deniskore** [comment]
@roma4u Run CMake with option -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON and provide more information about your environment.

**Comment by roma4u** [comment]
```
apt install build-essential cmake gperf libssl-dev libmicrohttpd-dev libreadline-dev
git clone https://github.com/ton-blockchain/ton.git
cd ton
git submodule update --init --recursive
mkdir build && cd build
cmake ..
make -j4
```
resolved the issue
