### ISSUE TITLE
[BUG] Couldn't create wallet with workchainId greater 127

### ISSUE THREAD

**Issue by phil-dolgolev** [ton-blockchain/ton#120]
new-wallet-v2.fif correct handles only 1-byte workchainId. 
According documentation workchainId can be any 4-byte signed integer.

**Comment by ton-blockchain** [comment]
Yes, the sample wallets support only 8-bit workchain ids, but we don't think this is a bug. More than 127 workchains with the same set of rules as the basechain are not expected to be required the next several years, so there is not so much sense to make the sample scripts more complicated.
