### ISSUE TITLE
SECURITY.md

### ISSUE THREAD

**Issue by Alijocker369** [ton-blockchain/ton#1200]
SECURITY.md

_Originally posted by @Alijocker369 in https://github.com/ton-blockchain/wallet-contract/pull/84#pullrequestreview-2319952507_

**Comment by Reedme-21** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@Alijocker369
