### ISSUE TITLE
Wrong transfer 

### ISSUE THREAD

**Issue by Avdhooll** [ton-blockchain/ton#1201]

**Comment by Reedme-21** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@Avdhooll

**Comment by JohnnyGoGoGo** [comment]
Not a suitable place. Please contact technical support of the service you are using.

**Comment by mohamadrezaasadi308** [comment]
> جای مناسبی نیست لطفاً با پشتیبانی فنی سرویسی که استفاده می کنید تماس بگیرید.

باشه
