### ISSUE TITLE
Почему перевод не поступают?

### ISSUE THREAD

**Issue by ALGA91** [ton-blockchain/ton#1203]
Прощу вернуть тон переводил на COINEX. Прошло 24 часа все таки не поступил прощу вернуть  UQBexFIQHUYBvSfMtQx6py1Nn3FsD7SZVXrwyqgmtIp0fBcC
![Screenshot_20240923-193041](https://github.com/user-attachments/assets/f02cfcd1-2963-460e-9ada-6fb131a564ae)

**Comment by Reedme-21** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@ALGA91

**Comment by Dru1DD** [comment]
> Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request. Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/) @ALGA91

Scam

**Comment by Dru1DD** [comment]
## **You sent TON to CoinEx but did not include a memo/comment**

**_A memo (or comment)_** is a special text field that is sometimes required when sending cryptocurrency to an exchange. It is used to link the transaction to your account. If no memo is provided, the exchange won’t be able to automatically credit the funds to your account.

**_What went wrong:_**

You sent funds to CoinEx, but you did not include a memo/comment in the transaction. As a result, CoinEx was unable to identify your transaction and credit the funds to your account.

Here is the address where your funds were sent: UQADtLHVdN-K9PdPJMWQ1whbk8A2MbtqIbVOBzCy6agP9GfR
<img width="400" alt="image" src="https://github.com/user-attachments/assets/531f0521-a139-4930-9938-8ae20c39b71f">


## **_What you can do:_**

Unfortunately, blockchain transactions are irreversible, and there is no way to cancel or get your funds back automatically. However, you can try to recover them by following these steps:

1. Contact CoinEx support.
2. Provide them with proof of the transaction, such as a screenshot from TonViewer or other transaction details (address, amount, time).
4.Explain that you forgot to include the memo when sending the funds.

The support team should be able to manually process the transaction and credit the funds to your account.
