### ISSUE TITLE
Unverified token faild tonkeeper

### ISSUE THREAD

**Issue by Ahadkira** [ton-blockchain/ton#1205]

**Comment by diadka** [comment]
same with Hamster 
![hamster1](https://github.com/user-attachments/assets/40a4dd30-0649-485d-81af-c012ae0a6eb1)

**Comment by diadka** [comment]
![изображение](https://github.com/user-attachments/assets/414a4ac6-a883-4229-8704-91c97dc04590)

**Comment by JohnnyGoGoGo** [comment]
Not a suitable place. Please contact technical support of the service you are using.
