### ISSUE TITLE
I mistakenly sent 18.876331 USDT.

### ISSUE THREAD

**Issue by Sokharak** [ton-blockchain/ton#1219]
I mistakenly send 18.876331 USDT to the wrong owner since 09/26/2024, 19:21:38. Can you please refund my cash back ? Thanks you.

![IMG_6542](https://github.com/user-attachments/assets/b57ebdb6-d32a-4102-86d0-3891d67f06db)
![IMG_6541](https://github.com/user-attachments/assets/4babe86b-1b1a-4913-8531-430d00107c2c)
![IMG_6539](https://github.com/user-attachments/assets/7a909adc-cc3b-404b-a61a-a20987455545)

**Comment by case-hub** [comment]
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. 
Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@Sokharak 
Support.
  {c}2024

**Comment by Rezacb0413** [comment]
>  I mistakenly send 18.876331 USDT to the wrong owner since 09/26/2024, 19:21:38. Can you please refund my cash back ? Thanks you.
> 
> 
> 
> 
> 
> 
> 
> ![IMG_6542](https://github.com/user-attachments/assets/b57ebdb6-d32a-4102-86d0-3891d67f06db)
> ![IMG_6541](https://github.com/user-attachments/assets/4babe86b-1b1a-4913-8531-430d00107c2c)
> ![IMG_6539](https://github.com/user-attachments/assets/7a909adc-cc3b-404b-a61a-a20987455545)
> 
> 
> 
> 
> 
>

**Comment by JohnnyGoGoGo** [comment]
Not a suitable place. Please contact technical support of the service you are using.

**Comment by Sokharak** [comment]
Scam
