### ISSUE TITLE
By mistake 😕 😪 iam send my coin other address usdt  and to coin.so please re deposite my usdt on my network..

### ISSUE THREAD

**Issue by Matininamdar30** [ton-blockchain/ton#1220]

**Comment by Msn7177** [comment]
Me too😟

**Comment by case-hub** [comment]
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@Matininamdar30 
Support.
  {c}2024
