### ISSUE TITLE
finds are stuck from congestion?

### ISSUE THREAD

**Issue by gavint75** [ton-blockchain/ton#1222]
funds stuck
 to be sent

unknown
![Screenshot_20240929-061515](https://github.com/user-attachments/assets/16d9a28f-d733-4dc3-8afb-d925b0592636)

0:1d8919ca152e4562afbc30d73253ade20283f0b92fddf1cec70442154ae95a01

**Comment by case-hub** [comment]
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@gavint75 
Support.
  {c}2024

**Comment by gavint75** [comment]
funds have now cleared
