### ISSUE TITLE
No memo and wrong transfer 

### ISSUE THREAD

**Issue by Benauorin** [ton-blockchain/ton#1223]
<!-- Describe the issues 
I didn't not add the memo and I think I mistakenly transfer  USDT(ton) to another address,this is my wallet address UQClutBgGsTzoZEMevTAays2GYCkQeMhpI1l_PfLizTuNQ9N and this is the ADDRESS I THE transfer the USDT TO  UQDD8dqOzaj4zUK6ziJOo_G2lx6qf1TEktTRkFJ7T1c_fKneI

**Comment by Shayan12699** [comment]
Alhundullah
