### ISSUE TITLE
_VS_VERSION calculation error

### ISSUE THREAD

**Issue by kongye-su** [ton-blockchain/ton#1246]
https://github.com/ton-blockchain/ton/blob/921aa29eb54db42de21e0f89610c347670988ed1/CMake/FindSodium.cmake#L130-L135

When the MSVC_VERSION is larger than 1939, the _VS_VERSION  should be 143 instead of 144 or more.

The latest VS,  Visual Studio 2022 version 17.10.1, its _MSC_VER is 1940.

There is no v144 build tool in VS Installer.

**Comment by IDXNTCXNAJM** [comment]
Mit license
