### ISSUE TITLE
Func nil exposes into PUSHNULL

### ISSUE THREAD

**Issue by JIoJIaJIu** [ton-blockchain/ton#125]
## Overview
FunC **nil** word exposed as **PUSHNULL** Asm instruction, but I expect to have **NIL**

## Case
There is **nil** (that describes empty tuple) and **null** into TVM, when I init tuple as
```
var t = nil;
```
I expect to get `()`, rather then `null`. It doesn't allow me to get size of nil tuple that described as empty one with length 0. Also nil word in `FunC` contradicts with the NIL/nil words into Fift
It would be great to have separated [null](https://github.com/ton-blockchain/ton/blob/38c3e39066a9c3b8a62b2f4cad54df4dc6307360/crypto/func/builtins.cpp#L912) and nil in FunC
 
## Example
FunC 
```
(int) size(tuple) asm "TLEN";

() main() {
}

(int) get_tuple_size() method_id {
  var t = nil;
  return t.size();
}
```
Fift
```
"Asm.fif" include
// automatically generated from `dns/tuple.func`
95857
PROGRAM{
  DECLPROC main
  95857 DECLMETHOD get_tuple_size
  main PROC:<{
  }>
  get_tuple_size PROC:<{
    PUSHNULL
    TLEN
  }>
}END>c

<s runvmcode
```
```
execute SETCP 0
execute DICTPUSHCONST 19 (xC_,1)
execute DICTIGETJMP
execute PUSHNULL
execute TLEN
handling exception code 7: not a tuple of valid size
default exception handler, terminating vm with exit code 7
[ 3][t 0][1570790811.721310616][continuation.cpp:783]   steps: 6 gas: used=380, max=9223372036854775807, limit=9223372036854775807, credit=0
```

**Comment by ton-blockchain** [comment]
The idea was that `nil` represents the null constant as a value of type `Tuple?` (i.e., `Tuple or Null`), so that it can be used to construct lists (which currently also have type `Tuple?` in the simplified funC type system):

```
var l = nil;
int i = 0;
do {
 l = cons(i += 1, l);
} until (i >= 10);
return l;
```

If you really need an empty Tuple, you can define a new asm function in your code:

tuple Nil() asm "NIL";

**Comment by JIoJIaJIu** [comment]
Doesn't it look ambigiuos?

About constructing list cause you mentioned it, another issue, that I've faced, in all existed smartcontracts there is `cons` section that constructs the list. but in fact it's alias of `pair`
```
var l = nil;
int i = 0;
do {
 l = cons(i += 1, l);
} until (i >= 10);
return l;
```
produces the structure as 
```
[ 10 [ 9 [ 8 [ 7 [ 6 [ 5 [ 4 [ 3 [ 2 [ 1 (null) ] ] ] ] ] ] ] ] ] ]
```
so it concates 2 lists in one without folding, so I am using `TPUSH` for that purpose
