### ISSUE TITLE
I lost my funds, amount 6ton  when paste an address it changed  I need refund please 

### ISSUE THREAD

**Issue by Shekzy** [ton-blockchain/ton#1275]

**Comment by Shekzy** [comment]
Please I need refund I lost my funds 6ton this is my wallet address UQAk5i_aSmMP1IcVYfdYi1eTuPvWaXgOYqa5V7ejNW0mB7I9
![Screenshot_20241015-064500](https://github.com/user-attachments/assets/a92f7fa7-2f47-4aaa-ad82-48aa0da611a3)

**Comment by Shekzy** [comment]
If possible please refund 🙏🥹

**Comment by Shekzy** [comment]
UQDD8dqOzaj4zUK6ziJOo_G2lx6qf1TEktTRkFJ7T1c_fKne
Sent to this wrong wallet address

**Comment by Julietnacy** [comment]
@Shekzy has your issues been solved?
