### ISSUE TITLE
Single Nominator Pool can't do new stake

### ISSUE THREAD

**Issue by YuXiaoCoder** [ton-blockchain/ton#1281]
I ran a Validator node and also deposited enough money into the contract, but I still can't do the new stake operation, the operation exit code is 8195(0x2003)
![image](https://github.com/user-attachments/assets/e56481a4-0431-43a9-b99a-90f21e25debb)

I'm looking forward to getting into the election like the other Validator nodes!
https://tonscan.org/address/Ef_gtF7qLZvvz-sa2Qp8kzg3P6EM1HnG8chTwAWnALnAuDtt
![image](https://github.com/user-attachments/assets/6c13a595-792f-451b-ae0b-841e71b7875a)

This is my Single Nominator Pool contract, and I can't do a new stake.
https://tonscan.org/single-nominator/Ef_0E7UiFzMbO0xsyf3wRcfBwkFIoF-C_zQf3SPZnY3SZn8A
![image](https://github.com/user-attachments/assets/d668777d-9ea8-4dba-9e0f-4a457ba7ddd6)
![image](https://github.com/user-attachments/assets/d2cf716a-e5ff-40ac-9e09-19e5eeaa62a4)

Run a node normally and create a Single Nominator Pool via mytonctrl
![image](https://github.com/user-attachments/assets/650db5a6-319e-4624-bc39-5b0317274601)

Version: `v2024.09 self-compiled`

OS: `Ubuntu 22.04 Docker`
CPU: `Intel(R) Xeon(R) Platinum 8575C`
Ditsk: `ALiYun ESSD PL1`

**Comment by nkmax13** [comment]
Hello,
Got the same error, how did you solve this?
