### ISSUE TITLE
question on TX order

### ISSUE THREAD

**Issue by cmingxu** [ton-blockchain/ton#1287]
Hi, dear community

Suppose contract A and B both are sending TX to contract C, suppose internal messages  generated by A and B have same LT, same shard, same block, then which one would be handle first by C.

**Comment by EmelyanenkoK** [comment]
With lower hash. Check whitepapers.

**Comment by cmingxu** [comment]
> With lower hash. Check whitepapers.

Thank you for your kindly reply, can you further point out where the logic is locate in the source code, that would be very helpful for me.
