### ISSUE TITLE
DNS scm contest requirements clarification, dnsresolve signature

### ISSUE THREAD

**Issue by JIoJIaJIu** [ton-blockchain/ton#131]
In the `TON Contest` file there is requirements for supporting pointing multiple domains into `dnsresolve` method

> must implement get-method "dnsresolve" that accepts two arguments: a 8n-bit Slice containing an n-character string with the subdomain name, or with several subdomain names each followed by a zero byte;

but output signature is (int, cell) as
> The output consists of one Integer and one Cell or Null. If the subdomain is not found, the smart contract should return (0, null)

Did I get right that I can point multiple domains that can be resolved into different locations as
```
run_method scm_address 0 "core.telegram.org blog.yandex.ru blog.google.com"
```
and output should contain tuple for example (or maybe Hashmap?)
```
[(core.telegram.org_address, 16), (null, 0), (null, 0)] 
```

 Is it mismatch in requirements or my interpretation is wrong?

**Comment by ton-blockchain** [comment]
1) The domain components are written backwards when passed as an argument to `dnsresolve`. So "blog.google.com" is actually represented by a Slice containing string "com\0google\0blog\0".
2) If the subdomain "com\0" is present in the subdomain database, the result is the value stored for this subdomain (represented by a Cell) and the integer 4 (subdomain length).
On the other hand, if "com\0google\0" is present in the database, the result is the corresponding value for this subdomain (either the whole dictionary or one specific entry from this dictionary) and the integer 11 (subdomain length).

`dnsresolve` is not intended to be used to resolve multiple domains in one query.

**Comment by JIoJIaJIu** [comment]
Thank you for an answer, I understood requirements wrongly. Hence I'm closing the issue
