### ISSUE TITLE
![IMG_8517](https://github.com/user-attachments/assets/25ce0e57-14ab-4a6d-b261-6d53931e7aa5)

### ISSUE THREAD

**Issue by martyb1666** [ton-blockchain/ton#1313]
![IMG_8517](https://github.com/user-attachments/assets/25ce0e57-14ab-4a6d-b261-6d53931e7aa5)
![IMG_8515](https://github.com/user-attachments/assets/c7f6533a-f3c2-44f6-b774-eb692b34751b)

_Originally posted by @thsafe in https://github.com/ton-blockchain/TEPs/issues/119#issuecomment-2412537474_

**Comment by Ramees78600** [comment]
0:2c63cd7bcf92a303cb6b4020b2934d210caa216cf6ef9fb1decd963cbc57e5fb
