### ISSUE TITLE
I sent 69000 X token to wrong address

### ISSUE THREAD

**Issue by rakibhdjd** [ton-blockchain/ton#1317]
I sent 69000 X token to wrong address on 25 October, 2024. Write the bybit address and mistakenly write comment instead of memo id
He's the bybit received address:
UQDD8dqOzaj4zUK6ziJOo_G2lx6qf1TEktTRkFJ7T1c_fKne

Sending address:
UQAbiRMI0Z6yRnudoAFM686HVYXmntLvIwQm_cHBj6fmKVFF
I'm requesting for the refounding of token to the above address
Thanks.

**Comment by JohnnyGoGoGo** [comment]
Not a suitable place. Please contact technical support of the service you are using.
