### ISSUE TITLE
Unable to create Hashmap with variable length slice key

### ISSUE THREAD

**Issue by JIoJIaJIu** [ton-blockchain/ton#133]
## Overview
There is no possible to use slices as keys for Dict with length less then **n**

## Case
When I set value with `DICTSET` as example I **must** provide `BBITS` for slice as **n**, either the execution fails cause my slice is smaller. 
```
execute DICTGETOPTREF
handling exception code 9: not enough bits for a dictionary key
default exception handler, terminating vm with exit code 9
```

But then when I request DICTGET with bigger key - I get error 
```
handling exception code 9: error while parsing a dictionary node label
default exception handler, terminating vm with exit code 9
```
cause `HashmapLabel` is initialized with the first call

**Comment by ton-blockchain** [comment]
This seems to be the correct behavior, because all keys in an ordinary Dictionary with n-bit keys must be exactly n bits long.

Did you have a prefix dictionary in mind? Then you should use PFXDICTGET and PFXDICTSET instead.

**Comment by JIoJIaJIu** [comment]
> because all keys in an ordinary Dictionary with n-bit keys must be exactly n bits long

As an approach - maybe fill the slice with needful amount of zeros automatically, similar to int/uint keys?

I am working on implementing `DNS` registry **`Hashmap N ^ResourceRecord`** 
where **N** is domain length and should be `1024 bits`, 128 letters
When I use uint/int I'm limitted to `256bits`, 32 letters or I need to fill all slice with zeros by my own in scm code

**Comment by KStasi** [comment]
> where N is domain length and should be 1024 bits
Not really, it could be less than 1024. 

PFXDICTGET and PFXDICTSET allow you to have a variable length of key slice. You don't need to add extra zeros, you may just put the value for the key with length <= 1024 into your hashmap. Key does not need to be padded.

**Comment by JIoJIaJIu** [comment]
Thank you, I'm going to migrate code on using `prefix dictionaries` then
