### ISSUE TITLE
Сannot get server version and time (server too old?)

### ISSUE THREAD

**Issue by ponchik69** [ton-blockchain/ton#134]
When i connect to my node with  a lite-client i get:
```
[ 1][t 2][1570879659.805462360][lite-client.h:186][!testnode]   conn ready
[ 1][t 2][1570879669.813891172][lite-client.cpp:156][!query]    failed query: [Error : 652 : adnl query timeout]
[ 1][t 1][1570879669.814370155][lite-client.cpp:250][!testnode] cannot get server version and time (server too old?)
[ 1][t 1][1570879669.814419270][lite-client.cpp:262][!testnode] server version is too old (at least 1.1 with capabilities 1 required), some queries are unavailable
[ 1][t 2][1570879679.824642420][lite-client.cpp:156][!query]    failed query: [Error : 652 : adnl query timeout]
[ 1][t 2][1570879679.824710131][lite-client.cpp:292][!query]    cannot get masterchain info from server
```
But I use master branch on git and ```validator-engine``` haven't subcommand some ```version```. And so I can’t understand what's the matter.

The lite-client and validator-engine belong to one build.

**Comment by alesito85** [comment]
Any information about this? I'm experiencing the same. I have the latest master build and whenever I try to connect to my full node's lite server I get these errors.

It does work if I use https://test.ton.org/ton-lite-client-test1.config.json though.

**Comment by ponchik69** [comment]
i think it some coupled with this:
https://github.com/ton-blockchain/ton/issues/6
and this:
https://github.com/ton-blockchain/ton/issues/135
But i'm not shure.

**Comment by ton-blockchain** [comment]
You seem to be running a very old version of the TON FullNode. Compile a newer one from the sources in this repository. It can also happen that you have copied an old version of `validator-engine` into another directory and did not upgrade that copy after recompiling.

**Comment by ponchik69** [comment]
I repeated the building twice on the different nodes and this error repeated. I used master branch on this repository both times.
I think if there was a ```version``` or some subcommand it would be easier to describe the problem.

**Comment by alesito85** [comment]
What seems to "help" is leaving the node to sync for a while (even an hour
or more) and then lite client is able to send commands.

**Comment by slavafomin** [comment]
I'm experiencing the same issue, I'm building all binaries from the master branch on a clean system. Have you managed to overcome this?

**Comment by slavafomin** [comment]
I can confirm that this relates to a server that is unsynced. After syncing the node the errors go away.

I believe that client is incorrectly thinking that the problem is in outdated software version, which is reflected in the first error message: `cannot get server version and time (server too old?)` (notice the question mark).

I think that client should handle this case more gracefully by displaying a more relevant error message like `server is not in sync with the masterchain and should be synchronized first`.

**Comment by EmelyanenkoK** [comment]
The issue is related to the fact that unsynced server does not respond to the lite-client on greeting message. Unfortunately very old versions of LS do not respond at all (whether it is synced or not), so lite-client can not detect is it old or unsynced server.
