### ISSUE TITLE
- La

### ISSUE THREAD

**Issue by ayanwaar** [ton-blockchain/ton#1342]
- La

_Originally posted by @NGUYENDUCCHUNG21 in https://github.com/ton-blockchain/highload-wallet-contract-v3/issues/25#issuecomment-2425529160_

**Comment by NGUYENDUCCHUNG21** [comment]
What ?

Vào Th 6, 1 thg 11, 2567 BE lúc 06:48 ayanwaar ***@***.***>
đã viết:

**Comment by NGUYENDUCCHUNG21** [comment]
Sorry, I'm sorry, to be honest, I don't understand anything about gitthub,
I'm Vietnamese, I don't have Vietnamese, so I have to use google translate,
so the meaning of the sentence will sometimes be wrong with what the app is
used for, I don't know, I don't know, I hope the creator adds Vietnamese so
I


Vào Th 6, 1 thg 11, 2567 BE lúc 14:33 JohnnyGoGoGo ***@***.***>
đã viết:
