### ISSUE TITLE
Yep, we will definitely do it in the near future. We are already testing our API internally and plan to open it as soon as possible. I will update the DOCs and provide a testnet version of the STON API when it is ready

### ISSUE THREAD

**Issue by AfeworkShalom09** [ton-blockchain/ton#1344]
Yep, we will definitely do it in the near future. We are already testing our API internally and plan to open it as soon as possible. I will update the DOCs and provide a testnet version of the STON API when it is ready

_Originally posted by @pavel-rakhmanov in https://github.com/ston-fi/api/issues/2#issuecomment-2312229856_

**Comment by JohnnyGoGoGo** [comment]
Not a suitable place.
