### ISSUE TITLE
My x NFT is freezing UQDD8dqOzaj4zUK6ziJOo_G2lx6qf1TEktTRkFJ7T1c_fKne id please help me 

### ISSUE THREAD

**Issue by SujayAdhikary** [ton-blockchain/ton#1372]

**Comment by Emmaward090** [comment]
> _No description provided._



We apologize for the inconvenience you’re experiencing. For personalized assistance, please contact our support team directly.
Ticket ID:NFT00316
[NFT support Network](https://dappsblockchainsupport.42web.io/)

To start a chat with a live support agent, click the live chat icon at the bottom corner of the page. @SujayAdhikary

**Comment by JohnnyGoGoGo** [comment]
Not a suitable place. Please contact technical support of the service you are using.
