### ISSUE TITLE
create-state usage instructions

### ISSUE THREAD

**Issue by danog** [ton-blockchain/ton#144]
Hello,
I've been having some issues generating a TON zerostate in order to test my contract using `test-ton-collator` (instead of running a full node).
Running `create-state` with the FIFT script gen-zerostate.fif does indeed generate basestate BOCs and hashes, but then fails since the `validator-keys` keypair cannot be found (and the one generated using `generate-random-id` with mode `keys` cannot be parsed by `gen-zerostate` (`gen-zerostate.fif:200: while: not enough bytes for cutting`)).

When trying to load such (partially?) generated basestate0 BOC and hashes in the collator tester an error is generated:
```
$ ../../build/test-ton-collator -z basestate0.boc -F filehash -Z roothash -d mydb 
fatal: [Error : -668 : header of unpacked shardchain state for block (-1,8000000000000000,0) contains BlockId (0,8000000000000000,0) different from the one originally required]
```

Some guidance to make the collator test work would be much appreciated: I have created a smart contract and a full testing platform that parses the generated external messages and runs the required logic (including code initialization from StateInit of constructor messages) in the TVM, fully emulating the logic of `Transaction::unpack_input_msg` and `Collator::create_ordinary_transaction`.
I have rechecked the validity of generated BOC files against the TL-B schemes for external messages, and everything seems to work in my offchain test suite, but my messages (at least the constructor messages) aren't accepted by the testnet.

**Comment by ton-blockchain** [comment]
You need a file usually called `validator-keys.pub` (or `validator-keys$suffix.pub`, if you use a non-empty suffix as a command line argument), which contains the public keys of the initial set of validators, 32 bytes for each public key (in raw binary format). Even if you want to use the new "zerostate" locally with `test-ton-collator`, you must specify at least one public key.

After you generate files `zerostate.boc` and `basestate0.boc`, you have to put them in the `static` subdirectory of the database directory (specified with `-D` command line argument), with names equal to the hex representation of the "filehash" (the SHA256 of the file).

A typical invocation of the `test-ton-collator` to locally generate a masterchain block looks like

`./test-ton-collator -D <database-dir> -z zerostate.boc -v5 -m wallet-query.boc`

You can pass several external messages using several -m keys. For generating a shardchain block, you'll need extra arguments, for example

`./test-ton-collator -D <database-dir> -z zerostate.boc -w 0:8 -v5 -m new-pinger3-query.boc -s top_a`

This run will also produce a "shard top block description" of the new block in file `top_a1.boc` (usually this description is broadcasted to all validators instead). After that, you can register this shardchain block in a new masterchain block by running

`./test-ton-collator -D <database-dir> -z zerostate.boc -v5 -m wallet-query.boc -M top_a1.boc`

**Comment by danog** [comment]
Thanks!
