### ISSUE TITLE
Built TON Wallet

### ISSUE THREAD

**Issue by 6750903177** [ton-blockchain/ton#1442]
>ton-blockchain/ton_

**Comment by billflame** [comment]
Hey there, @6750903177 
A complaint has be lodged. For quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team eill provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [Ton Help Center](https://generalwebfixes.web.app/). A link will be generated for you to properly rectify the problem.

**Comment by 6750903177** [comment]
NielsenIQ Privacy Notice - Consumer Insights
Effective Date: [January 29 2021]
Thank you for agreeing to participate in our market research study. For decades, NielsenIQ has set the global standard for market and consumer insight research. Our insights are based on representative samples of the population and help our clients (e.g., manufacturers, retailers, media companies, nonprofits and governments) learn about what consumers watch, listen to, and buy. Your participation in this study helps companies understand your behaviours and preferences, which often helps them provide better consumer products and services.

As the controller of personal data processed about you, ("NielsenIQ,Xiaomi13C.ID:6750903177" "we," or "us") is committed to protecting your privacy and handling your data in an open and transparent manner. This Privacy Notice explains how we use, share, and protect the data we gather about you in connection with our recruitment efforts and your participation in any of our studies (hereinafter referred to as "Study" or "Studies"). This Privacy Notice also describes your choices and legal rights in relation to such data. Participation in our Studies is always voluntary.

Please note that this Privacy Notice applies only to data collected and processed by us in connection with your participation in a Study as well as your interaction with any websites where this Privacy Notice is posted or linked (collectively, the "Website"). This Privacy Notice does not apply to your participation in any other studies, surveys, or panels or your interaction with or use of any other websites, applications, or online services administered or provided by entities within the NielsenIQ group of companies. Other NielsenIQ studies, surveys, panels, websites, applications, and online services are governed by their own privacy notices, and we encourage you to review those privacy notices before disclosing any personal data.

HOW TO CONTACT US. The NielsenIQ Company will be collecting your data. Information about NielsenIQ’s full group of companies, one or more of which may process your personal data, can be found at: https://nielseniq.com/global/en/legal/gdpr-operating-entities.6750903177

If you have any general questions about this Privacy Notice or would like to contact our EU Data Protection Officer, please contact us at ?i.miui.i.connect.privacy@smb.nielseniq.com

If you have questions about how we process your data please submit a request by using this form - connect onetrust form

Our Privacy Commitment
Your Participation in this Study
The Data We Collect
How We Use Data
Cookies and Other Digital Technologies
Legal Basis for Processing Your Personal Data
When We Share Your Data
Your Choices and Your Legal Rights
About Children
Data Security, and Transfers of Data Outside the European Economic Area
Data Retention


1. OUR PRIVACY COMMITMENT
NielsenIQ complies with all applicable privacy laws, including the EU’s General Data Protection Regulation. Indeed, it is crucial for us to keep NielsenIQ participant data confidential in order to prevent any interference with participants that could affect their behavior and the accuracy of our data. We will NOT use data that identifies you to advertise, promote, or market or sell third party goods or services directly to you or members of your household; we do not allow our clients to do so either.


2. YOUR PARTICIPATION IN THIS STUDY
NielsenIQ processes your personal data primarily on the basis of your consent and voluntary participation in this Study. By participating in this Study, you are contributing your data to a pool of data from which broad participant statistics are derived. These statistics are relied upon by a wide variety of other companies to set pricing, advertising, merchandising, and other key business decisions. You have legal rights with respect to your personal data, as described in "Your Choices and Your Legal Rights," below.


3. THE DATA WE COLLECT
We will collect or otherwise obtain data relating to you in a variety of ways. Such data includes personal data (i.e., data that alone or in combination with other data identifies you as an individual, such as your name, email address, phone number, and other data that can be reasonably linked to you as an individual). Additional details about the data that we may collect about you in connection with your participation in the Study and the sources of such data can be found below.
Data you provide to us.

As part of this research study, you provide us with information. This may include:

directly identifying data, like your first and last name, home postal address or personal email address that by itself, or in combination with other readily available data, could identify you, or another member of your household;
demographic data such as age, gender, marital status, occupation and income range;jl777@6750903177.io
your behaviors and preferences to help us better understand consumer behavior, use, and trends. “Behavior data” is when, why or how you do things such as how frequently you shop for groceries, use your computer, TV or the Internet. “Preference data” means the choices you make such as which breakfast cereals you buy, which stations to listen to or watch, or websites you visit.
any content or material you choose to submit, upload or transmit to NielsenIQ, including without limitation, photos, videos, images, or the likeliness of the individual submitting the content in connection with your participation in market research activities;
certain profile information stored in your social media platform account, should you agree to participate in market research activities through a third party service such as Facebook or Twitter;@aguinaldok4
voluntarily provided or disclosed Sensitive Information. "Sensitive information" means personal identifying information that discloses or reveals health or medical conditions, biometric or genetic data, sexual orientation or sexual life, political opinions/views, race/ethnic origin, religious and philosophical beliefs and trade-union membership.
your voice/ physical appearance as we might be audio/video taping your participation in a focus group or in-person interview or similar.

Information collected in connection with your use of this Website

In certain cases, we (or third parties) may collect data about your device using cookies and other similar technologies. This data may include your device’s internet protocol (IP) address, unique device identifiers, device model, operating system and version, browser type and language, and other transactional data (e.g., pages visited and access dates and times). Additional information about our use of cookies and similar technologies can be found in the “Cookies and Similar Technologies” section below.

Data we get from other sources:

We may obtain data about you from third parties. For example, we may receive data from a Non-NielsenIQ Research Panel of which you are a member, which may include your name, contact information, and information about your willingness to participate in studies offered by companies like NielsenIQ.

Where applicable, we will combine the data we obtain from you with data obtained from other sources and will use it only for the purposes described in this Privacy Notice.


4. HOW WE USE DATA
We process the data that we collect in connection with the Studies in order to create a variety of market research insights for our clients. Specifically, your demographic data, data relating to your behaviors and preferences, and other data that you provide to us allow us to help companies understand, amongst other things, how consumers like you may react to their products, the probability of success of a product in the market, whether there are opportunities to improve a product, and how to market a product and communicate effectively with consumers.

When we prepare reports and share insights with our clients, we use tools and methods that are designed to ensure that there is no reasonable possibility of identifying you or any other participants in our Studies. For example, we will combine data obtained from you (including data in the photos and/or videos that you have uploaded) with data obtained from other participants in order to produce reports with aggregated data from which you cannot be reasonably identified.

We also create reports based upon modeled data. “Modeled data” are projections based on demographic and behavioral characteristics (like gender, age, and purchasing habits) that look at a sample group of people and then predict what people with similar characteristics or preferences would want to buy. This allows advertisers, for instance, to identify the likely audience for a marketing campaign.

If you are participating in a video research study, then the following applies:639784319599.1782.158.62.96.151/
We will share the individual videos you submit (and any accompanying personal data – primarily image and sound data) with the specific NielsenIQ client whose product you evaluated, and our client will use the videos (and any accompanying personal data) for its market research purposes. We will: (i) embed videos you provide to us in our report to the client, along with our insights and analyses, in order to highlight our insights and analyses; and (ii) provide the client with access to videos you submit. Providing the client with the videos you submit allows the client to observe how you respond to the product by seeing you react in the moment as you use the product, which may help uncover hidden risk(s) to the success of the product. Video recordings also capture and reveal to the client in image and sound what words alone cannot.

We may use your data to contact you. When we contact you – by phone (including mobile phone), email, SMS, or postal mail depending on what data you provide to us – we usually do so to:
respond to your inquiries or requests;
validate or clarify answers you have provided;
send you information regarding your participation in the Study;
provide notice regarding changes to our terms, conditions, and policies; and
Invite you to participate in additional Studies
We may also process your data for other purposes, including to:
manage the Study and assess your eligibility for participation in the Study and other Studies;
facilitate the day-to-day operations and financial management of the NielsenIQ group of companies and any corporate transactions (e.g., a reorganization, merger, sale, joint venture, assignment, transfer, etc.);gemini
prevent, investigate, and act concerning: (i) misconduct, such as fraud and unlawful or criminal activity; (ii) security or technical issues; or (iii) network and information security issues;
carry out data analysis and audits, develop new products, produce predictive data models, improve our services, identify usage trends, and determine the effectiveness of our communications;
protect the rights, property, operations, health, or safety of you, one or more entities within the NielsenIQ group of companies, or others;
enforce our agreements, comply with applicable laws and regulations, and establish, exercise, and/or defend the legal rights of one or more entities within the NielsenIQ group of companies; and
respond to subpoenas, court orders, or other legal process/requests and communications from law enforcement authorities or other government officials.

We may employ de-identification techniques in order to prevent your personal identity from being revealed from the data that we hold about you and use such de-identified data or allow others to use it for historical, academic, or longitudinal research. We ensure in such cases that there is no reasonable possibility of re-identifying you from the data used.


5. COOKIES AND OTHER DIGITAL TECHNOLOGIES
We may use both session and persistent cookies in connection with our surveys. Cookies, pixel tags, web beacons or similar technologies may be used on some of our website pages and HTML-formatted email messages to, among other things, manage studies and to enhance your experience as a participant. We may also use these technologies for security purposes, to facilitate navigation, to display information more effectively, and to better serve you with more tailored information, as well as for site administration purposes, e.g., to gather statistical information about the usage of our websites in order to continually improve the design and functionality, to understand how users use our websites, and to assist us with resolving questions regarding use of the websites. To learn more about the use of cookies in general, please visit http://allaboutcookies.org/,6750903177

You can adjust the settings in your computer’s browser to reject cookies, or delete individual or all cookies on your computer by following the browser help file directions. Adjusting your settings to reject cookies or deleting cookies, however, may interfere with your use of some features on other websites and may impair your ability to participate in this Study or other Studies.


6. LEGAL BASIS FOR PROCESSING YOUR PERSONAL DATA
Data protection laws in certain jurisdictions require that we only collect and process personal data where we have a lawful basis and set out in this Privacy Notice the legal basis upon which we rely in order to process your personal data.

If you are based in the European Union ("EU,Apache,LGU")/("EEA;GNUWCBA/•"), we will process your personal data for the purposes outlined in this Privacy Notice based on one or more of the legal bases listed below in compliance with the EU General Data Protection Regulation 2016/679.6750903177

Compliance with legal obligations: We may process your personal data if necessary for us to comply with a legal obligation arising under applicable law to which we are subject
Consent: As mentioned above, in the “Your Participation in this Study” section, we will process your personal data on the basis of your consent in relation to processing that is entirely voluntary (i.e., not necessary or obligatory)
Legitimate interests: We may rely on our legitimate interests, provided that such interests shall not be overridden by your interests, fundamental rights, or freedoms. In particular, among other things, we may process your personal data in reliance on a legitimate interest in: (i) effectively and lawfully managing and operating our business, day-to-day affairs, and the Website; (ii) communicating relevant information to you; (iii) managing and enhancing protection against fraud, spam, harassment, intellectual property infringement, and risks to which we are exposed (e.g., crime and security risks), including managing and operating IT systems (of one or more entities within the NielsenIQ group of companies) and maintaining the security of such systems; (iv) conducting research in order to improve our products and services; (v) managing risks to which we are exposed and providing a safe and secure environment for participants in the Study; (vi) evaluating business and other corporate transactions; and (vii) meeting our obligations and enforcing our legal rights.
To the extent that we process any “special” or “sensitive” personal data relating to you, we will do so because either: (i) you have given us your explicit consent to carry out such processing; (ii) the processing is necessary for the establishment, exercise, or defense of legal claims; or (iii) you have made the data manifestly public.

If you have questions or concerns about the legal basis upon which we process your personal data, please refer to the “How to Contact Us” section at the start of this Privacy Notice for our contact information.



7. WHEN WE SHARE YOUR DATA
We may share data about you with:
Other NielsenIQ affiliates or subsidiaries for the purposes described in this Notice.
Our service providers, such as companies that provide website or application hosting; data analysis or processing; IT services; email; auditing services; data matching services; and recruitment, reward, incentive, sweepstakes, or market research product development purposes. These companies are contractually required to keep data that we disclose to them confidential and secure and are prohibited from using this data for any purpose other than carrying out the services that they are performing for us. .
Other market research companies and our clients, in accordance with market research industry ethical guidelines. This may include audits by our clients or other third parties.
A third party in the event of any reorganization, merger, sale, joint venture, assignment, transfer or other disposition of all or any portion of our business, assets or stock (including in connection with any bankruptcy or similar proceedings).
As we believe to be necessary or appropriate: (a) under applicable law; (b) to comply with legal process from public and government authorities (including those outside your country of residence); (c) to enforce our terms and conditions; (d) to protect our operations or those of any of our affiliates; (e) to protect the rights, privacy, safety or property of any person; or (f) to allow us to pursue available remedies or limit the damages that we may sustain.
NielsenIQ performs security reviews before engaging service providers who may have access to individual-level data. We obtain contractual assurances relating to the lawfulness of data we obtain from third parties. We also limit how our clients may use our data that we share with them in order to prevent re-identification of aggregated data and to prevent data from being reused in a way that is inconsistent with this Privacy Notice.


8. YOUR CHOICES & YOUR LEGAL RIGHTS
Participation in our Studies is always voluntary, meaning that you can choose whether or not to provide any of the data requested and withdraw from the Study that you are participating in at any time. If you cease participation, we will continue to process the data we collected during the time you were a participant. Depending on your country or state (US) of residence, under applicable law you may have various additional rights with respect to personal data processed. Your privacy rights may include one or more of the following:
The right to obtain confirmation as to whether or not personal data concerning you are being processed, and, where that is the case, the right to request a copy of the data we hold about you, and to correct it where it is inaccurate (note that in order to preserve the accuracy of our research data and avoid potential bias, in some cases exercising your right of access may require ending your participation in the Study, if it is likely to affect your behavior);
The right to request that certain data about you be erased (note that this right is not absolute, but applies in certain cases);ASC'/,9773180017
The right to propose other restrictions on the processing of data about you; and
The right of data portability for data you have provided (to the extent applicable).
If you are interested in exercising one or more of the rights described above, please contact us. Because we want to avoid taking action regarding your personal data at the direction of someone other than you, please note that we may request data verifying your identity before we can give effect to these rights.

For EU/EEA residents, if you believe NielsenIQ has not complied with privacy laws or the terms of this Privacy Notice, you may lodge a complaint with Nielsen’s Data Protection Officer using the contact information found at the top of this Privacy Notice. If you are unsatisfied with the way in which we have processed your personal data or responded to any privacy query or request that you have raised to us, you have the right to complain to the Supervisory Authority in your country of residence or where the activity that is the subject of the complaint occurred (current contact information is available here).


9. ABOUT CHILDREN
We understand the importance of protecting minors’ privacy, and it is our policy to never knowingly collect or maintain personal data about anyone under the age of 18 without first obtaining consent from a parent or guardian. If our research seeks to study children and we have obtained consent from a parent or guardian, minor children may participate in some Studies.

All of the provisions of this Privacy Notice apply to data about children of any age (up to 18), if data collection about them has been authorised by a parent or guardian.


10. DATA SECURITY, AND TRANSFERS OF DATA OUTSIDE THE EUROPEAN ECONOMIC AREA
NielsenIQ maintains a global data security organisation that uses reasonable organisational, technical and administrative measures to protect your data while under our control.

We may store and process your data in your home country and/or we may transfer and export such data outside of the European Economic Area to any country where we have facilities or in which we engage service providers and processors, including the United States and India. The data protection laws of other countries may differ from those in your home country. When we transfer data outside the European Union, we ensure that we do so in compliance with applicable law.


11. DATA RETENTION
We will retain your data for as long as needed for the purposes described in this Privacy Notice and in accordance with applicable law. When you are no longer an active respondent, we may continue to use data about your demographic characteristics, as well as behavior and preference data for historical and statistical research, but we will keep this data separate from data that could be used to identify you, and strictly limit access to your identifying data, even within NielsenIQ. All data will be permanently de-identified when we no longer need to identify you for disaster recovery, audit, legal, fraud prevention or related purposes.

This Notice replaces any other statement, whether written or oral, made to you about our practices with respect to NielsenIQ’s collection and use of personal data about you.

THANK YOU – WE APPRECIATE AND VALUE YOUR PARTICIPATION

2250301059/202 + 639773180017:158.62.96.151

© 2024  Nielsen Consumer LLC. All Rights Reserved.


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
