### ISSUE TITLE
Block info from tonlib

### ISSUE THREAD

**Issue by akme** [ton-blockchain/ton#147]
Do you have any plans to add block info related methods to tonlib? Such as getblock/dumpblock in lite-client?

**Comment by rbndg** [comment]
Yes, this is standard in all blockchains. I need a way to get all transactions in a given block

**Comment by ton-blockchain** [comment]
If you are willing to receive the block as a binary bag-of-cells, this would be easy. If you want more structured output, similar to that of `dumpblock`, this would increase the size of the library, and, more importantly, generate ~10MiB of text for a 512k block. What would you do with this text afterwards?

**Comment by rbndg** [comment]
I need to get all transactions in a given block, this is a standard feature and commonly used feature in all blockchains.

**Comment by akme** [comment]
If you’ll provide the way of decoding such binary format so we can get all needed info, it also could work

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rbndg** [comment]
Yes, i don't really mind how we get the information, as long as there is a documented standard method to get it

**Comment by webresult** [comment]
There is raw.getTransactions method inside tonlibjson. I want to fetch all transactions from each of blocks. So I need a method, that gives me a response like raw.getTransactions but for block

**Comment by ton-blockchain** [comment]
Why do you need to fetch all transactions from a block?

The primary purpose of TONLib is to simplify creation of wallets and similar client applications, not to replace the blockchain explorer, the LiteClient and other similar tools.

**Comment by akme** [comment]
Everybody wants developers-friendly instruments without the need to go low-level with C++  as you suggest in #76. So TONLib is the one that people know how to use from different languages and this is the reason for asking you to add at least so basic requests there where they can make use of it.
It's ok that you want to keep separate API separate and if you'll provide more developers-friendly ways to interact with them it would be awesome, but now even for the basic needs of developers, we are forced to build solutions from shit and sticks :volcano: That's no good for mass adoption :suspect:

**Comment by alexqrid** [comment]
> Everybody wants developer-friendly instruments without the need to go low-level with C++ as you suggest in #76. So TONLib is the one that people know how to use from different languages and this is the reason for asking you to add at least so basic requests there where they can make use of it.
> It's ok that you want to keep separate API separate and if you'll provide more developers-friendly ways to interact with them it would be awesome, but now even for the basic needs of developers, we are forced to build solutions from shit and sticks  That's no good for mass adoption
Actually, agree with mentioned above. It's better to provide more friendly API for mass adoption. 
At least It would be a way to provide users with much more user-friendly statistical applications if you do it.

**Comment by rbndg** [comment]
A JSON-RPC api or gRPC api is the right way to do this I believe.
