### ISSUE TITLE
In fift comments require space 

### ISSUE THREAD

**Issue by raiym** [ton-blockchain/ton#150]
This will give interpreter error: 
```
//<b
``` 
But this will run fine: 
```
// <b
```

**Comment by ton-blockchain** [comment]
Yes, this is indeed so. We thought it was better this way, so that other words beginning with `//` could be defined. If you are unhappy with this choice, you can always redefine `//`:

`' // ::_ //`

**Comment by raiym** [comment]
Oh, I see.
Thanks for clarifying
