### ISSUE TITLE
GetNext on dict in nested loop failed

### ISSUE THREAD

**Issue by AkKoks** [ton-blockchain/ton#153]
For example we have func code:
```
;; load from external msg
cell dict1 = load_dict1();
;; load from persistent data
cell dict2 = load_dict2();
int dict1_pos = -1;
do {
  (dict1_pos, slice cs1, int ret1) = dict1.udict_get_next?(32, dict1_pos);
  int dict2_pos = -1;
  do {
    (dict2_pos, slice cs2, int ret2) = dict2.udict_get_next?(32, dict2_pos);
    ;; do something with cs1 and cs2
  } until (~ ret2);
} until (~ ret1);
```
When I run this code in the Fift TVM, it works correctly. For each dict1 elem nested loop gets all dict2 elems. But when i try deploy a smc with this code - it fails. Empirically I found that smc init fails at operation `(dict2_pos, slice cs2, int ret2) = dict2.udict_get_next?(32, dict2_pos);`

Please can you explain this behavior?

**Comment by ton-blockchain** [comment]
How large are the two dictionaries? Have you noticed gas consumed while running this code in Fift TVM? Is this code run after `accept()` or before?

Notice that a dictionary operation with a dictionary containing N keys will require O(N log N) cell load operations, each worth at least 100 gas. Gas price is currently set to 10^(-6) grams per gas unit in the workchain, 10^(-5) in the masterchain, the gas limit is 10^6 gas units per smart contract execution (once you run `accept()`), gas credit is 10000 gas units. Of course, there are just the somewhat arbitrary settings for the testnet.

**Comment by AkKoks** [comment]
> How large are the two dictionaries? - Less or equal than 10.
> Have you noticed gas consumed while running this code in Fift TVM? Yes,

**Comment by ton-blockchain** [comment]
Well, you cannot run a lot of logic before `accept`. In this example, you try to consume 21266 gas, but the gas credit is only 10000 gas units.

**Comment by AkKoks** [comment]
Oh, thank you! I misunderstood `acept()` work. I thought it should be used when I ready to finish handle this message. Now smc could been deploy.
