### ISSUE TITLE
Script ton/crypto/smartcont/gen-zerostate.fif won't run

### ISSUE THREAD

**Issue by leedioxin** [ton-blockchain/ton#156]
I'm working from commit 9c9248a9ae1791152d88c9c36574b4becdf5e8b6

If I try to run the gen-zerostate script, I get an error on line 7.

[ 1][t 0][1571253062.931130171][words.cpp:2906] gen-zerostate.fif:7: wc_master: -?
[ 1][t 0][1571253062.931397915][fift-main.cpp:196]      Error interpreting file `/home/tonton/source/ton/crypto/smartcont/gen-zerostate.fif`: error interpreting included file `gen-zerostate.fif` : gen-zerostate.fif:7: wc_master: -?

If I comment out the line, the error just keeps moving to the next uncommented line.

I was hoping to be able to create myself a zero state so I could test out some validator actions in a private network.

**Comment by ton-blockchain** [comment]
You should use `create-state` instead of `fift` to execute this (undocumented) script. See also issue #144.

**Comment by leedioxin** [comment]
Thanks!  If this script isn't supported, I'll just close this issue and refer to the other script and #144.
