### ISSUE TITLE
Directories for Full Node and Validator

### ISSUE THREAD

**Issue by volayvaz** [ton-blockchain/ton#158]
In the documentation, you mentioned that it is better to use two separate partitions for "Full Node" one backed up by SSD and another one by HDD. The validator has its {DB_ROOT} directory, where it should be placed on SSD or HDD? Which data to store on HDD/SSD?

Thank you!

**Comment by ton-blockchain** [comment]
If you have both a HDD and a SSD, put {DB_ROOT} on SSD, but {DB_ROOT}/archive on HDD, by using a symlink or by mounting a HDD partition at this directory.
