### ISSUE TITLE
Account balance depletion vulnerability

### ISSUE THREAD

**Issue by JIoJIaJIu** [ton-blockchain/ton#159]
## Case
accept_message is used in recv_internal, that allows to send message with error or less then required amount of grams and deplete account balance

## Overview
We had [conversation](https://contest.com/blockchain/entry373) with [Chick Dolphin](https://contest.com/blockchain/entry369). We thought about the case when somebody send a message that can pass first level of checking but fails after. For external message - it's ok cause I send my message and should care about structure of message, but internal message can come from anywhere. Basic on it I've got that `accept_message` should be used only in `recv_external`, what isn't really intuitive. But that's not all

There is existed [TON fc](https://github.com/ton-blockchain/ton/blob/9c9248a9ae1791152d88c9c36574b4becdf5e8b6/crypto/smartcont/elector-code.fc#L157), which uses `accept_message` in methods which is invoked from `recv_internal`. Most of them doesn't contain after `accept_message` place for error (all variables already are fetched), but it's not obviously and provide area for making mistake 

## Proposal
Remove ACCEPT instruction and [control balance](https://github.com/ton-blockchain/ton/blob/9c9248a9ae1791152d88c9c36574b4becdf5e8b6/crypto/block/transaction.cpp#L970) outside the TVM into transaction

**Comment by ton-blockchain** [comment]
If you don't want to use `ACCEPT` in `recv_internal`, don't. Then only the value of the inbound internal message will be spent for gas.

**Comment by JIoJIaJIu** [comment]
@ton-blockchain
I've opened the issue not about wish of the instruction usage or unwillingness, but mostly about the case when its usage can lead to vulnerability with an accent that it's **not obviously** (for me at least). I would be glad to get your comments about the case - maybe I've understood wrongly the logic or the behavior is expected (split message fees between sender and receiver):

1. SCM creator adds `ACCEPT` to `recv_internal`
2. Malefactor starts to send corrupted messages that throws an error after `ACCEPT` or the messages with less amount grams that required
3. SCM balance starts to deplete 

I've got that you mean that the scm author should care about his scm

**Comment by rainydio** [comment]
There are probably legitimate use cases for accept in recv_internal. And I guess it's to late, but I'd rather suggest renaming `ACCEPT` into `BUYGASMAX`, so it's obvious what it actually does.

**Comment by EmelyanenkoK** [comment]
Note, that for auto-depletion message should be replayed. So the issue only affects `recv_external` calls, not `recv_internal`: if contract throws in `recv_internal` after accept the only way that contract will pay for gas is if it consumed more gas than can be bough for message value. And no auto-replays.
Regarding `recv_external` it is known behavior that there should not be possible to cause throws after ACCEPT.
