### ISSUE TITLE
Lite client error

### ISSUE THREAD

**Issue by alexqrid** [ton-blockchain/ton#161]
Lite client's ` status ` command is not working at all. Displays the message about unknown command.

![image](https://user-images.githubusercontent.com/30272185/67149526-d39fa180-f2b4-11e9-8df7-2e9fb77e0370.png)

Also ` getstate ` never works properly:
![image](https://user-images.githubusercontent.com/30272185/67149602-cc2cc800-f2b5-11e9-9b82-72a5bdcd29af.png)

**Comment by ton-blockchain** [comment]
`getstate` sometimes works for the workchain 0. The state of the masterchain is too large to be generated and downloaded by means of this query.
`status` never worked. Maybe we should make it output some generic information.
