### ISSUE TITLE
Unable to include smartcontract #4 when generating zero-state

### ISSUE THREAD

**Issue by leedioxin** [ton-blockchain/ton#166]
When attempting to create a zero state block with create-state, I'm getting an error when trying to register smc #4 

tonton@ip-10-5-1-13:~/source/crypto$ ./create-state ../ton/crypto/smartcont/gen-zerostate-test.fif 

initial basechain state is:
x{9023AFE2FFFFFFEF0000000000800000000000000000000000000000005DAF4C240000000000000000FFFFFFFF2_}
 x{00000000000000001_}
 x{001_}
 x{00000000000000000000000000000000000}

B5EE9C72E1010401005600667C84AC035B9023AFE2FFFFFFEF0000000000800000000000000000000000000000005DAF4C240000000000000000FFFFFFFF2001020300110000000000000000100003001000230000000000000000000000000000000000086F52700A
(Initial basechain state saved to file basestate0.boc)
file hash=17b4e71a9e0e1cac86b98f494fc4b046abcd995b177c228eb51c8981fa0d0cc0  F7TnGp4OHKyGuY9JT8SwRqvNmVsXfCKOtRyJgfoNDMA=
root hash=4f739010168949d917e1d90e7a94a360ae120fdab1f65b17350b4f02034c9699  T3OQEBaJSdkX4dkOepSjYK4SD9qx9lsXNQtPAgNMlpk=
Loading private key from file main-wallet.pk
wallet address = -1:1c5175021ff077df1d84d10adfe35af217772f89f772e2bf4e81c9e238ce6f09 
kf8cUXUCH_B33x2E0Qrf41ryF3cvifdy4r9OgcniOM5vCSdN
(Saving address to file main-wallet.addr)
free test gram giver address = -1:8156775b79325e5d62e742d9b96c30b6515a5cd2f1f64c5da4b193c03f070e0d 
kf-BVndbeTJeXWLnQtm5bDC2UVpc0vH2TF2ksZPAPwcODZKR
(Saving address to file testgiver.addr)
address = 25c6cdb5aa85ce33fd0ea7484dceecd4a33f0bd1a39f1ac68e5c7b882e7c4ddc 
[ 1][t 0][1571769380.578484535][words.cpp:2856] gen-zerostate-test.fif:130: register_smc: not a cell
Error interpreting file `../ton/crypto/smartcont/gen-zerostate-test.fif`: [Error : 0 : error interpreting included file `gen-zerostate-test.fif` : gen-zerostate-test.fif:130: register_smc: not a cell]
tonton@ip-10-5-1-13:~/source/crypto$ 

===
If I edit gen-zerostate-test.fif and look at line 124 it looks like we're trying to include the elector smc simply by including its source.

I did also try to put all of the content of /home/tonton/source/ton/crypto/smartcont/auto/elector-code.fif inline instead of using the include, but I still got an error complaining about "not a cell".  I assume that the top of the stack.

**Comment by leedioxin** [comment]
Follow-up:
In gen-zerostate-test.fif, after the script and data, if I copy an empty libraries cell from the previous smc and insert it, the registration seems to work (the line numbers are big because I've also copy-pasted the elector contract inline in the same file.):

1840 <b 0 1 1+ 1+ 5 + u, 0 256 u, b>  // data
1841 Libs{
1842   x{ABACABADABACABA} s>c public_lib
1843   x{1234} x{5678} |_ s>c public_lib
1844 }Libs  // libraries
1845 GR$10  // balance: 10 grams
1846 0 // split_depth
1847 1 // ticktock: tick
1848 2 // mode: create
1849 register_smc
1850 dup make_special dup constant smc4_addr dup constant elector_addr



=====

After doing this, I'm getting a new script error.  I'll probably try opening a new issue for that one.

Would it be best for me to leave this issue open?  I suspect my dirty workaround isn't what your team will want for a solution.

**Comment by ton-blockchain** [comment]
Use (or edit a copy of) `gen-zerostate.fif`, because `gen-zerostate-test.fif` is not up to date.

**Comment by leedioxin** [comment]
Thanks
