### ISSUE TITLE
Multisig vulnerability

### ISSUE THREAD

**Issue by koinov** [ton-blockchain/ton#168]
I just checked your multisig contract and I really believe it is vulnerable. You accept incoming order if just one signature is valid. I believe this is a big mistake since one compromised private key can lead to draining funds from smart contract by submitting multiple external transactions with new orders. 

I believe right solution is not to accept messages signed by less than predefined number of signatures or use internal messages sent through participants wallets. 

This problem is described in my contest submission at 
https://contest.com/blockchain/entry390 in readme.txt within /multisig folder.

**Comment by koinov** [comment]
Since this issue is still unsolved I tried to enforce your wallet, that is very well done and optimized,  and added minimum required K parameter for every new request, so new request message is accepted only when number of valid signatures reaches this value.

You can check [https://github.com/koinov/ton-multisig-enforced](https://github.com/koinov/ton-multisig-enforced) and particularry [this commit](https://github.com/koinov/ton-multisig-enforced/commit/5367dd30d5a43f8d586c7fd36c9e13a2042c3d87#diff-a02494c4146eb5e928a753616542a593)

I also added FIFT scripts and some tests. 

If you think this way is meaningful, I will be happy to do more tests, work on scripts and I also believe CLI is necessary for better MultiSig interaction.

**Comment by koinov** [comment]
Here's the another, and I believe more elegant solution that eliminate the possibility of draining all the funds from original multisig contract when one private key is compromised.   

I've added unconfirmed orders limit parameter to the smart contract, so when number of new orders reaches the limit all new orders signed by the private key are reverted. This counter is reset as soon as any order is confirmed by at least K number of signatures. 

This solution allows creating orders with the single key, that is really great, so no off-chain interactions between parties is required. 

You can check [https://github.com/koinov/ton-multisig-enforced-limit](https://github.com/koinov/ton-multisig-enforced-limit) and particularly this [commit](https://github.com/koinov/ton-multisig-enforced-limit/commit/020a9605afc77ca428ee0b155fd395e33395e4d4) 

I believe this is the only safe and efficient way of operating multisig wallet using external messages.

**Comment by rainydio** [comment]
Hey, here is my approach https://github.com/rainydio/ton-tolerant-personal-multisig/blob/master/code.fc

I started with assumption that multisig is used by a single company (e.g. exchange), where several clients are signing the same stream of orders with different keys. Orders are executed in-order (controlled by `seqno), but may be accepted out of order (controlled by `tolerance` parameter). Once queue is filled no new orders are accepted. If the mistake was made, or malicious key filled the queue it's possible to sent `reset` vote, which will wipes the queue out.

One more thing, I haven't seen used anywhere. Instead of having separate initialization branch of code I `ACCEPT ` constructor message and swap the code with actual contract code. `<{ SETCP0 ACCEPT "ContractCode.fif" include PUSHREF SETCODE }>c`.

Feel free to incorporate any of those ideas into your implementation @koinov

**Comment by rainydio** [comment]
I was worried that malicious key might blow the pending orders dictionary to some extreme size preventing legitimate message from ever reaching `accept_message`. Hence reset is a short-cut, and very lightweight on gas.

**Comment by koinov** [comment]
We definitely need to find ideal balance between usability, security and optimisation. I believe original TON implementation has great functionality, perfect code and the only problem was this issue with malicious or compromised co-owner. I believe last fix is rather good solution.

**Comment by koinov** [comment]
What about the size of the message, I believe there is a TODO inside the contract limiting gas consumption, so I'm sure this will be fixed very soon on TVM level.

**Comment by koinov** [comment]
Hi man, nice seeing you here, your public testing was highly appreciated!
We definitely need to find ideal balance between usability, security and optimisation. I believe original TON implementation has great functionality, perfect code and the only problem was this issue with malicious or compromised co-owner. I believe last fix is rather good solution.

What about the size of the message, I believe there is a TODO inside the contract limiting gas consumption, so I'm sure this will be fixed very soon on TVM level.

**Comment by koinov** [comment]
Updated multisig is looking good!
