### ISSUE TITLE
Generating zero-state: Failing to configure gas prices in script

### ISSUE THREAD

**Issue by leedioxin** [ton-blockchain/ton#169]
When trying to use create-state to make a private testnet, I'm getting an error when configuring the gas price.

tonton@ip-10-5-1-13:~/source/crypto$ ./create-state ../ton/crypto/smartcont/gen-zerostate-test.fif 

initial basechain state is:
x{9023AFE2FFFFFFEF0000000000800000000000000000000000000000005DB07CCD0000000000000000FFFFFFFF2_}
 x{00000000000000001_}
 x{001_}
 x{00000000000000000000000000000000000}

B5EE9C72E1010401005600667C84AC035B9023AFE2FFFFFFEF0000000000800000000000000000000000000000005DB07CCD0000000000000000FFFFFFFF200102030011000000000000000010000300100023000000000000000000000000000000000008ECE079FB
(Initial basechain state saved to file basestate0.boc)
file hash=99135afffeb074a9a9819e152d6a845c95b356d6c41e862def4a6c020a1ca4a8  mRNa__6wdKmpgZ4VLWqEXJWzVtbEHoYt70psAgocpKg=
root hash=945a38987d97347e3935afe1750bdfc8d75fa0d5ed40850e3106a3ad3613d08c  lFo4mH2XNH45Na_hdQvfyNdfoNXtQIUOMQajrTYT0Iw=
Loading private key from file main-wallet.pk
wallet address = -1:1c5175021ff077df1d84d10adfe35af217772f89f772e2bf4e81c9e238ce6f09 
kf8cUXUCH_B33x2E0Qrf41ryF3cvifdy4r9OgcniOM5vCSdN
(Saving address to file main-wallet.addr)
free test gram giver address = -1:8156775b79325e5d62e742d9b96c30b6515a5cd2f1f64c5da4b193c03f070e0d 
kf-BVndbeTJeXWLnQtm5bDC2UVpc0vH2TF2ksZPAPwcODZKR
(Saving address to file testgiver.addr)
address = 25c6cdb5aa85ce33fd0ea7484dceecd4a33f0bd1a39f1ac68e5c7b882e7c4ddc 
[ 1][t 0][1571847373.897860289][words.cpp:2906] gen-zerostate-test.fif:1868: config.gas_prices!: integer does not fit into cell
Error interpreting file `../ton/crypto/smartcont/gen-zerostate-test.fif`: [Error : 0 : error interpreting included file `gen-zerostate-test.fif` : gen-zerostate-test.fif:1868: config.gas_prices!: integer does not fit into cell]
tonton@ip-10-5-1-13:~/source/crypto$ 

==
The corresponding script location ...

1852 // Configuration Parameters
1853 
1854 // max-validators max-main-validators min-validators
1855 // 9 3 2 config.validator_num!
1856 1000 100 5 config.validator_num!
1857 // min-stake max-stake min-total-stake max-factor
1858 GR$10000 GR$10000000 GR$1000000 sg~10 config.validator_stake_limits!
1859 // elected-for elect-start-before elect-end-before stakes-frozen-for
1860 400000 200000 4000 400000 config.election_params!
1861 // elector-addr
1862 elector_addr config.elector_smc!
1863 
1864 1 sg* 100 sg* 1000 sg* 1000000 sg* config.storage_prices!
1865 config.special!
1866 
1867 // gas_price gas_limit gas_credit block_gas_limit freeze_due_limit delete_due_limit --
1868 1000 sg* 1000000 10000 10000000 GR$0.1 GR$1.0 config.gas_prices!
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1869 10000 sg* 1000000 10000 10000000 GR$0.1 GR$1.0 config.mc_gas_prices!
1870 // lump_price bit_price cell_price ihr_factor first_frac next_frac

**Comment by ton-blockchain** [comment]
gen-zerostate-test.fif is outdated. In particular, `config.gas_prices!` now takes more parameters. Try looking into gen-zerostate.fif.

**Comment by leedioxin** [comment]
Thanks - I just noticed that I could get gen-zerostate.fif to run.

I guess I was pretty fixated on making a test network.  If these issues are of no further use, I can close them out.  Want me to?

**Comment by leedioxin** [comment]
Will close ... I'll switch to gen-zerostate.fif
