### ISSUE TITLE
Error on custom build on windows

### ISSUE THREAD

**Issue by adyshimony** [ton-blockchain/ton#17]
Hi, I am having error on windows build:

ClCompile:
  All outputs are up-to-date.
Link:
  All outputs are up-to-date.
  tlbc.vcxproj -> C:\Sources\TON\lite-client-build\crypto\Debug\tlbc.exe
FinalizeBuildStatus:
  Deleting file "tlbc.dir\Debug\tlbc.tlog\unsuccessfulbuild".
  Touching "tlbc.dir\Debug\tlbc.tlog\tlbc.lastbuildstate".
Done Building Project "C:\Sources\TON\lite-client-build\crypto\tlbc.vcxproj" (default targets).

InitializeBuildStatus:
  Touching "Win32\Debug\tlb_generate_block\tlb_gene.439E29B7.tlog\unsuccessfulbuild".
CustomBuild:
  Generate block tlb source files
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code -1073741701. [C:\Sources\TON\
lite-client-build\crypto\tlb_generate_block.vcxproj]
Done Building Project "C:\Sources\TON\lite-client-build\crypto\tlb_generate_block.vcxproj" (default targets) -- FAILED.

Done Building Project "C:\Sources\TON\lite-client-build\crypto\ton_block.vcxproj" (default targets) -- FAILED.

Done Building Project "C:\Sources\TON\lite-client-build\lite-client\lite-client.vcxproj" (default targets) -- FAILED.

Build FAILED.

"C:\Sources\TON\lite-client-build\lite-client\lite-client.vcxproj" (default target) (1) ->
"C:\Sources\TON\lite-client-build\crypto\ton_block.vcxproj" (default target) (23) ->
"C:\Sources\TON\lite-client-build\crypto\tlb_generate_block.vcxproj" (default target) (24) ->
(CustomBuild target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code -1073741701. [C:\Sources\TO
N\lite-client-build\crypto\tlb_generate_block.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:04.15

Thanks

**Comment by EmelyanenkoK** [comment]
Please check [workflows](https://github.com/ton-blockchain/ton/tree/master/.github/workflows) as guide.
