### ISSUE TITLE
tonlibjson

### ISSUE THREAD

**Issue by webresult** [ton-blockchain/ton#171]
Methods wallet.init and exportKey which contain input_key  become returning error after last update 

`Failed to parse [request:{\042@type\042:\042exportKey\042,\042input_key\042:{\042@type\042:\042inputKeyRegular\042,\042local_password\042:\042cGFzc3dvcmQ\042,\042key\042:{\042public_key\042:\042PuYjDPGuKeY6u95ozZGhl1Z6Xz1NYiNDuiOH17I-BsqeyFGh\042,\042secret\042:\042GKRJi9UjXn+2wada7p8XLj/trsurCaYyAFJOR/wICjE=\042}}}] [Error : 0 : Wrong string length]`

It looks like something went wrong with input_key processing.
How can I fix it?

**Comment by ton-blockchain** [comment]
`cGFzc3dvcmQ` is not a valid base64 encoded string. I lacks `=` at the end.

**Comment by webresult** [comment]
It needed base64url encoding. And it worked before last commit. Now it needs just base64?

**Comment by webresult** [comment]
It works with base64 encoding, thx. 
About new commit. What is the difference between raw.createAndSendMessage and raw.sendMessage? New method doesn't return something new, just {"@type":"ok"} if all ok. When I should use raw.createAndSendMessage and what this method creates?

**Comment by ton-blockchain** [comment]
`raw.sendMessage` is like `sendfile` from lite-client. It just sends a given message to lite-server. It takes `body:bytes` as an argument.

`raw.createAndSendMessage`  is renamed `raw.sendMessage` from previous version.
It takes its arguments, creates [Message](https://github.com/ton-blockchain/ton/blob/master/crypto/block/block.tlb#L147), serializes it and sends it in the same way as new `raw.sendMessage` does.
