### ISSUE TITLE
tonlibjson incorrect mnemonics

### ISSUE THREAD

**Issue by akme** [ton-blockchain/ton#177]
Tried to import wallet with mnemonics generated by tonlibjson [go-library](https://github.com/mercuryoio/tonlib-go), but wallet says it's incorrect, same actions, but with tonlib-cli gives success.
Is there any chance that tonlibjson gives us words in wrong order?

**Comment by ton-blockchain** [comment]
Go library uses non-empty mnemonic password.

**Comment by akme** [comment]
Thank you, fixed go library, now everything works well
