### ISSUE TITLE
No SETLIBS operation in TVM (similar to SETCODE)

### ISSUE THREAD

**Issue by rainydio** [ton-blockchain/ton#182]
I was attempting to implement *constructor contract* which replaces data, code, and libs from storage. This is to avoid workarounds such as checking that seqno is zero, or signing init message to pass signature checks. But I cannot find the way to replace contract libs. Although I can simply leave them intact, the question remains. Is TVM missing `SETLIBS` operation?

**Comment by ton-blockchain** [comment]
Note that `SETLIBCODE` and `CHANGELIB` instructions have been added to TVM in commit 090e0c16eb86184eaa3fda0e5d1c9838cf2ff88e

**Comment by rainydio** [comment]
Allright then
