### ISSUE TITLE
Error: Can't create directory

### ISSUE THREAD

**Issue by ank-everstake** [ton-blockchain/ton#184]
After [commit](https://github.com/ton-blockchain/ton/commit/3d51e417661a00a0b890e1dc62fce0969628eebe) the validator-engine repeatedly catches an error about creating the directories: 

```
First:
[ 0][t 2][1573833223.347395658][Status.h:261][!archive]	Unexpected Status [PosixError : No such file or directory : 2 : Can't create directory "/mnt/operational/TONtest/dbfiles/packages/"] in file /home/ton/ton-sources/ton/validator/db/archive-manager.cpp at line 516

Second try:
[ 0][t 4][1573834046.670448542][Status.h:261][!archive]	Unexpected Status [PosixError : No such file or directory : 2 : Can't create directory "/mnt/operational/TONtest/dbarchive/packages/arch0000/"] in file /home/ton/ton-sources/ton/validator/db/archive-manager.cpp at line 516
```

After the first error I created **/mnt/operational/TONtest/dbfiles/packages**, but I think the issue is the wrong db root dir that it calculates. 
In my case it is **/mnt/operational/TONtest/db**.

Previously it worked well. So most probably it brokedown after the commit.
I use this command for launch:
`./validator-engine -C /mnt/operational/TONtest/etc/ton-global.config.json --db /mnt/operational/TONtest/db -l /mnt/operational/TONtest/log/error.log -I 148.251.91.50:9200 -d &`

**Comment by akme** [comment]
Same for me:
```
[ 0][t 6][1573833966.467825413][Status.h:261][!archive]	Unexpected Status [PosixError : No such file or directory : 2 : Can't create directory "/var/ton-work/dbfiles/packages/"] in file /ton/validator/db/archive-manager.cpp at line 516
```
is there any update to new directory structure?

**Comment by akme** [comment]
Commit https://github.com/ton-blockchain/ton/commit/0dae2c157b55b8a9640efad5947a6a3df171cd02 helped, node successfully started
