### ISSUE TITLE
Try to compiling new version lite node

### ISSUE THREAD

**Issue by mitagmio** [ton-blockchain/ton#185]
`root@node01:~# git clone https://github.com/ton-blockchain/ton.git
Cloning into 'ton'...
remote: Enumerating objects: 145, done.
remote: Counting objects: 100% (145/145), done.
remote: Compressing objects: 100% (138/138), done.
remote: Total 2940 (delta 25), reused 40 (delta 6), pack-reused 2795
Receiving objects: 100% (2940/2940), 11.17 MiB | 9.56 MiB/s, done.
Resolving deltas: 100% (1537/1537), done.
root@node01:~# mkdir liteclient-build2
root@node01:~# cd ~/liteclient-build2
root@node01:~/liteclient-build2# cmake ~/ton
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CRC32C_HAVE_SSE42
-- Performing Test CRC32C_HAVE_SSE42 - Success
-- Performing Test ROCKSDB_HAVE_SSE42
-- Performing Test ROCKSDB_HAVE_SSE42 - Success
Add abseil-cpp
CMake Error at CMakeLists.txt:92 (add_subdirectory):
  The source directory

    /root/ton/third-party/abseil-cpp

  does not contain a CMakeLists.txt file.

Add crc32c
CMake Error at CMakeLists.txt:111 (add_subdirectory):
  The source directory

    /root/ton/third-party/crc32c

  does not contain a CMakeLists.txt file.

Add rocksdb
CMake Error at CMakeLists.txt:122 (add_subdirectory):
  The source directory

    /root/ton/third-party/rocksdb

  does not contain a CMakeLists.txt file.

Add ton
-- Found ccache
-- Performing Test HAVE_STD14
-- Performing Test HAVE_STD14 - Success
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
-- Performing Test HAVE_CXX_FLAG_WALL
-- Performing Test HAVE_CXX_FLAG_WALL - Success
-- Performing Test HAVE_CXX_FLAG_WEXTRA
-- Performing Test HAVE_CXX_FLAG_WEXTRA - Success
-- Performing Test HAVE_CXX_FLAG_WIMPLICIT_FALLTHROUGH_2
-- Performing Test HAVE_CXX_FLAG_WIMPLICIT_FALLTHROUGH_2 - Success
-- Performing Test HAVE_CXX_FLAG_WPOINTER_ARITH
-- Performing Test HAVE_CXX_FLAG_WPOINTER_ARITH - Success
-- Performing Test HAVE_CXX_FLAG_WCAST_QUAL
-- Performing Test HAVE_CXX_FLAG_WCAST_QUAL - Success
-- Performing Test HAVE_CXX_FLAG_WSIGN_COMPARE
-- Performing Test HAVE_CXX_FLAG_WSIGN_COMPARE - Success
-- Performing Test HAVE_CXX_FLAG_WDUPLICATED_BRANCHES
-- Performing Test HAVE_CXX_FLAG_WDUPLICATED_BRANCHES - Success
-- Performing Test HAVE_CXX_FLAG_WDUPLICATED_COND
-- Performing Test HAVE_CXX_FLAG_WDUPLICATED_COND - Success
-- Performing Test HAVE_CXX_FLAG_WALLOC_ZERO
-- Performing Test HAVE_CXX_FLAG_WALLOC_ZERO - Success
-- Performing Test HAVE_CXX_FLAG_WLOGICAL_OP
-- Performing Test HAVE_CXX_FLAG_WLOGICAL_OP - Success
-- Performing Test HAVE_CXX_FLAG_WTAUTOLOGICAL_COMPARE
-- Performing Test HAVE_CXX_FLAG_WTAUTOLOGICAL_COMPARE - Success
-- Performing Test HAVE_CXX_FLAG_WVLA
-- Performing Test HAVE_CXX_FLAG_WVLA - Success
-- Performing Test HAVE_CXX_FLAG_WNON_VIRTUAL_DTOR
-- Performing Test HAVE_CXX_FLAG_WNON_VIRTUAL_DTOR - Success
-- Performing Test HAVE_CXX_FLAG_WUNUSED_PARAMETER
-- Performing Test HAVE_CXX_FLAG_WUNUSED_PARAMETER - Success
-- Performing Test HAVE_CXX_FLAG_WCONVERSION
-- Performing Test HAVE_CXX_FLAG_WCONVERSION - Success
-- Performing Test HAVE_CXX_FLAG_WSIGN_CONVERSION
-- Performing Test HAVE_CXX_FLAG_WSIGN_CONVERSION - Success
-- Performing Test HAVE_CXX_FLAG_QUNUSED_ARGUMENTS
-- Performing Test HAVE_CXX_FLAG_QUNUSED_ARGUMENTS - Failed
-- Performing Test HAVE_CXX_FLAG_WUNUSED_PRIVATE_FIELD
-- Performing Test HAVE_CXX_FLAG_WUNUSED_PRIVATE_FIELD - Failed
-- Performing Test HAVE_CXX_FLAG_WREDUNDANT_MOVE
-- Performing Test HAVE_CXX_FLAG_WREDUNDANT_MOVE - Failed
-- Found LATEX: /usr/bin/latex
-- Found UnixCommands: /bin/bash
-- I could not find the biber command.
-- I could not find the ps2pdf command.
-- I could not find the pdftops command.
-- Disabling HTML build for ton_white_paper.tex because the main file is in subdirectory doc
-- Disabling HTML build for ton_vm_description.tex because the main file is in subdirectory doc
-- Disabling HTML build for ton_blockchain_description.tex because the main file is in subdirectory doc
-- Disabling HTML build for fift_basic_description.tex because the main file is in subdirectory doc
-- Found ZLIB: /usr/include /usr/lib/x86_64-linux-gnu/libz.so
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.1")
CMake Error at CMakeLists.txt:332 (get_target_property):
  get_target_property() called with non-existent target
  "absl::flat_hash_map".
Call Stack (most recent call first):
  tdutils/CMakeLists.txt:320 (target_link_libraries_system)

CMake Error at CMakeLists.txt:332 (get_target_property):
  get_target_property() called with non-existent target
  "absl::flat_hash_set".
Call Stack (most recent call first):
  tdutils/CMakeLists.txt:320 (target_link_libraries_system)

CMake Error at CMakeLists.txt:332 (get_target_property):
  get_target_property() called with non-existent target "absl::hash".
Call Stack (most recent call first):
  tdutils/CMakeLists.txt:320 (target_link_libraries_system)

-- Performing Test GNU_READLINE_FOUND
-- Performing Test GNU_READLINE_FOUND - Success
-- Found Readline: /usr/include
-- Found Readline: /usr/include /usr/lib/x86_64-linux-gnu/libreadline.so
-- Performing Test USABLE_READLINE_FOUND
-- Performing Test USABLE_READLINE_FOUND - Success
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Found mhd: /usr/include
-- Configuring incomplete, errors occurred!
See also "/root/liteclient-build2/CMakeFiles/CMakeOutput.log".
See also "/root/liteclient-build2/CMakeFiles/CMakeError.log".
root@node01:~/liteclient-build2#`

**Comment by ton-blockchain** [comment]
Did you run `git submodule update` to fetch the source of all third-party libraries used by the software?

**Comment by Eninspace** [comment]
Try this, https://github.com/ton-blockchain/ton/issues/16#issuecomment-531727088

**Comment by EmelyanenkoK** [comment]
Please check [workflows](https://github.com/ton-blockchain/ton/tree/master/.github/workflows) as compilation guide.
