### ISSUE TITLE
opennSSL recommendation

### ISSUE THREAD

**Issue by KStasi** [ton-blockchain/ton#189]
It is recommended to use OpenSSL version 1.1.1  or letter:
https://github.com/ton-blockchain/ton/blob/7f3a22a217c0998d9cadca972d2be6aa327711a1/lite-client-docs/README#L18
But then linker command for test-ton-collator fails with:

> [ 72%] Linking CXX executable test-ton-collator
> Undefined symbols for architecture x86_64:
>   "_EVP_MD_CTX_destroy", referenced from:
>       digest::HashCtx<digest::OpensslEVP_SHA256>::clear() in libton_crypto.a(bitstring.cpp.o)
>       digest::HashCtx<digest::OpensslEVP_SHA512>::clear() in libton_block.a(mc-config.cpp.o)
>   "_EVP_MD_CTX_create", referenced from:
>       digest::HashCtx<digest::OpensslEVP_SHA256>::init() in libton_crypto.a(bitstring.cpp.o)
>       digest::HashCtx<digest::OpensslEVP_SHA512>::init() in libton_block.a(mc-config.cpp.o)
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [test-ton-collator] Error 1
> make[1]: *** [CMakeFiles/test-ton-collator.dir/all] Error 2
> make: *** [all] Error 2
> 

I found it can be caused by changes between openssl1.0 and openssl1.1 (https://www.openssl.org/news/cl110.txt):

> 
>      Additional changes:
>      1) EVP_MD_CTX_cleanup(), EVP_CIPHER_CTX_cleanup() and
>         HMAC_CTX_cleanup() were removed.  HMAC_CTX_reset() and
>         EVP_MD_CTX_reset() should be called instead to reinitialise
>         an already created structure.
>      2) For consistency with the majority of our object creators and
>         destructors, EVP_MD_CTX_(create|destroy) were renamed to
>         EVP_MD_CTX_(new|free).  The old names are retained as macros
>         for deprecated builds.
>      [Richard Levitte]

**Comment by ton-blockchain** [comment]
It is very strange that you obtained linker errors, but no compiler errors. Are you sure you are using OpenSSL headers corresponding to the same version of OpenSSL as the libraries installed?
