### ISSUE TITLE
can't setup on windows: error with gperf

### ISSUE THREAD

**Issue by davidkhl** [ton-blockchain/ton#19]
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.10586.
CMake Warning (dev) at CMakeLists.txt:26 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

Add abseil-cpp
-- No CMAKE_CXX_STANDARD set, assuming 11
Add wingetopt
-- Use wingetopt
Add crc32c
Add rocksdb
CMake Error at third-party/rocksdb/cmake/modules/ReadVersion.cmake:4 (file):
  file failed to open for reading (No such file or directory):

    D:/workinprogress/lite-client/include/rocksdb/version.h
Call Stack (most recent call first):
  third-party/rocksdb/CMakeLists.txt:39 (get_rocksdb_version)

CMake Warning at third-party/rocksdb/CMakeLists.txt:40 (project):
  VERSION keyword not followed by a value or was followed by a value that
  expanded to nothing.

-- GFLAGS library is disabled
-- SNAPPY library is disabled
-- LZ4 library is disabled
-- ZLIB library is disabled
-- XPRESS is disabled
-- ZSTD library is disabled
-- JEMALLOC library is disabled
-- Enabling RTTI in Debug builds only (default)
-- JNI library is disabled
Add ton
-- Could NOT find ccache
-- Could NOT find LATEX (missing: LATEX_COMPILER)
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
CMake Error at tdutils/generate/CMakeLists.txt:22 (message):
  Could NOT find gperf.  Add path to gperf executable to PATH environment
  variable or specify it manually using GPERF_EXECUTABLE option, i.  e.
  'cmake -DGPERF_EXECUTABLE:FILEPATH="<path to gperf executable>"'.

-- Configuring incomplete, errors occurred!
See also "D:/workinprogress/liteclient-build/CMakeFiles/CMakeOutput.log".
See also "D:/workinprogress/liteclient-build/CMakeFiles/CMakeError.log".

**Comment by ben-curv** [comment]
There's a WIP PR with Windows build instructions, including how to install gperf - https://github.com/ton-blockchain/ton/pull/10/files

**Comment by davidkhl** [comment]
doesn't work

**Comment by davidkhl** [comment]
./lite-client/lite-client -C ton-lite-client-test1.config.json is not a comand in fact

**Comment by ton-blockchain** [comment]
Should not be a problem anymore. 
The current version does not require gperf.

**Comment by Thirawat11** [comment]
G
