### ISSUE TITLE
validator rewards calculations

### ISSUE THREAD

**Issue by akme** [ton-blockchain/ton#190]
How can I get information about the amount of work that a validator made during a round?
What is this prices for? 
```
// lump_price bit_price cell_price ihr_factor first_frac next_frac
1000000 1000 sg* 100000 sg* 3/2 sg*/ 1/3 sg*/ 1/3 sg*/ config.fwd_prices!
10000000 10000 sg* 1000000 sg* 3/2 sg*/ 1/3 sg*/ 1/3 sg*/ config.mc_fwd_prices!
```
What is the bit? Is it minimal unit of work that validator can do and get reward for?

**Comment by ton-blockchain** [comment]
No, these are the message forwarding prices. They will be documented in an appendix to the TON Blockchain description.

**Comment by akme** [comment]
Got it, thanks!
But, what about checking validators work per round? how can we get this information?

**Comment by ton-blockchain** [comment]
Well, it is stored as a part of the masterchain state and described in crypto/block/block.tlb lines ~500-520:

```
counters#_ last_updated:uint32 total:uint64 cnt2048:uint64 cnt65536:uint64 = Counters; 
creator_info#4 mc_blocks:Counters shard_blocks:Counters = CreatorStats; 
block_create_stats#17 counters:(HashmapE 256 CreatorStats) = BlockCreateStats;

masterchain_state_extra#cc26
  shard_hashes:ShardHashes
  config:ConfigParams
  ^[ flags:(## 16) { flags <= 1 }
     ...
     block_create_stats:(flags . 0)?BlockCreateStats ]
  ...
= McStateExtra;
```

If you have a full node, you can attempt to extract this information from the masterchain state. We are currently in the process of adding a suitable query to the LiteServer, so in a few days there will be an option to obtain this information from the LiteClient.

**Comment by akme** [comment]
Thanks, will wait!

**Comment by ton-blockchain** [comment]
New commands `creatorstats` and `recentcreatorstats` have been added to the Lite Client. They can be used to inspect the participation of validators in creating new masterchain / shardchain blocks.

**Comment by akme** [comment]
> New commands `creatorstats` and `recentcreatorstats` have been added to the Lite Client. They can be used to inspect the participation of validators in creating new masterchain / shardchain blocks.

Great! Thanks, could you please give a bit of description about this data?
```
> creatorstats (-1,8000000000000000,349300)
0000000000000000000000000000000000000000000000000000000000000000 mc_cnt:(counter last_updated:1574959208 total:349300 cnt2048: 592.007 cnt65536: 19214.6) shard_cnt:(counter last_updated:1574959208 total:1760851 cnt2048: 3253.36 cnt65536: 104413)
00228468C797D44CAFE3D42EE54D38C54DA1465CB7EB0E00835B92EB2A30E679 mc_cnt:(counter last_updated:1574242916 total:521 cnt2048: 16.9609 cnt65536: 329.79) shard_cnt:(counter last_updated:1574242933 total:3188 cnt2048: 122.611 cnt65536: 2072.45)
0068CBA6608FDD45DD63F10CE762068873CC3AEA64635852270A3F48121276BB mc_cnt:(counter last_updated:1574898178 total:522 cnt2048: 16.6474 cnt65536: 330.109) shard_cnt:(counter last_updated:1574898290 total:2961 cnt2048: 98.0284 cnt65536: 1910.83)
00F865681D4208154973BDA45879E5ECA15607FDD209EFBA93A0FCDB25A7A53B mc_cnt:(counter last_updated:1574242896 total:629 cnt2048: 19.407 cnt65536: 393.048) shard_cnt:(counter last_updated:1574242930 total:3571 cnt2048: 100.428 cnt65536: 2270.16)
00F984D4A6FDA2ADAEC22F9459ADB9E689E631E546BC16E093599E7D392CFEC9 mc_cnt:(counter last_updated:1574373945 total:526 cnt2048: 16.8731 cnt65536: 332.821) shard_cnt:(counter last_updated:1574373749 total:3346 cnt2048: 122.27 cnt65536: 2151.13)
012774BE28DCBC63F362E8D94605C71AD5B402B64548BBB5BB9F0B5C2A4DBC94 mc_cnt:(counter last_updated:1574177383 total:1642 cnt2048: 41.9373 cnt65536: 938.541) shard_cnt:(counter last_updated:1574177400 total:7507 cnt2048: 181.576 cnt65536: 4255.95)
…
```

**Comment by ton-blockchain** [comment]
`mc_cnt` = counters for masterchain blocks
`shard_cnt` = counters for shardchain blocks
`last_updated` = Unixtime of last counter update (i.e. of last generated block)
`total` = total blocks created
`cnt2048` = approximate number of blocks created during last 2048 seconds (before `last_updated`)
`cnt65536` = same for last 65536 seconds

**Comment by akme** [comment]
Thanks, I appreciate your help!
