### ISSUE TITLE
root_hash and file_hash for zero-state in ton-global.config

### ISSUE THREAD

**Issue by akme** [ton-blockchain/ton#192]
After running create-state gen-zerostate.fif I obtained root_hash and file_hash for zero_state, but when I put them into ton-global.config, I get an error:
```
[Error : 0 : json does not fit TL scheme:  Wrong character in the string]
```
If I put hashes from testnet there - no error occurs.
What hashes should I put in the config to fix this error?

**Comment by ton-blockchain** [comment]
Well, probably a string contains a wrong character. Did you put Base64, Base64url or Hex hashes there?

**Comment by akme** [comment]
I've put what was generated by create-state:
```
file hash= BFF2BA3CD0954F318C22C7F2736830528C2B9D26AFF6E74C8AD8B9B2BE3A9D0A  v_K6PNCVTzGMIsfyc2gwUowrnSav9udMiti5sr46nQo=
root hash= 36C742086E69B78AE76198BD02DF83AC1D5B806801605858574AB6FF0AEDE225  NsdCCG5pt4rnYZi9At-DrB1bgGgBYFhYV0q2_wrt4iU=
Basestate0 root hash= B973E1E2D22D1A5529174E9243525975503DBC936CB2C3A923592DA037EC0E19  uXPh4tItGlUpF06SQ1JZdVA9vJNsssOpI1ktoDfsDhk=
Basestate0 file hash= E586ED965F3AE0CBC116D636AED12A2015A696B0A30412EE1EF8214BFD65CE32  5Ybtll864MvBFtY2rtEqIBWmlrCjBBLuHvghS_1lzjI=
Zerostate root hash= 36C742086E69B78AE76198BD02DF83AC1D5B806801605858574AB6FF0AEDE225  NsdCCG5pt4rnYZi9At-DrB1bgGgBYFhYV0q2_wrt4iU=
Zerostate file hash= BFF2BA3CD0954F318C22C7F2736830528C2B9D26AFF6E74C8AD8B9B2BE3A9D0A  v_K6PNCVTzGMIsfyc2gwUowrnSav9udMiti5sr46nQo=
```
base64
root hash= NsdCCG5pt4rnYZi9At-DrB1bgGgBYFhYV0q2_wrt4iU=
file hash= v_K6PNCVTzGMIsfyc2gwUowrnSav9udMiti5sr46nQo=

**Comment by akme** [comment]
Ok, got it, create-state generates base64url, but ton-global.config needs just base64
