### ISSUE TITLE
Blockchain explorer doesn't work

### ISSUE THREAD

**Issue by akme** [ton-blockchain/ton#196]
https://test.ton.org/testnet/ doesn't work
![image](https://user-images.githubusercontent.com/1006307/69525551-66e58a00-0f79-11ea-88c6-5225d20bef5b.png)
![image](https://user-images.githubusercontent.com/1006307/69525568-6fd65b80-0f79-11ea-9697-0ba31019fa5a.png)

**Comment by ton-blockchain** [comment]
The full node used by the public blockchain explorer went out of sync after a software upgrade. Now everything should be in order.
