### ISSUE TITLE
test-ton-collator crashes

### ISSUE THREAD

**Issue by sorokinvld** [ton-blockchain/ton#201]
1st and 2nd run of `test-ton-collator` crash returning:
`~/ton/build# ./test-ton-collator -D /var/ton-work/db/ -z crypto/zerostate.boc -v5`

`...
[ 0][t 5][1575215006.838424444][apply-block.cpp:257][!apply [ w=-1 s=9223372036854775808 seq=1 WwQniCEukxTU4f3HBR9ZGNGb/00kITpY1MOCe0e0qVQ= 5w/Zu7n88h6y4XXiels1D0lLPo6lj5XK7kiRKl95xos= ]]	Check `handle_->handle_moved_to_archive()` failed
...`

third run:

`...
[ 0][t 4][1575215104.861180544][block-handle.hpp:336][!manager][&next_[0] == next]	id=[ w=-1 s=9223372036854775808 seq=1 WwQniCEukxTU4f3HBR9ZGNGb/00kITpY1MOCe0e0qVQ= 5w/Zu7n88h6y4XXiels1D0lLPo6lj5XK7kiRKl95xos= ] next=[ w=-1 s=9223372036854775808 seq=2 3hOk/LvzPy7+GcggzCBXQb0wnO6YstBIc+Zw/7nAjOI= MN6axQTcr4jnC6SOdBGzF6MNuS7Uommb4iMlIwAef+E= ] to_be_next=[ w=-1 s=9223372036854775808 seq=2 uAh4LDMoRCgz+TRcl2sreAh9i6ijxa0GBCDyfYehH20= nIn/dQ5Mc0RcQ4trT/0ZMpCNLYa8NEX+BLVE99DspnM= ]
[pid 29689] [time 1575215104] Signal: 6
...
`

what am I doing wrong? before test-ton-collator run I generated zerotate/basestate (generated correctly), moved them to db/static and so on.

**Comment by hortonelectric** [comment]
track down and comment out the checks and it will work. Dirty but it will get you there. apply-block.cpp where it checks handle_moved_to_archive and moved_to_archive.

https://github.com/ton-blockchain/ton/issues/195#issuecomment-559107083

**Comment by EmelyanenkoK** [comment]
Some guide can be found here https://github.com/ton-blockchain/TIPs/issues/2
