### ISSUE TITLE
malicious validator can steal funds from any contract that receives an external message?

### ISSUE THREAD

**Issue by vikstrous** [ton-blockchain/ton#203]
I'm posting this directly to the issue tracker because TON is not live yet and so there's no threat to anyone's funds right now. I hope that I'm wrong about my conclusion, so let me know where I've made a mistake.

As a part of implementing the signing of a message to the simple contract for withdrawing funds, I noticed that import fees are not signed. That means that any malicious validator can choose to include a modified version of an external message in the blockchain and send itself more funds than intended by the author of the message.

The structure of a message that sends funds from the simple contract is the following:
```
message$_ {X:Type} info:CommonMsgInfo
  init:(Maybe (Either StateInit ^StateInit))
  body:(Either X ^X) = Message X;

ext_in_msg_info$10 src:MsgAddressExt dest:MsgAddressInt 
  import_fee:Grams = CommonMsgInfo;
```

The signed part of the message is the part inside `body` and consists of the following data directly in the current cells:
```
signature || seqno || mode
```
And in a child cell:
```
message$_ {X:Type} info:CommonMsgInfoRelaxed
  init:(Maybe (Either StateInit ^StateInit))
  body:(Either X ^X) = MessageRelaxed X;

int_msg_info$0 ihr_disabled:Bool bounce:Bool bounced:Bool
  src:MsgAddress dest:MsgAddressInt 
  value:CurrencyCollection ihr_fee:Grams fwd_fee:Grams
  created_lt:uint64 created_at:uint32 = CommonMsgInfoRelaxed;
```

The signature is over `seqno || mode` and the child cell, but it doesn't cover `import_fee` which is outside in the external message wrapper.

Attack example:
* Alice has 1000 grams in her address (1 kg?)
* Alice signs a message to send 10 grams to Bob
* Alice wraps the signed message in an external message with `import_fee` of 0
* Alice sends the external message to Mallory because Mallory is running a full node or validator and wants her to include the message in the blockchain
* Mallory unwraps the unsigned parts of Alice's message, takes the signed portion and the signature and constructs her own external message with `import_fee` of 990 grams
* Mallory includes the external message in the next block she validates or passes it on to an other validator to include it in the blockchain.

Either Mallory directly benefits from rewarding herself the fees from the message or the fees get distributed to some other validator. I haven't read enough about exactly how fees get distributed. Either way, Alice loses 990 grams.

Is there a way to defend against this attack? Can the simple contract enforce an upper limit on the fees it's willing to accept? Can it require the external message to contain a signed copy of the import fees amount?

**Comment by EmelyanenkoK** [comment]
As I understand for external messages import_fees are always considered to be equal to zero:
https://github.com/ton-blockchain/ton/blob/e30d98eb30d35b6808d2511c93631a72e5882514/crypto/block/block-parse.cpp#L1699-L1702
Actual value encoded into external message is always skipped:
https://github.com/ton-blockchain/ton/blob/e30d98eb30d35b6808d2511c93631a72e5882514/crypto/block/block-parse.cpp#L636
https://github.com/ton-blockchain/ton/blob/e30d98eb30d35b6808d2511c93631a72e5882514/crypto/block/block-parse.cpp#L667

**Comment by vikstrous** [comment]
In your first link, InMsg seems to be a message received by a shard from another shard, not an external message. That's why it has no "import fees", but in this context they are referring to fees "imported" into the new shard.

In your second link, all values are parsed with the `_skip` versions of methods. This is in the `validate_skip` method on `CommonMsgInfo`, so that makes sense. In the third link, it's also in the `skip` method of the parent object. It doesn't mean the field is not used. It's just a function implementation.

I think this indicates that import_fees are used:

https://github.com/ton-blockchain/ton/blob/090e0c16eb86184eaa3fda0e5d1c9838cf2ff88e/validator/impl/collator.cpp#L3551

The easiest way to test whether or not import fees actually do what I think they do is to set them on an external message and observe if they decrease the balance of the receiving account. Sorry for not doing that before posting.

**Comment by EmelyanenkoK** [comment]
Well, is it really a "big" problem? Unlike bitcoin where sender directly set fees, or ethereum where sender directly set gas_price in ton sender only (partially) control input_data but not total fees or gas price.
As I understand fees which will be collected by validators are calculated as follows:
0. there is consensus based `gas_price` for every workchain
1. each contract has some `gas_credit` to start execution
2. during external message processing contract should `ACCEPT` incoming message and effectively raise gas_limit to it's `balance/gas_price`
3. after finishing all execution phases, spent gas is summarised, multiplied by `gas_price` and result is subtracted from account balance
That way `fees` in external message are not used at all, if malicious party will change it nothing happens: nor consensus based `gas_price` will change, nor message based total used `gas`.
Still I agree that there should be no fields which may be changed by any transmitting party.

**Comment by vikstrous** [comment]
Ok, I proved myself wrong finally. It turns out that the import_fee field doesn't do anything. I thought that it's an additional fee to incentivize validators to include the transaction, but it's actually not. It's just another ignored field.

Here's the transaction that proves it:

https://test.ton.org/testnet/transaction?account=EQBqNxo9YMUiHZGHtzGDaS0ra1wDPEG32Ht-k4V2rpSAKApH&lt=688840000001&hash=05DFF97887606FE1553778941D03C9ACBE01C4EF1F3156DBAF4995E17C13E141

total_fees is only 4 mg even though import_fee is 1 gram. Also, the balance is still at 4.8 grams even though it started at 5 grams.

Closing this issue because the scenario I described is not possible.

**Comment by vikstrous** [comment]
I found out why I was confused about this. It was this quote from the original paper:

> “Messages from nowhere” can also define some transaction fee which is deducted from the receiver’s account on top of the gas
> payment for redistribution to the validators.

**Comment by ton-blockchain** [comment]
Originally, there was an idea to use this field to indicate extra fees to be paid if the message is included by the validator, but then this idea was dropped more or less for the reasons indicated above. Another option would be to pass the import_fee indicated in the ext_message as a stack parameter to recv_external(), so that the receiving smart contract would check whether this value matches a value stored in the signed part of the external message. Such a change is still possible; it has not been adopted because of the additional complications it would impose on all wallet smart contracts, and because of the security issues it would create for those smart contracts that do not check this value.
