### ISSUE TITLE
creatorstats total doesn't match with sum of others

### ISSUE THREAD

**Issue by akme** [ton-blockchain/ton#205]
Why the value of mc total counter doesn't match with the sum of all other records?
00..00 mc total counter shows around 565577, but sum of other records is only about 343450...

Btw, why there is always +1 validator in current validator set? For example, 33 validators participated in elections, but the validator set shows 34 validators...

**Comment by ton-blockchain** [comment]
1) Once a validator stops generating blocks, the `cnt65536` counters in its entry start to decay (dividing by approximately four each day; the precise value is exp(86400/65536)=3.71). When they become zero (as fixed-point values), the entry is discarded to avoid infinite growth of this data structure in the masterchain state. This would happen in 20-30 days after a validator stops creating new blocks. However, the total is not adjusted, so the `total` value of the value with key 0 is larger than the sum of `total` of all other entries. For `cnt65536` and `cnt2048` they should more or less match.

2) We see 33 members in the list at `getconfig 34`: [https://test.ton.org/testnet/config#configparam34](https://test.ton.org/testnet/config#configparam34)

**Comment by akme** [comment]
1. thanks, got it.
2. I recorded all participants from 1575815798 elections:
```
8716288637793229233203240156649685054923036342765753903032697732271323695034 20138000000000
8977411933987194904438735243856350536486769383686536975146311763946903516693 20138000000000
9195527252773072185940838983622764687012478485013193465256513296492096620687 20138000000000
12052150795683606255364234236841429947635155180024306858011539060941837637215 20138000000000
12738625117503330478211129885927334013961094084260447829091873606929183977945 20138000000000
13246105429045069988667043768063408597016660580872493989562319349090193579255 20138000000000
14816982076540518986957297649137427365475375128342694293333306929650066755212 20138000000000
15049165015730683359907873936505699235467025935046280484287578029107922790437 20138000000000
15832122677966537439285703771613922709922081698979984768062682663776014913801 20138000000000
19966491283511508709626851203542771774410584585805607480471739878248389293096 20138000000000
31707363381635310414593935202003207488439562798608456864091891423311506617901 20138000000000
48147373657219011284823985973507769162271953339514841715580468974424553779031 20138000000000
48857658043433289147082931031612854027623626125806374242771998871302266849654 20138000000000
52091015657655550507813489976945945077008757665515393092201225892047483156154 20138000000000
55701492877097554925609216386390638641721290315919775049473077040100988100073 20138000000000
56431255593335694006752491605993869467449201368901786939873088031391213940164 20138000000000
57841852256199376814641527374277181528998303616673327941243598167158284243745 30000000000000
60909793492718633885177947256794221789884428726928074350114740994417110250628 20138000000000
66499978779131743245338819834164731044058074616400002306233270908168603670400 22000000000000
72961253498746709626267052029175979444838764512280733012656159611903502021725 20138000000000
74788162192644903060919411928621288055458025938227278155309200701215782230475 20138000000000
75377857102497599724723716145047277366503152077169479067629138921680011513853 20138000000000
80413352979457241155691973732099009470870019653127092355534831739885852240559 18004200000000
80933501472793792212880872041896957864854393088662261484714814632654331776957 20138000000000
81407190332602134003189724134689096331122875070107979880758098605255624773362 20138000000000
83831907729315902415083104159484582052222365455667558198256396885187742732714 20138000000000
85409537340359356746398777453204713442895809806490969671620539661445212899325 20138000000000
85670698777816023349260275709230080148775433554159276311360101733852034929070 20138000000000
86499673143661898013803745293784280140660070816621863290687989442637885045626 20138000000000
88461254442682548377285249642684589856166391089703257741573841185101850168521 20138000000000
97842058612954976223839598078436207521686650120507828121482155500362886321995 20138000000000
105328831953210592744713524012386330642257868130403533143235917623298599840962 20138000000000
114083453697752727435858198199177395933790722910846465822701516678328666581587 20138000000000
```
here is 33 records, but `getconfig 34` says:
```
  cur_validators:(validators_ext utime_since:1575815798 utime_until:1575881334 total:34 main:34 total_weight:1152921504606846945
```
and this happens in each elections round, cur_validators always show +1 to participants number

P.S. maybe you have a bot that stakes in last second before elections closing and I just can't record it?

**Comment by ton-blockchain** [comment]
Well, it happens sometimes that there are insufficiently many validators or the total stake is still too small, but the election closing time is already overdue, and then the election is concluded as soon as a new stake arrives that makes the conditions satisfied.

However, this does not seem the case. Maybe there is indeed a bot like you suggest, but then it is not one of ours. We usually make the stakes as soon as the elections are announced.

It would be interesting to compare the public keys in the list of participants and in `getconfig 34`.

**Comment by ton-blockchain** [comment]
It seems that the missing participant was the very first one with key
2480485228457313508090715774961435223944581157723602963066562592600597566770 = 0x057BE7A6A92C42A384819AD5C86493E1DCF6C0E6C96458A66C700E4DFD899532

**Comment by akme** [comment]
Checked for 1575881334 and 165502EBF5217C911DE0C49AFD31F503AFB2C9CE7A86EEAB617648564054D631 was absent in participants list.
I check participants_list and save it each minute before the end of elections. Is it possible that participants_list method doesn't show all participants?

**Comment by ton-blockchain** [comment]
Only if DICTUGETPREV does not work correctly in some occasions. This would be very strange.
Is 165502EBF5217C911DE0C49AFD31F503AFB2C9CE7A86EEAB617648564054D631 also the smallest key?

**Comment by ton-blockchain** [comment]
Yes, it is. It looks like `participant_list` does not return the very first element (one with the smallest public key).

**Comment by akme** [comment]
Good that you confirmed, will you investigate it further?

**Comment by ton-blockchain** [comment]
Can you check that your script for obtaining the participant list does not omit the first line of the result while saving?
We tried to reproduce this effect by constructing a dictionary with the same keys and running a part of the code for `participant_list`. It worked correctly.

**Comment by akme** [comment]
I'll check once the elections will be active.

**Comment by akme** [comment]
Yes, it's my bad, sorry, missed some characters after the format of the participant_list changed.
