### ISSUE TITLE
No random number generator in TVM

### ISSUE THREAD

**Issue by gr8den** [ton-blockchain/ton#209]
As described in documentation (https://test.ton.org/tvm.pdf A.11.3) opcodes for random number generator are reserved but not implemented

**Comment by Kyborg2011** [comment]
Understand! Thank you for this reply. Then I will build another smart-contract right now...

**Comment by ton-blockchain** [comment]
A simple PRNG has been introduced in commit d41ce55305718d207867f0dac60319ec4b6846f2. The documentation is in section A.11.3 of [tvm.pdf](https://test.ton.org/tvm.pdf).
