### ISSUE TITLE
validator reward lower than staked

### ISSUE THREAD

**Issue by akme** [ton-blockchain/ton#214]
After one round I got validators reward lower than I staked, I thought it's because of not up to date engine deployed, then I updated it with the latest commit, but again got my reward pretty low.
There are a lot of errors in logs like this:
```
[ 1][t 6][1576196633.014778614][validate-query.cpp:116][!validateblock(0,2000000000000000):921252]	aborting validation of block candidate for (0,2000000000000000) : [Error : -666 : reference masterchain block (-1,8000000000000000,705384):39460F2ADBDBD0A68820DA9848D7D8812D53D42A4AD2B63F2EA3C2DCC227CB7A:EDFD5329E96B04FECC93E8D8D8A7E03C9ECA6389A63DC5E8AF0224C51016E52C for block (0,2000000000000000,921252):8D540A03B550365BA0F5F5E91879E0AB8FA93D3ADDF5DDD88E096C435DB519E0:B8AA3C8F9FED0C002BEC13435B8CABBF6D4CA5CA295AB06FA0FA16E8A2116452 does not have a valid proof]
[ 1][t 6][1576196633.014800072][validator-group.cpp:51][!validateblock(0,2000000000000000):921252]	failed to validate candidate: [Error : -666 : reference masterchain block (-1,8000000000000000,705384):39460F2ADBDBD0A68820DA9848D7D8812D53D42A4AD2B63F2EA3C2DCC227CB7A:EDFD5329E96B04FECC93E8D8D8A7E03C9ECA6389A63DC5E8AF0224C51016E52C for block (0,2000000000000000,921252):8D540A03B550365BA0F5F5E91879E0AB8FA93D3ADDF5DDD88E096C435DB519E0:B8AA3C8F9FED0C002BEC13435B8CABBF6D4CA5CA295AB06FA0FA16E8A2116452 does not have a valid proof]
[ 1][t 6][1576196633.014924526][validate-query.cpp:116][!validateblock(0,2000000000000000):921252]	aborting validation of block candidate for (0,2000000000000000) : [Error : -666 : reference masterchain block (-1,8000000000000000,705384):39460F2ADBDBD0A68820DA9848D7D8812D53D42A4AD2B63F2EA3C2DCC227CB7A:EDFD5329E96B04FECC93E8D8D8A7E03C9ECA6389A63DC5E8AF0224C51016E52C for block (0,2000000000000000,921252):8D540A03B550365BA0F5F5E91879E0AB8FA93D3ADDF5DDD88E096C435DB519E0:B8AA3C8F9FED0C002BEC13435B8CABBF6D4CA5CA295AB06FA0FA16E8A2116452 does not have a valid proof]
[ 1][t 6][1576196633.014943123][validator-group.cpp:51][!validateblock(0,2000000000000000):921252]	failed to validate candidate: [Error : -666 : reference masterchain block (-1,8000000000000000,705384):39460F2ADBDBD0A68820DA9848D7D8812D53D42A4AD2B63F2EA3C2DCC227CB7A:EDFD5329E96B04FECC93E8D8D8A7E03C9ECA6389A63DC5E8AF0224C51016E52C for block (0,2000000000000000,921252):8D540A03B550365BA0F5F5E91879E0AB8FA93D3ADDF5DDD88E096C435DB519E0:B8AA3C8F9FED0C002BEC13435B8CABBF6D4CA5CA295AB06FA0FA16E8A2116452 does not have a valid proof]
[ 1][t 5][1576196633.015036821][validate-query.cpp:116][!validateblock(0,2000000000000000):921252]	aborting validation of block candidate for (0,2000000000000000) : [Error : -666 : reference masterchain block (-1,8000000000000000,705384):39460F2ADBDBD0A68820DA9848D7D8812D53D42A4AD2B63F2EA3C2DCC227CB7A:EDFD5329E96B04FECC93E8D8D8A7E03C9ECA6389A63DC5E8AF0224C51016E52C for block (0,2000000000000000,921252):8D540A03B550365BA0F5F5E91879E0AB8FA93D3ADDF5DDD88E096C435DB519E0:B8AA3C8F9FED0C002BEC13435B8CABBF6D4CA5CA295AB06FA0FA16E8A2116452 does not have a valid proof]
[ 1][t 5][1576196633.015058994][validator-group.cpp:51][!validateblock(0,2000000000000000):921252]	failed to validate candidate: [Error : -666 : reference masterchain block (-1,8000000000000000,705384):39460F2ADBDBD0A68820DA9848D7D8812D53D42A4AD2B63F2EA3C2DCC227CB7A:EDFD5329E96B04FECC93E8D8D8A7E03C9ECA6389A63DC5E8AF0224C51016E52C for block (0,2000000000000000,921252):8D540A03B550365BA0F5F5E91879E0AB8FA93D3ADDF5DDD88E096C435DB519E0:B8AA3C8F9FED0C002BEC13435B8CABBF6D4CA5CA295AB06FA0FA16E8A2116452 does not have a valid proof]
```
Is everything ok with validation process or there is a problem after last updates?

**Comment by ton-blockchain** [comment]
Do you want to say that you recovered less test grams than you staked? If so, can you tell your masterchain account address that you used for staking and approximate time, so that we can investigate?

As to the errors - did they appear only during the initial synchronization phase, or later as well?

**Comment by akme** [comment]
> Do you want to say that you recovered less test grams than you staked? If so, can you tell your masterchain account address that you used for staking and approximate time, so that we can investigate?


Yes, account used: kf-8s6QrxANt90N-zZpTBd51SZLSV_g3fDhMnmFVcFwR75O3
Stake: https://test.ton.org/testnet/transaction?account=kf-8s6QrxANt90N-zZpTBd51SZLSV_g3fDhMnmFVcFwR75O3&lt=1015640000001&hash=5C35503A2F53E68069833AFD1903F4FA1C4B06C3800E115F81E19DFE0F7D1E1B
Recover: https://test.ton.org/testnet/transaction?account=kf-8s6QrxANt90N-zZpTBd51SZLSV_g3fDhMnmFVcFwR75O3&lt=1077063000005&hash=832F30E0114F90C0520C684D333422A835A21B71A1584E3A334914A93496EFC5
```
'runmethod -1:3333333333333333333333333333333333333333333333333333333333333333 compute_returned_stake 0xbcb3a42bc4036df7437ecd9a5305de754992d257f8377c384c9e6155705c11ef'
using liteserver 0 with addr [67.207.74.182:4924]
zerostate set to -1:17A3A92992AABEA785A7A090985A265CD31F323D849DA51239737E321FB05569:5E994FCF4D425C0A6CE6A792594B7173205F740A39CD56F537DEFD28B48A0F6E
latest masterchain block known to server is (-1,8000000000000000,754427):71BBFFC7433155B94A8C96657B36826A4B0594451554D48C18BDE063D58C3CE9:95A71274853890BBAD0CEFB979A1980DA093D41130D154859E7810419D0793F5 created at 1576373285 (5 seconds ago)
BLK#1 = (-1,8000000000000000,754427):71BBFFC7433155B94A8C96657B36826A4B0594451554D48C18BDE063D58C3CE9:95A71274853890BBAD0CEFB979A1980DA093D41130D154859E7810419D0793F5
BLK#2 = (-1,8000000000000000,0):17A3A92992AABEA785A7A090985A265CD31F323D849DA51239737E321FB05569:5E994FCF4D425C0A6CE6A792594B7173205F740A39CD56F537DEFD28B48A0F6E
arguments:  [ 85352214224570612152920135754148667434497558849190997494220203594075032261103 130944 ]
result:  [ 29065585476165 ]
```
> As to the errors - did they appear only during the initial synchronization phase, or later as well?


Errors appeared during validation round, full node was synced and active in current validators set

**Comment by akme** [comment]
Possibly, I was wrong with the stake link and this one should be correct https://test.ton.org/testnet/transaction?account=kf-8s6QrxANt90N-zZpTBd51SZLSV_g3fDhMnmFVcFwR75O3&lt=994203000001&hash=9E15E990FFF1AFAF2D4816A6AF28E13103F9E454B9DB080D4E86577F3C724437
Anyway reward was also less then stake

**Comment by ton-blockchain** [comment]
How often do you try to recover the reward?
The amount that you recover (approximately 29066 test Grams) is something like 2.7*minimal stake (which is slightly more than 10000 test Grams) plus some reward. If you use max_factor=2.7 (which is the value used in documentation), this would explain this effect (your actual stake is slightly more than 27000 test Grams).

Note that if your actual stake turns out to be less than the amount that you originally tried to stake, then the remainder is credited to you immediately after the elections are successfully conducted. A reward recover transaction could have transferred this amount at any point after the election (long time before the actual stake would be unfrozen).

**Comment by akme** [comment]
I recover once elections are open and stake unfrozen, currently, I skipped one election and found out exactly that behavior that you described, but because of a continuous process, returned part of the exceeded stake summed up with the reward and I just didn't notice this...
Sorry for bothering you
Thanks for the help!
