### ISSUE TITLE
TON crashes in docker container

### ISSUE THREAD

**Issue by hortonelectric** [ton-blockchain/ton#237]
It runs for a minute, and then after 'certificate update', it gives this.

ton    | [ 3][t 4][1580551121.257527590][validator-session-description.hpp:113][!session]	reused 1 times
ton    | [ 3][t 2][1580551121.257547617][validator-session-description.hpp:113][!session]	reused 1 times
ton    | [ 3][t 4][1580551121.266988277][collator.cpp:492][!collate(-1,8000000000000000):1]	after_get_shard_blocks: got 0 ShardTopBlockDescriptions
ton    | [ 3][t 5][1580551121.267346859][collator.cpp:1105][!collate(-1,8000000000000000):1]	unpacking most recent masterchain state
ton    | [ 4][t 0][1580551121.268046618][mc-config.cpp:141]	requested accounts dictionary
ton    | [pid 1] [time 1580551121] Signal: 6
ton    | ------- Stack Backtrace -------
ton    | validator-engine(+0x22b60e)[0x555848e9660e]
ton    | validator-engine(+0x2293d4)[0x555848e943d4]
ton    | /lib/x86_64-linux-gnu/libpthread.so.0(+0x15540)[0x7f5a4ab63540]
ton    | /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7f5a4a64a3eb]
ton    | /lib/x86_64-linux-gnu/libc.so.6(abort+0x12b)[0x7f5a4a629899]
ton    | validator-engine(_ZNSt10unique_ptrIcN2td14StackAllocator7DeleterEED1Ev+0x28)[0x555848e2f272]
ton    | /var/ton/build/crypto/libton_block.so(+0x234e2c)[0x7f5a4b0a0e2c]
ton    | /var/ton/build/crypto/libton_block.so(_ZN5block10ConfigInfo6unpackEv+0x316)[0x7f5a4afc3d0e]
ton    | /var/ton/build/crypto/libton_block.so(_ZN5block10ConfigInfo14unpack_wrappedEv+0x2f)[0x7f5a4afc464d]
ton    | /var/ton/build/crypto/libton_block.so(_ZN5block10ConfigInfo14extract_configEN2td3RefIN2vm4CellEEEi+0xa8)[0x7f5a4afc48a2]
ton    | validator-engine(+0x488bd7)[0x5558490f3bd7]
ton    | validator-engine(+0x493e1d)[0x5558490fee1d]
ton    | validator-engine(+0x4a5746)[0x555849110746]
ton    | validator-engine(+0x4a61bc)[0x5558491111bc]
ton    | validator-engine(+0x4a7169)[0x555849112169]
ton    | validator-engine(+0x48bc1f)[0x5558490f6c1f]
ton    | validator-engine(+0x23d00f)[0x555848ea800f]
ton    | validator-engine(+0x23d163)[0x555848ea8163]
ton    | validator-engine(+0x240a8a)[0x555848eaba8a]
ton    | validator-engine(+0x23d6b7)[0x555848ea86b7]
ton    | validator-engine(+0x23d71f)[0x555848ea871f]
ton    | validator-engine(_ZN2td6detail13ThreadPthread10run_threadEPv+0x3d)[0x555848e2deb0]
ton    | /lib/x86_64-linux-gnu/libpthread.so.0(+0x9669)[0x7f5a4ab57669]
ton    | /lib/x86_64-linux-gnu/libc.so.6(clone+0x43)[0x7f5a4a726323]
ton    | -------------------------------
ton    | ------- Stack Backtrace -------
ton    | validator-engine(+0x22b60e)[0x555848e9660e]
ton    | validator-engine(+0x2293d4)[0x555848e943d4]
ton    | /lib/x86_64-linux-gnu/libpthread.so.0(+0x15540)[0x7f5a4ab63540]
ton    | /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7f5a4a64a3eb]
ton    | /lib/x86_64-linux-gnu/libc.so.6(abort+0x12b)[0x7f5a4a629899]
ton    | validator-engine(_ZNSt10unique_ptrIcN2td14StackAllocator7DeleterEED1Ev+0x28)[0x555848e2f272]
ton    | /var/ton/build/crypto/libton_block.so(+0x234e2c)[0x7f5a4b0a0e2c]
ton    | /var/ton/build/crypto/libton_block.so(_ZN5block10ConfigInfo6unpackEv+0x316)[0x7f5a4afc3d0e]
ton    | /var/ton/build/crypto/libton_block.so(_ZN5block10ConfigInfo14unpack_wrappedEv+0x2f)[0x7f5a4afc464d]
ton    | /var/ton/build/crypto/libton_block.so(_ZN5block10ConfigInfo14extract_configEN2td3RefIN2vm4CellEEEi+0xa8)[0x7f5a4afc48a2]
ton    | validator-engine(+0x488bd7)[0x5558490f3bd7]
ton    | validator-engine(+0x493e1d)[0x5558490fee1d]
ton    | validator-engine(+0x4a5746)[0x555849110746]
ton    | validator-engine(+0x4a61bc)[0x5558491111bc]
ton    | validator-engine(+0x4a7169)[0x555849112169]
ton    | validator-engine(+0x48bc1f)[0x5558490f6c1f]
ton    | validator-engine(+0x23d00f)[0x555848ea800f]
ton    | validator-engine(+0x23d163)[0x555848ea8163]
ton    | validator-engine(+0x240a8a)[0x555848eaba8a]
ton    | validator-engine(+0x23d6b7)[0x555848ea86b7]
ton    | validator-engine(+0x23d71f)[0x555848ea871f]
ton    | validator-engine(_ZN2td6detail13ThreadPthread10run_threadEPv+0x3d)[0x555848e2deb0]
ton    | /lib/x86_64-linux-gnu/libpthread.so.0(+0x9669)[0x7f5a4ab57669]
ton    | /lib/x86_64-linux-gnu/libc.so.6(clone+0x43)[0x7f5a4a726323]
ton    | -------------------------------
ton exited with code 1

**Comment by EmelyanenkoK** [comment]
You can check [docker yml](https://github.com/ton-blockchain/ton/blob/master/.github/workflows/docker-ubuntu-image.yml) as example.
