### ISSUE TITLE
Add verbosity setting for tonlibjson config

### ISSUE THREAD

**Issue by akme** [ton-blockchain/ton#238]
As I see, there is only one way to change the verbosity level for tonlibjson by calling SetLogVerbosityLevel after client creation, so we can't turn off output completely. 
It would very useful if we could set this setting in the config, so we can get more control over the output from the start. 
For tonlib-cli we can set it from the arguments, by providing -v0 flag, but I don't see any available option for tonlibjson.

**Comment by ton-blockchain** [comment]
You may call sendVerbosityLevel before client creation by calling a static function `Client::execute`.
Or `ClientJson::execute`.

**Comment by akme** [comment]
It's possible to do in C++, but can't figure out how to do it via FFI from tonlib-go...

**Comment by ton-blockchain** [comment]
It looks more like tonlib-go issue. The needed interface is exposed via 
`TONLIBJSON_EXPORT const char *tonlib_client_json_execute(void *client, const char *request);`

**Comment by akme** [comment]
Ok, got it, we made it like [this](https://github.com/mercuryoio/tonlib-go/blob/762187f212213ceaf5b2058c84b7cdf7b1c103d0/client.go#L70), but still getting some output:
```
[ 4][t 0][1581683244.115713120][TonlibClient.cpp:1196][&tonlib_query]	Tonlib got static query setLogVerbosityLevel {
  new_verbosity_level = 0
}
```
Could you give advice on how to deal with this?

**Comment by EmelyanenkoK** [comment]
Fixed in https://github.com/ton-blockchain/ton/commit/09236fba0940335295570faea0ace41ce135124c
