### ISSUE TITLE
Elector smart-contract should not accept ordinary transfers

### ISSUE THREAD

**Issue by AleksejMelman** [ton-blockchain/ton#248]
According to the documentation https://test.ton.org/Validator-HOWTO.txt one should generate and 
 send validator-query.boc file to elector smart-contract in order to participate in elections.

>fift -s wallet.fif my_wallet_id -1:A4C2C7C05B093D470DE2316DBA089FA0DD775FD9B1EBFC9DC9D04B498D3A2DDA 1 100001. -B validator-query.boc 
>sendfile wallet-query.boc

If user by accident instead of proper validator-query.boc sends a simple message with body, let's say <b 0 32 u, "GIFT" $, b>, then elector smart-contract processes this transfer and accepts grams:

https://github.com/ton-blockchain/ton/blob/1de39f5d7cc1655ae691462370dffec26cd9bc77/crypto/smartcont/elector-code.fc#L365

Since normally potential participants send huge amount of grams to elector-smart contract the cost of mistake is very high. There is no reason for potential participant to simply send his grams to elector smart-contract without any chance to get these grams back later on. 

I encourage elector smart-contract to accept only relevant messages and reject simple transfers.
I recognize that elector smart-contract still might have a reason to accept simple transfers, but this should be somehow protected against accidental transfers.

**Comment by ton-blockchain** [comment]
Well, you may have a point here. The current behavior is correct, but a bit cruel. We could make a special "GIFT" internal message for "donating" grams to the elector smart contract (i.e., to the validator community), and return large sums if transferred via a simple transfer.

Did you lose a lot of grams because of this mistake?

**Comment by AleksejMelman** [comment]
Cruel - is a very pricise word for this scenario. Yes, at the very last step my send-script took the wrong boc file and sent 10k grams as a gift. The first thought was - no problem, it's a mistake and grams come back, but they never came. 
To construct a wrong boc in order to become validator is easy, because many steps are involved and  this wrong boc will be easily rejected, but within this process a chance to send a simple GIFT boc with a huge amount of grams by mistake is much bigger. 
If that would happen with real money, the one would be in a very unfortuante position in front of his investors.  In my case I just lost an oppotunity to become validator and analyze how it works.
Here is a proof link for this transaction:
https://gramscan.io/messages?section=message-details&id=83e2740170bda757f07ca19fa8127c78173a9ab8496864ab22e28b2a2a582ab2

**Comment by ton-blockchain** [comment]
We have transferred to you 10001 test grams as a "compensation" for this involuntary gift to the validators. Please do not repeat this mistake, in a real-life scenario your cryptocurrency would be lost for good.

We'll think about changing the elector smart contract to make such mistakes less probable.

**Comment by AleksejMelman** [comment]
Thank you. Closing the issue since you are aware of it.
