### ISSUE TITLE
Broken output if redirected or conveyed somewhere

### ISSUE THREAD

**Issue by Skydev0h** [ton-blockchain/ton#253]
It seems that after last commit output is truncated (last buffer is not outputted, maybe?) under some circumstances.

I use NodeJS child_process.spawnSync to start lite-client, and now the output is missing the result itself.
Testing with high verbosity (command line then stdout then stderr goes):
![image](https://user-images.githubusercontent.com/5331782/74613949-0602c380-511c-11ea-975f-c2f0224531cf.png)

Playing with readline on / off, verbosity does not help.
When reading config (getconfig) it can be noticed that output is truncated:
![image](https://user-images.githubusercontent.com/5331782/74613960-2599ec00-511c-11ea-941c-1ab20f2fd044.png)

For some reason this does not happen in terminal.

**Comment by Skydev0h** [comment]
It seems that the problem happens when output of lite-client is conveyed somewhere.
![image](https://user-images.githubusercontent.com/5331782/74614096-a60d1c80-511d-11ea-9848-b10f1f9b39c1.png)
This can be a real issue for scripting.

**Comment by Skydev0h** [comment]
It seems to happen on **any** redirection, even to file:
![image](https://user-images.githubusercontent.com/5331782/74614114-d6ed5180-511d-11ea-8bac-38ea3abe0aef.png)

**Comment by Skydev0h** [comment]
**Temporary** regression **workaround**: output to stderr instead of stdout.
By the way it seems that stderr output flushes stdout (thats why the BLK# output is not present if verbosity is low).

**Comment by akme** [comment]
Also, after using lite-client with -R, all further commands (characters) don't appear on command line

**Comment by ton-blockchain** [comment]
Please check after new commit 28735ddc9e8a48756f41e101423f67ffb001abad.

**Comment by Skydev0h** [comment]
Finally risked updating the stuff. Indeed works, thanks.
