### ISSUE TITLE
duplicate listening port

### ISSUE THREAD

**Issue by KStasi** [ton-blockchain/ton#254]
```
rldp-http-proxy/rldp-http-proxy -p 8080 -c 3333 -C ton-global-lite-client.config.json
```
Fails with:
```
[ 1][t 3][1582014753.970892191][rldp-http-proxy.cpp:610][!proxymain]	duplicate listening port
```

**Comment by akme** [comment]
Maybe you already have something running on one of these ports? Did you check it?

**Comment by KStasi** [comment]
Yes, nothing is running. I tried to change ports but still the same issue. 
It is probably important to admit that this problem appears after running  `rldp-http-proxy/rldp-http-proxy` in the second time (after Ctrl^C)

**Comment by deekshant-gammastack** [comment]
Hi.. I am facing the same issue ,  any updates regarding this problem? 
`rldp-http-proxy/rldp-http-proxy -p 8080 -c 3333 -C ton-global.config.json
[ 1][t 1][1586243111.590582848][rldp-http-proxy.cpp:610][!proxymain]	duplicate listening port
` @KStasi

**Comment by dkaraush** [comment]
I have faced the same issue.
It seems, that `port_` in script is not initialised, but is also checked on whether it is zero or not. [(rldp-http-proxy.cpp:610)](https://github.com/ton-blockchain/ton/blob/9f351fc29f7a0e8937897a873f62fc35418fdcb1/rldp-http-proxy/rldp-http-proxy.cpp#L610), [(rldp-http-proxy.cpp:1010)](https://github.com/ton-blockchain/ton/blob/9f351fc29f7a0e8937897a873f62fc35418fdcb1/rldp-http-proxy/rldp-http-proxy.cpp#L1010).
Maybe, problem is much deeper, I don't really know 🤷‍♂️

**Comment by igroman787** [comment]
I don’t remember why (I don’t remember what problem I encountered), but I use a slightly different config, namely `ton-global-lite-client.config.json`. And for me this command works:
```
rldp-http-proxy -p 8080 -c 3334 -C ton-global-lite-client.config.json -v 3
```
