### ISSUE TITLE
RLDP-HTTP proxy | rldp query failed [Error 602]

### ISSUE THREAD

**Issue by ObsidianDestroyer** [ton-blockchain/ton#259]
I'm trying to deploy site in "TON" by instructions described in document: https://test.ton.org/TonSites-HOWTO.txt \
I have build **rldp-http-proxy** on my server, but found that instruction does not describe many nuances.
I don’t have any more or less specific question, I’ll just describe the steps that I’ve completed, maybe someone will tell me what I did wrong, that instead of returning a response from the server, I received an error in.
1. Build `rldp-http-proxy` & `rldp`
2. Configured my Nginx like:
```nginx
server {
        listen 80;
        listen [::]:80;
        server_name <server-name>.ton vrcuq77h2qgfsd3aqyvdmnixdv3ljswzccxegc2py4erld7zj2kuo4h.adnl;

        location / {
                access_log on;
                proxy_pass http://127.0.0.1:3333/;
                proxy_set_header X-Forwarded-For $remote_addr;
                proxy_set_header   X-Real-IP $remote_addr;
                proxy_set_header Host $http_host;
                root /opt/www/dash;
                try_files $uri /index.html;
        }

}

```
3. Generate **adnlid** and run **RLDP-proxy** in server mode:
    - NOTE: RLDP-proxy in server mode takes some time to sync with **ADNL** nodes
```bash
root@cs765739:/usr/local/src/ton-build# rldp-http-proxy/rldp-http-proxy -a 80.93.182.20:3333 -L "ton-site.ton" -C ../ton-global-lite-client.config.json -A vrcuq77h2qgfsd3aqyvdmnixdv3ljswzccxegc2py4erld7zj2kuo4h -v 3 -d -D .
[ 2][t 7][1582469756.385961056][TonlibClient.cpp:1594][!tonlibclient][&!config->ignore_cache_]	Unknown LastBlockState: [Error : 0 : Unknown key]
```
4. And execute:
```bash
curl -I -x localhost:8080 http://vrcuq77h2qgfsd3aqyvdmnixdv3ljswzccxegc2py4erld7zj2kuo4h.adnl 
```
- - -
And then I see this log in the console:
```sh
[ 3][t 7][1582469934.604269266][rldp-http-proxy.cpp:932][!proxymain]	got HTTP request over rldp from qoRurJG1oJrXzq9QmsuztUfQK+JcMR0x3rYX3mJK3rU=
[ 3][t 7][1582469934.604687929][rldp.cpp:207][!proxymain][&RLDP_NOTICE]	rldp query failed: [Error : 602 : unknown server name]
```
I can’t understand why **RLDP-proxy** cannot find the server name, although I explicitly passed it to him with flag `-L <my-server-name>` and the name is also present in the "Nginx" settings. I have the assumption that I configured nginx incorrectly, but I could not do something better on my own.
Same result gives TON web proxy: http://78.155.217.86 | http://v1z.io

**Comment by ObsidianDestroyer** [comment]
Tried another configuration of **Nginx** and **rldp-http-proxy** on my server logged something other:
```bash
[ 3][t 2][1582474311.149178743][rldp-http-proxy.cpp:932][!proxymain]	got HTTP request over rldp from tsVwLu9a2WComzpHSCk4zQfZuo2MoHMYBWEF/V5VqMI=
[ 3][t 2][1582474311.151317120][rldp-http-proxy.cpp:983][!proxymain]	starting HTTP over RLDP request
[ 3][t 2][1582474311.151825666][rldp-http-proxy.cpp:161][!HttpPayloadReceiver(R)]	HttpPayloadReceiver: sent=false completed=true ready=0 watermark=32768
[ 3][t 0][1582474311.154432058][http-outbound-connection.cpp:78][!outconn]	sending HTTP request
[ 3][t 0][1582474311.161548615][http-connection.cpp:71][!outconn]	close after read
[ 3][t 3][1582474321.162160158][rldp-http-proxy.cpp:371][!HttpPayloadSender(R)]	timeout on RLDP connection. closing http transfer

```

**Comment by ton-blockchain** [comment]
Try `-L "vrcuq77h2qgfsd3aqyvdmnixdv3ljswzccxegc2py4erld7zj2kuo4h.adnl"` instead of or together with `-L "ton-site.ton"`.

**Comment by ObsidianDestroyer** [comment]
> Try `-L "vrcuq77h2qgfsd3aqyvdmnixdv3ljswzccxegc2py4erld7zj2kuo4h.adnl"` instead of or together with `-L "ton-site.ton"`.
> 
> Alternatively, `-L '*'` should also work.

Ye, I've tried to set `-L "*"`
Nginx logs:
```bash
127.0.0.1 - - [23/Feb/2020:19:25:05 +0300] "HEAD http://vrcuq77h2qgfsd3aqyvdmnixdv3ljswzccxegc2py4erld7zj2kuo4h.adnl/test_page.html HTTP/1.1" 404 0 "-" "curl/7.67.0"
127.0.0.1 - - [23/Feb/2020:19:25:24 +0300] "HEAD / HTTP/1.0" 200 0 "-" "curl/7.67.0"
```
But **rldp-http-proxy** still answers:
```bash
[ 3][t 6][1582475124.393808126][rldp-http-proxy.cpp:983][!proxymain]	starting HTTP over RLDP request
[ 3][t 6][1582475124.394193411][rldp-http-proxy.cpp:161][!HttpPayloadReceiver(R)]	HttpPayloadReceiver: sent=false completed=true ready=0 watermark=32768
[ 3][t 0][1582475124.394744158][http-outbound-connection.cpp:78][!outconn]	sending HTTP request
[ 3][t 0][1582475124.395437241][http-connection.cpp:71][!outconn]	close after read
[ 3][t 3][1582475134.396528721][rldp-http-proxy.cpp:371][!HttpPayloadSender(R)]	timeout on RLDP connection. closing http transfer
```

**Comment by ObsidianDestroyer** [comment]
> Try `-L "vrcuq77h2qgfsd3aqyvdmnixdv3ljswzccxegc2py4erld7zj2kuo4h.adnl"` instead of or together with `-L "ton-site.ton"`.
> 
> Alternatively, `-L '*'` should also work.

By the way, I found interesting behavior. If you raise **RLDP** as a server, then all proxies running before the server was raised will not be able to access it. At least this happened to me with a local proxy and remote on a separate server.

**Comment by ton-blockchain** [comment]
Do other TON sites such as `http://test.ton/` work?
It may happen that your client HTTP->RLDP is unable to receive incoming UDP packets.

**Comment by ObsidianDestroyer** [comment]
> Do other TON sites such as `http://test.ton/` work?
> It may happen that your client HTTP->RLDP is unable to receive incoming UDP packets.

Yep, other sites like `test.ton` or `vcqmha5j3ceve35ammfrhqty46rkhi455otydstv66pk2tmf7rl25f3.adnl` works fine.

**Comment by ObsidianDestroyer** [comment]
@ton-blockchain , solved my problem, its covered in Nginx conf as you can see above. Thanks for your answers.
