### ISSUE TITLE
latest lite-client does not output full block when executing dumpblock command

### ISSUE THREAD

**Issue by AleksejMelman** [ton-blockchain/ton#260]
For some reason, when lite-client tries to get a dump of an old block it returns not the whole output.
Here is the example of the command:

`dumpblock (-1,8000000000000000,1783265):5665BD991898ABB62C964114AD3D59695EDB4923580F24B79482E074B99EBFDC:384A6D6707525DD5FB8F92661E6182C16A62F698939C87372EE440C86ECF294F`

also verbosity option does not help:

`lite-client -C ton-lite-client-test1.config.json -v 0 -c "dumpblock (-1,8000000000000000,1783265):5665BD991898ABB62C964114AD3D59695EDB4923580F24B79482E074B99EBFDC:384A6D6707525DD5FB8F92661E6182C16A62F698939C87372EE440C86ECF294F"| wc -l`
1883

In the output, section " extra:(block_extra" has no closing parenthesis.

lite-client was compiled today.

**Comment by AleksejMelman** [comment]
Found the more precise error message:

dumpblock (-1,8000000000000000,1796897):0DBFC0978705EB830E9EC726724EA4E4AD18EAA799B00B5D3C11823B58E34646:991446B89C0FD29C0AF15A8DC5E5913F41B45A87DE0F4A1900C7A1479AB46B2E

omitted output and in the end prints out:
**cell output limit reached**

**Comment by ton-blockchain** [comment]
Try setting the value of command line parameter `--print-limit` of `lite-client` to a higher value, e.g. `--print-limit=1000000`. This should help if you want to print larger object.

**Comment by AleksejMelman** [comment]
The issue has been fixed.
