### ISSUE TITLE
Actual testgiver address

### ISSUE THREAD

**Issue by Anatolii-Shevchuk** [ton-blockchain/ton#265]
Hi all
Can someone, please, provide actual testgiver address?
If I correct understand network was restarted or  testgiver contract redeployed, is it? Because I can`t get test grams rely on testgiver address from this repository, just get  **invalid smart-contract address** status. 
https://github.com/ton-blockchain/ton/blob/77842f9b637dd2efcd684a4668e9ff4a173449f8/crypto/smartcont/testgiver.fif

Additionally, I used **Non-bounceable address (for init**) to get test grams is it correct?

**Comment by Skydev0h** [comment]
Testgiver address is [-1:6666666666666666666666666666666666666666666666666666666666666666](https://github.com/ton-blockchain/ton/blob/master/crypto/smartcont/gen-zerostate.fif#L88), but it is [empty as of now](https://test.ton.org/testnet/account?account=-1%3A6666666666666666666666666666666666666666666666666666666666666666).

**Comment by naumovlab** [comment]
You can request test Grams in this thread on the forum ;)
https://tontalk.org/threads/132/

**Comment by EmelyanenkoK** [comment]
Is not relevant anymore.
