### ISSUE TITLE
Multisig flood parameter isn't enough to prevent an attack

### ISSUE THREAD

**Issue by rainydio** [ton-blockchain/ton#266]
Flood parameter prevents single key from sending many pending queries consuming all contract funds. It is increased each time pending query is created and it's decreased once query is confirmed.

But this assumes honest attacker who is sending otherwise valid queries. If instead attacker crashes contract somewhere between `set_gas_limit(100000)` and `commit()` flood update will not be saved and contract funds can be drained. Simply sending query that is bound more than one hour into the future is enough.

https://github.com/ton-blockchain/ton/blob/master/crypto/smartcont/multisig-code.fc#L157-L167

PS: also flood parameter isn't decreased when query expires and so it puts lifetime limit on how many queries that did not received enough approvals multisig participant can send.

**Comment by ton-blockchain** [comment]
Looks legit, thank you.

This `throw_if` is completely against the intention of `set_gas_limit` - `commit` block. The original idea was that nothing bad might happen in this block. Then at some point, this `throw_if` was added.

The flood parameter should be decreased too.

**Comment by EmelyanenkoK** [comment]
Should be fixed in [current multisig](https://github.com/ton-blockchain/ton/blob/master/crypto/smartcont/multisig-code.fc)
