### ISSUE TITLE
gen-zerostate.fif critical_params invalid value

### ISSUE THREAD

**Issue by hortonelectric** [ton-blockchain/ton#269]
Since commit 54c7a4dcc3e53751c3e25af7b8b7172506af1f12

When running gen-zerostate.fif

```c
[ 1][t 0][1584706574.541335106][create-state.cpp:776]	{}
[ 1][t 0][1584706574.683099031][words.cpp:3046]	gen-zerostate.fif:205: config.critical_params!: invalid value for indicated configuration parameter
Error interpreting file `/Users/dawud/tfn/ton/crypto/smartcont/gen-zerostate.fif`: [Error : 0 : error interpreting included file `gen-zerostate.fif` : gen-zerostate.fif:205: config.critical_params!: invalid value for indicated configuration parameter]
```

the line in question: 

`( -1000 -1001 9 10 32 34 36 ) config.critical_params!`

Apparently, these values are incorrect and so the zerostate cannot be built.

**Comment by ton-blockchain** [comment]
Are you sure you use a recent version of `create-state` compiled from the same sources?

**Comment by hortonelectric** [comment]
> Are you sure you use a recent version of `create-state` compiled from the same sources?

This must have been the problem, and I would like to point out to anyone who has a similar problem the following tips. 

A. that using --no-cache on your docker container build commands will ensure that you don't run into similar issues 

B. You might experience this as a "glitch" that solves itself when you re-compile from a fresh clone, or even just recompiling the existing build.
