### ISSUE TITLE
Subdomain Expiration

### ISSUE THREAD

**Issue by votnichosi** [ton-blockchain/ton#270]
How, through a light client, the owner of example.temp.ton can find out how many seconds are left before the loss of control over example.temp.ton?

**Comment by ton-blockchain** [comment]
First, you have to find out the address of the automatic DNS smart contract for `temp.ton`:

```
> dnsresolve temp.ton 0
...
Result for domain 'temp.ton' category 0 (all categories)
raw data: x{F0}
 x{BA938003217AEADED81CF291B84D968F2D06462EFF640689F1F34A123195F0FD96696F3_}

category #-1 : (dns_next_resolver
  resolver:(addr_std
    anycast:nothing workchain_id:0 address:x190BD756F6C0E7948DC26CB47968323177FB20344F8F9A50918CAF87ECB34B79))
	next resolver 0:190BD756F6C0E7948DC26CB47968323177FB20344F8F9A50918CAF87ECB34B79 = EQAZC9dW9sDnlI3CbLR5aDIxd_sgNE-PmlCRjK-H7LNLeUXN
```

Then you run get-method `getexpiration` of this smart contract with the parameter equal to your subdomain:

```
> runmethod EQAZC9dW9sDnlI3CbLR5aDIxd_sgNE-PmlCRjK-H7LNLeUXN getexpiration "example"
...arguments:  [ CS{Cell{000e6578616d706c65} bits: 0..56; refs: 0..0} 110574 ] 
result:  [ 0 ] 
remote result (not to be trusted):  [ 0 ] 
```

**Comment by ton-blockchain** [comment]
This is the expiration Unixtime. If it is zero, then the subdomain is either not registered or already expired.

**Comment by awesome-doge** [comment]
issue merge
https://github.com/ton-blockchain/ton/issues/280
