### ISSUE TITLE
TON uses 'orphan' unmerged RocksDB commit

### ISSUE THREAD

**Issue by hortonelectric** [ton-blockchain/ton#284]
https://github.com/ton-blockchain/ton/issues/32

Please refer to the issue above.

The RocksDB submodule in TON uses a commit from September of 2018 (!!!)

https://github.com/facebook/rocksdb/commit/d6f2ecf49c28fee225477d39e2a1535a87919afe

which is part of an UNMERGED pull request (!!!!)

https://github.com/facebook/rocksdb/pull/4423 

I think this is cause for alarm. The following release would have been the likely target for TON's submodule:

https://github.com/facebook/rocksdb/releases/tag/v5.17.2 which contains bugfixes and is at least on the main RocksDB Git Tree.

There was also a v5.18.3 release (the final v5 release) which contains 160+ commits / 20+ bugfixes. 

Nevermind that there were another 1200+ commits in the ensuing 2 years for v6

**Comment by hortonelectric** [comment]
RocksDB v6.7.3 compiles, but the validator engine fails with the following:

```[ 0][t 2][1587113279.016908169][Status.h:264][!NetworkManager]	Unexpected Status [PosixError : Address already in use : 48 : Failed to bind a socket] in file /Users/dawud/tfn/tfn-ton/adnl/adnl-network-manager.cpp at line 73
[pid 4691] [time 1587113279] [14][t 7][1587113279.016950130][MpmcWaiter.h:287][&waiter]	Search -> Work Signal: 6
```
I managed to cherry pick this commit from December 2019 
https://github.com/facebook/rocksdb/commit/a796c06fef6a8e43d793f8e627db3f29e6f95964

And then compile it again with that one-line fix to get past the issue I was experiencing.

But I think the larger question here is why are we not even updating minor versions and patches of rocksdb since the 2-year old commit?

**Comment by EmelyanenkoK** [comment]
Will be solved in https://github.com/newton-blockchain/ton/tree/safer_overlay_plus
