### ISSUE TITLE
[tonlibjson] Memory leak

### ISSUE THREAD

**Issue by akme** [ton-blockchain/ton#285]
Looks like we found memory leak issues in tonlibjson while using it from golang:
```
total runtime: 166.40s.
bytes allocated in total (ignoring deallocations): 34.17MB (205.35KB/s)
calls to allocation functions: 52706 (316/s)
temporary memory allocations: 13324 (80/s)
peak heap memory consumption: 23.77MB
peak RSS (including heaptrack overhead): 41.32MB
total memory leaked: 23.57MB
```
Full log: [heap_leak.txt](https://github.com/ton-blockchain/ton/files/4529409/heap_leak.txt)

**Comment by ton-blockchain** [comment]
Like in #268, it is because tonlib clients are not properly closed. Not sure why though.

It looks like some problems in golang wrapper with tonlib usage. Do you have some easy way to reproduce this problem?

**Comment by akme** [comment]
Ok, found out that CGO needs additional memory management.
