### ISSUE TITLE
Validator does not sync

### ISSUE THREAD

**Issue by igroman787** [ton-blockchain/ton#288]
I use this commit: [2f81361](https://github.com/ton-blockchain/ton/commit/2f81361a02e6e696ad5aa42119947a96d017df48)
Faced a problem - I can’t synchronize a node. Constantly error:
```
[ 3][t 6][1588010431.476365805][full-node-shard.cpp:582][!manager]      dropped broadcast: [Error : 651 : node not started]
```

Full logs after starting the validator: 
[v.log](https://github.com/ton-blockchain/ton/files/4541321/v.log)

**Comment by igroman787** [comment]
Everything worked fine in this commit: [16a4566](https://github.com/ton-blockchain/ton/commit/16a45660911a53020d7f0ab0536101c901e6d721)

**Comment by Kyborg2011** [comment]
@igroman787 I have this error, too.

**Comment by igroman787** [comment]
This problem persisted with a commit: [be9c34c](https://github.com/ton-blockchain/ton/commit/16a45660911a53020d7f0ab0536101c901e6d721).

Validator does not sync with errors:
```
[ 3][t 9][1588317879.657247543][manager.cpp:1583][!archive]     failed to download archive slice: [Error : 652 : adnl query timeout]
[ 3][t10][1588317881.732154131][manager.cpp:1583][!archive]     failed to download archive slice: [Error : 651 : remote db not found]
[ 3][t 6][1588318452.483181715][import-db-slice.cpp:378][!archiveimport]        [Error : 651 : no proof for shard block [ w=0 s=576460752303423488 seq=4804279 qV6IhdD1DE5W2/h9rtRl/XpBVAX7PhrFGgrjjsaQJN0= kS237CXtEuC7ID01J4hvkZIfKtGiO2wDsiPpEW1HkIY= ]]
```

**Comment by igroman787** [comment]
This problem persisted with a commit: [040df63](https://github.com/ton-blockchain/ton/commit/040df63c9864f2f37ebe50c4cafcc01f2d5d2d5c)

Validator does not sync with errors:
```
[ 3][t11][1588849021.392574310][import-db-slice.cpp:378][!archiveimport]  [Error : 651 : no proof for shard block [ w=0 s=1729382256910270464 seq=4961358 pgSHTFBBZngs4izVxjle50Va67fIbC4ill9qMQx79JE= 3d8ske9lq9MNQVt6V27uQmMqMChoTzsLJGbhYp4A3v8= ]]
```

Full log file: [v.log](https://github.com/ton-blockchain/ton/files/4593694/v.log)

**Comment by Skydev0h** [comment]
+1 have the same problem with validators that have been shut down for a while

**Comment by lvxv** [comment]
how to deploy private network?

**Comment by igroman787** [comment]
This problem arose because of different versions of validators - most of the validators were on the old version, so some validators with a newer commit could not synchronize with the network. It was tested in another test network.
