### ISSUE TITLE
Command addpermkey in validator-engine-console removes a key from the keyring

### ISSUE THREAD

**Issue by logvik** [ton-blockchain/ton#293]
I think this is a bug or wrong behavior due to initial conditions.
``` sh
> newkey
created new key 0800BAC46565900D1275D2A61C41BC7C56890FA2DF0E6D52BEA86F7CEE83C92C
> addpermkey 0800BAC46565900D1275D2A61C41BC7C56890FA2DF0E6D52BEA86F7CEE83C92C 0 1
success
> addvalidatoraddr 9AD60917D565DD539616467B1E73B89BA583D6C218BF01460A2388944400C6D4 0800BAC46565900D1275D2A61C41BC7C56890FA2DF0E6D52BEA86F7CEE83C92C 1
Failed addvalidatoraddr query: [Error : 2 : failed to get public key:  key not in db:  File "/mnt/volume/ton/db//keyring/0800BAC46565900D1275D2A61C41BC7C56890FA2DF0E6D52BEA86F7CEE83C92C" can't be opened for reading]
```
Procedure passes in accordance with `4. Creating a validator public key and ADNL address` in https://ton.org/Validator-HOWTO.txt but with the unexpected result

**Comment by akme** [comment]
Try to set the more realistic timestamp for the expire date. (not just 1)

**Comment by logvik** [comment]
@akme, Thank you for advice. Here I have found that the second parameter is expire_at_
https://github.com/ton-blockchain/ton/blob/040df63c9864f2f37ebe50c4cafcc01f2d5d2d5c/validator-engine-console/validator-engine-console-query.h#L467 . Here assumes that each time needs to generate a new one for each elections.
