### ISSUE TITLE
Не официальный репозиторий TON

### ISSUE THREAD

**Issue by twepl** [ton-blockchain/ton#296]
По сколько официальный проект закрыт, и разработчики больше не поддерживают код, я создал другой репозиторий для [исправления багов и ошибок](https://github.com/tongram/ton).

Вы можете использовать [Pull requests](https://github.com/tongram/ton/pulls), я одобрю любые изменения в коде, вы так же можете добавлять дополнительный функционал API если вам нужно это для приложения.
Однако другие разработчики могут оспорить или изменить ваши изменения.

Я так же изменил лицензию на [MIT](https://github.com/tongram/ton/blob/master/LICENSE), мне кажется она проще и понятней, хотя особо не отличается.

https://github.com/tongram

**Comment by F5050** [comment]
Советую присмотреться к команде newton, там довольно много русскоязычных: https://newton-blockchain.github.io/

**Comment by ton-blockchain** [comment]
Nope, it's illegal to change GPL license to MIT. Please change back or remove your copy of TON sources from public access.

**Comment by twepl** [comment]
> GPL license to MIT

Вы же забросили свой проект официально, разве нет?
MIT позволяет как угодно использовать код, а GPL **требует** открывать исходники своего проекта.
Так же MIT разрешает изменять лицензию, а ваша лицензия не позволяет этого, разве неправильно сделать ее MIT?
License and copyright notice Telegram Systems LLP я указал.
Я могу еще что-то указать, если вы разрешите использовать MIT

Если вы не разрешаете использовать MIT я удалю репозиторий целиком.

**Comment by twepl** [comment]
Я обосную причины почему мне нужна лицензия MIT, возможно некоторые не понимаю всю сложность лицензий.

**1 Конечный продукт можно распространять под любой лицензией.**
Любой разработчик, который добавит Pull requests в мой неофициальный репозиторий, может забрать свой код обратно и использовать его в своем проекте под любой лицензией

**2 Исходные коды предоставлять не обязательно.**
Код, который был добавлен не должен получить строгие правила в предоставлении кода, то есть быть под лицензией GPL

**3 Отказ от гарантий. Пользователь использует ПО на свой страх и риск.
4 Отказ от ответственности. Вы ничего не сможете предъявить разработчику.**
Вот тут возможно много людей не понимают, что это значит.
Я не хочу нести ответственность за код и не собираюсь его поддерживать под лицензией GPL. Если кто-то потеряет деньги или его взломают это не мои проблемы.

Так же это может вызвать путаницу в суде, если человек подаст заявление на меня в суде как на разработчика, по причине каких то тестовых монет, что судья должен решить, это какой то бред получается.
В любом случае подать заявления за взлом оборудования на меня можно и отсудить свои потери.

Я не готов нести ответственность за то что кто то добавил Pull requests и создал уязвимость в коде.

**Comment by twepl** [comment]
> Nope, it's illegal to change GPL license to MIT. Please change back or remove your copy of TON sources from public access.

Исправил лицензию, но оставил за собой MIT Лицензию, еще добавил небольшое описание в README файл.

Как это работает: 
Если вы будете публиковать код в [неофициальном репозитории](https://github.com/tongram), то он публикуется под лицензией MIT.
Весь остальной код работает по лицензии GPL или в зависимости что укажут разработчики Telegram Systems LLP.
