### ISSUE TITLE
Эмиссия testnet

### ISSUE THREAD

**Issue by twepl** [ton-blockchain/ton#298]
Я правильно понимаю работу тестнета, если я ошибся скажите где ошибка.
Раньше был один адрес с `5 000 000 000` монет, сейчас эти монеты распределены на несколько кошельков.

https://github.com/ton-blockchain/ton/blob/master/doc/TestGrams-HOWTO

Small testgivers (deliver from 10 to 100 test Grams every several minutes):

Balance: ` 12 696 553` 1 address: `kf-kkdY_B7p-77TLn2hUhM6QidWrrsl8FYWCIvBMpZKprBtN` 
Balance: ` 12 693 550` 2 address: `kf8SYc83pm5JkGt0p3TQRkuiM58O9Cr3waUtR9OoFq716lN-`
Balance: ` 12 695 252` 3 address: `kf-FV4QTxLl-7Ct3E6MqOtMt-RGXMxi27g4I645lw6MTWraV`
Balance: ` 12 694 451` 4 address: `kf_NSzfDJI1A3rOM0GQm7xsoUXHTgmdhN5-OrGD8uwL2JMvQ`
Balance: ` 12 693 851` 5 address: `kf8gf1PQy4u2kURl-Gz4LbS29eaN4sVdrVQkPO-JL80VhOe6`
Balance: ` 12 689 347` 6 address: `kf8kO6K6Qh6YM4ddjRYYlvVAK7IgyW8Zet-4ZvNrVsmQ4EOF`
Balance: ` 12 693 550` 7 address: `kf-P_TOdwcCh0AXHhBpICDMxStxHenWdLCDLNH5QcNpwMHJ8`
Balance: ` 12 692 149` 8 address: `kf91o4NNTryJ-Cw3sDGt9OTiafmETdVFUMvylQdFPoOxIsLm`
Balance: ` 12 690 848` 9 address: `kf9iWhwk9GwAXjtwKG-vN7rmXT3hLIT23RBY6KhVaynRrIK7`
Balance: ` 12 699 155` 10 addres: `kf8JfFUEJhhpRW80_jqD7zzQteH6EBHOzxiOhygRhBdt4z2N`

Large testgivers (deliver 10000 test Grams at least once a day):

Balance:  `455 099 978` 1 address: `kf8guqdIbY6kpMykR8WFeVGbZcP2iuBagXfnQuq0rGrxgE04`
Balance: ` 454 799 977` 2 address: `kf9CxReRyaGj0vpSH0gRZkOAitm_yDHvgiMGtmvG-ZTirrMC`
Balance: ` 454 399 977` 3 address: `kf-WXA4CX4lqyVlN4qItlQSWPFIy00NvO2BAydgC4CTeIUme`
Balance: ` 452 599 975` 4 address: `kf8yF4oXfIj7BZgkqXM6VsmDEgCqWVSKECO1pC0LXWl399Vx`
Balance: ` 452 299 975` 5 address: `kf9nNY69S3_heBBSUtpHRhIzjjqY0ChugeqbWcQGtGj-gQxO`
Balance: ` 454 299 977` 6 address: `kf_wUXx-l1Ehw0kfQRgFtWKO07B6WhSqcUQZNyh4Jmj8R4zL`
Balance: ` 451 599 975` 7 address: `kf_6keW5RniwNQYeq3DNWGcohKOwI85p-V2MsPk4v23tyO3I`
Balance: ` 453 199 976` 8 address: `kf_NSPpF4ZQ7mrPylwk-8XQQ1qFD5evLnx5_oZVNywzOjSfh`
Balance: ` 450 099 973` 9 address: `kf-uNWj4JmTJefr7IfjBSYQhFbd3JqtQ6cxuNIsJqDQ8SiEA`
Balance: ` 453 799 977` 10 address: `kf8mO4l6ZB_eaMn1OqjLRrrkiBcSt7kYTvJC_dzJLdpEDKxn`

Я возьму последние цифры они все равно приблизительно одинаковые

Считаем:
`453 799 155 ` * `10` = `4 537 991 550`
`12 699 155` * `10` = `126 991 550`
`4 537 991 550` + `126 991 550` = `4 664 983 109`  как видите почти `5 000 000 000` монет

Идем дальше:
С одного Large testgivers валидаторы получают `10 000` test Grams как написано в документе, остался вопрос в скорости получение этих монет, в документе написано `10 000` монет в день. Но blockchain explorer пишет то один раз в `5` минут то в `1` час, здесь данные не стабильны, пока не понятно.

Тут нам поможет математика, куда же без нее
В `1` году `8760` часов, запомните это.

`453 799 155` / `10 000` = `45379` блоков
Кто не понял мы разделили баланс одного адреса на `10 000` монет который он выдает за блок. И получаем примерное количество блоков, когда этот адрес станет пустым.

Теперь самое интересное:
Если пройдет `5` лет это `43800` часов.
Тогда адрес который выдает по `10 000` монет в час, через `5` лет станет пустым. Но как показывает blockchain explorer адреса с Large testgivers не стабильны и могут выдавать блок каждых `30` минут.

**Возникают такие вопросы, что произойдет, когда опустеют все адреса?**

**Comment by twepl** [comment]
За 13 дней было добыто примерно 125 000 000 монет с каждого адреса.
Если так дальше пойдет через 2 месяца они будут пустые.

**Comment by igroman787** [comment]
Вы не правильно понимаете смысл этих действий. Никто не обещает что эти "гиверы" постоянно будут раздавать монеты. Они созданы в первую очередь для устранения главного недостатка технологии PoS, а именно централизации (тот, кто запускает сеть будет контролировать кто будет валидатором). После добавления данного замысла, а именно частичку PoW - все желающие получат возможность добыть себе немного (или много, смотря у кого какие мощности) монет и стать валидатором, тем самым будет достигнута децентрализация.

Ну и ответ на ваш вопрос, что будет с "гивером", когда он опустеет:
Ничего не произойдет. У всего есть начало и конец, следовательно конец этого "гивера" настал и больше он не сможет дать монет. Думаю на этом тему можно закрывать.

**Comment by twepl** [comment]
Это не похоже на децентрализацию скорее на картель, лично мое мнение когда опустеют эти адреса монета умрет.
