### ISSUE TITLE
P2P Exchange Buy or sell GRAM testnet2

### ISSUE THREAD

**Issue by twepl** [ton-blockchain/ton#301]
English: I need to buy some coins for the tap, maybe someone wants to sell?

Русский: Мне нужно купить несколько монет для крана, может быть, кто-то хочет продать?

https://t.me/tongram_exchange

**Comment by igroman787** [comment]
Test coins are test coins for not being sold. If someone is trying to sell them to you, then run away from him - the air should be free for everyone.
You can get test coins for free from the bots that give them away. Or ask someone who used to be a validator on the testnet.

**Comment by twepl** [comment]
> Test coins are test coins for not being sold. If someone is trying to sell them to you, then run away from him - the air should be free for everyone.
> You can get test coins for free from the bots that give them away. Or ask someone who used to be a validator on the testnet.

I don't mind buying testnet coins, even if they are free.

**Comment by igroman787** [comment]
Do something more useful for yourself - read the opportunity to earn test coins with your powers: https://github.com/ton-blockchain/ton/blob/master/doc/TestGrams-HOWTO
Even if you do not have a powerful server, this is not a problem. Just the first ten givers are designed for ordinary users - the complexity of the work is reduced by about 10 times.

**Comment by twepl** [comment]
> Do something more useful for yourself - read the opportunity to earn test coins with your powers: https://github.com/ton-blockchain/ton/blob/master/doc/TestGrams-HOWTO
> Even if you do not have a powerful server, this is not a problem. Just the first ten givers are designed for ordinary users - the complexity of the work is reduced by about 10 times.
> 
> Or maybe this will help you: https://faucet.grmhub.com/
