### ISSUE TITLE
TON and TON Crystal have identical addresses, no ability to contact wallet owner

### ISSUE THREAD

**Issue by ayerix** [ton-blockchain/ton#318]
The problem is: I bought some TONs recently and transfered them to my wallet EQAeJIHVWlSvAsyORbG1AtOUVE211_iYqqGSv6NhFAyTnVse
They didn't come. I started investigation and discovered that coins I ordered actually was not a TONs but TON CRYSTALs and what the main problem: I send them to the wallet with the same address existing in the other blockchain. Of course I can't access it anyhow. Also I can't revert transaction and I can't contact person who owns the wallet to ask him or her return this occassional transfer back.. I understand that it is nothing to blame for this except myself, but I'm pretty sure that this situation will happen many times:
- Not to many people are awared of another network existing with pretty much the same name, icon, same looking client, same way of restoring pwd and same wallet addresses
- TON CRYSTALs are twice cheaper so I'm pretty sure people would think that it's just an opportunity to buy them cheaper

What is wrong in this situation:
- Addresses should not belong to both networks! Either one, either another, but not both! Not the same address here and there
- Ability to revert wrong transaction (sent to inactive wallet) or at least contact wallet owner would be greatly appreciated

**Comment by ibsaaqa11** [comment]
ton://transfer/EQA-OqXm5f9ZRFEg5OEs4QkJyv-mN4VaooZ276_l9Klp04_5

**Comment by ibsaaqa11** [comment]
I can't get my Wallet

**Comment by EmelyanenkoK** [comment]
Check https://github.com/Custler/tc_Rescue for help.
