### ISSUE TITLE
VALIDATE_ACCOUNT_STATEcannot deserialize account proofinvalid bag-of-cells failed to deserialize cell

### ISSUE THREAD

**Issue by smith111707** [ton-blockchain/ton#319]
The error occurs in the both miner and wallet.

[ 1][t 3][][tonlib-cli.cpp:750][!PowMiner][&status.is_error()]	pminer: [Error : 500 : VALIDATE_ACCOUNT_STATEcannot deserialize account proofinvalid bag-of-cells failed to deserialize cell #39 [Error : 0 : First depth mismatch in a MerkleProof special cell]]
[ 3][t 3][][tonlib-cli.cpp:656][!PowMiner]	pminer: stopped

![image](https://user-images.githubusercontent.com/92824072/140706042-77a2c903-a05f-4205-ab7b-0d87a8379e3a.png)

**Comment by Ivandanilovich** [comment]
Have the same error, but web app still work correct.

**Comment by smith111707** [comment]
@Ivandanilovich update the wallet, it should resolve the issue

**Comment by EmelyanenkoK** [comment]
Fixed in https://github.com/ton-blockchain/ton/commit/64e68a47ec63d1968e7cbef445c8e6c51a1015d4 . Please update the wallet.
