### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by koalex** [ton-blockchain/ton#321]
Doing next steps (Ubuntu 20):
`git clone https://github.com/newton-blockchain/ton`
`cd ton`
`git submodule update --init`
`cd ~ && mkdir build && cd build`
`cmake ~/ton/ -DCMAKE_BUILD_TYPE=Release`
`make`

on 75% I've got an error:
```
/usr/bin/ld: storage/libstorage.a(TorrentCreator.cpp.o): in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > td::serialize<ton::TorrentHeader>(ton::TorrentHeader const&)':
TorrentCreator.cpp:(.text._ZN2td9serializeIN3ton13TorrentHeaderEEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_[_ZN2td9serializeIN3ton13TorrentHeaderEEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_]+0x3f): undefined reference to `void ton::TorrentHeader::store<td::TlStorerCalcLength>(td::TlStorerCalcLength&) const'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/test-storage.dir/build.make:151: test-storage] Error 1
make[1]: *** [CMakeFiles/Makefile2:2079: CMakeFiles/test-storage.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```
It looks like some library is missing but which one?

**Comment by grGred** [comment]
> Doing next steps (Ubuntu 20): `git clone https://github.com/newton-blockchain/ton` `cd ton` `git submodule update --init` `cd ~ && mkdir build && cd build` `cmake ~/ton/ -DCMAKE_BUILD_TYPE=Release` `make`

I've done the same thing and at 76% recived the same error as you.

> It looks like some library is missing but which one?

I will try this [comment](https://github.com/ton-blockchain/ton/issues/16#issuecomment-531727088) right now and hope it actually works. Let me know if you succeed.

**Comment by grGred** [comment]
[This instructions](https://github.com/ton-blockchain/ton/pull/10/files) still work, even though they are 2 year old. What a good project! Check out this steps for Linux, worked fine for me.

## Building on Linux (Debian based)

Install dependencies:
```
sudo apt update && sudo apt upgrade 
sudo apt install cmake clang ninja-build pkg-config libssl-dev zlib1g-dev libreadline-dev gperf libmicrohttpd-dev
```

Make & build with a ninja-build (assuming the repository directory is titled "telegram-node"): 
```
cd telegram-node
mkdir build
cd build
cmake -G "Ninja" ..
ninja
```

**Comment by uhvyuhs77** [comment]
This is my first run on any of this how do I go about - - receiving the [](work and library)
```~~ [license and files ] -

**Comment by uhvyuhs77** [comment]
> This is my first run on any of this how do I go about  receiving the work library with a license and files

**Comment by uhvyuhs77** [comment]
Never mind thank you for all of this

**Comment by koalex** [comment]
On Ubuntu 21 works fine

**Comment by EmelyanenkoK** [comment]
Please use [workflow](https://github.com/ton-blockchain/ton/blob/master/.github/workflows/ubuntu-18.04-compile.yml) as guide for compilation.
