### ISSUE TITLE
[full-node-shard.cpp:447][!manager]	getnextkey: [Error : 651 : not inited]

### ISSUE THREAD

**Issue by NoFeeding** [ton-blockchain/ton#326]
Hi I am new here and since I started to try to build full TON node I always encounter this Error whenever I start validator.

From the very beginning it will say found init block, key block candidate and state is not persistent things like that and after those I get always getnextkey: [Error : 651 : not inited].

I am using the docker version of ton node and the command I started it is 
< docker run --name ton --mount source=ton-db,target=MYDIRECTORY --network host -e "PUBLIC_IP=MYREALIPIPUTNUMBERHERE" -e "CONSOLE_PORT=6000" -it ghcr.io/newton-blockchain/ton >

I did put real directory and IP address in docker command then it started like this

[+] Running validator-engine
[ 3][t 1][2021-11-30 07:29:56.271960038][validator-engine.cpp:1287][!validator-engine]	found init block [ w=-1 s=9223372036854775808 seq=16051563 RT/O6YDt/Xf8YxHRsQLSrJWbENQxCOqINWbTB0EdD1s= CRo0DhWm+zngZG2mIDR6G5uiAQ/n6xOgwYRskRuYOME= ]
[ 3][t 4][2021-11-30 07:29:56.290440422][manager.cpp:1429][!manager]	failed to load blocks from import dir: [PosixError : No such file or directory : 2 : File "/var/ton-work/db/import" can't be opened for reading]
[ 3][t 2][2021-11-30 07:29:56.310141048][manager-init.cpp:35][!reiniter]	init_block_id=[ w=-1 s=9223372036854775808 seq=16051563 RT/O6YDt/Xf8YxHRsQLSrJWbENQxCOqINWbTB0EdD1s= CRo0DhWm+zngZG2mIDR6G5uiAQ/n6xOgwYRskRuYOME= ]
[ 2][t 2][2021-11-30 07:29:56.311797937][manager-init.cpp:86][!downloadproofreq]	failed to download proof link: [Error : 651 : no nodes]
[ 2][t 6][2021-11-30 07:29:57.312902006][manager-init.cpp:86][!downloadproofreq]	failed to download proof link: [Error : 651 : no nodes]
[ 2][t 3][2021-11-30 07:30:03.481269483][manager-init.cpp:183][!reiniter]	last key block is [ w=-1 s=9223372036854775808 seq=16125009 Qdgb8uu+EkeJpaHWbvPk0KNDN48eVqPFkYfRsw7j7cU= 6vG0kRYHKrwDLj63Gu5eTY7SxqM2VJCoZ1WdxwhBta0= ]
[ 2][t 1][2021-11-30 07:30:07.576488684][manager-init.cpp:183][!reiniter]	last key block is [ w=-1 s=9223372036854775808 seq=16198191 eBwc/rNt2VltVKzOcYvwRKziqerasWRJVV3rsWp895c= c8W3P9A9Zhlc3SLYZSM4ceIfdkNoW+vHrbi6WHikw5E= ]
[ 2][t 4][2021-11-30 07:30:11.649588339][manager-init.cpp:183][!reiniter]	last key block is [ w=-1 s=9223372036854775808 seq=16270624 sVkSm2Xlv6KNItGyseYhr19izVc7AokoM+vuecHNXLs= /IRcyaYKdj8nk89BLG/8GC+PhbU5otmr7B8u4pfLKek= ]
[ 2][t 5][2021-11-30 07:30:16.906933579][manager-init.cpp:183][!reiniter]	last key block is [ w=-1 s=9223372036854775808 seq=16342566 eInrm7b0X+0V/mthCXni6RrKobJozJ9MsT5LTtpUML8= 3N/sChAE/keiZCIXp8cukQw2LgIlgulBK4yk2kOWmQ0= ]
[ 2][t 4][2021-11-30 07:30:21.140030002][manager-init.cpp:183][!reiniter]	last key block is [ w=-1 s=9223372036854775808 seq=16412383 HxBxl8u2szGfAZ3MZ3hxyBkPFX6nXX3Ho7OlcJaORtI= 6vjkIofGD54Gh9StBD0jxQaVkB1mODM/vZEoJzoew5w= ]
[ 2][t 2][2021-11-30 07:30:23.842314523][manager-init.cpp:183][!reiniter]	last key block is [ w=-1 s=9223372036854775808 seq=16450900 De16r4/QsjBOIkSBYSps2fk/guVeEhKcC8lME6GQZ/o= cZdR2eWpuqUwefd5Ev0DWkL0L3jQbykzbCJdxSY/HbI= ]
[ 2][t 7][2021-11-30 07:30:24.170187010][manager-init.cpp:156][!next]	failed to download key blocks: [Error : 651 : received answer with error]
[ 3][t 1][2021-11-30 07:30:25.170972377][manager-init.cpp:220][!reiniter]	key block candidate: seqno=16450900 is_persistent=false ttl=1638766216 syncbefore=300.000000
[ 3][t 1][2021-11-30 07:30:25.171025867][manager-init.cpp:238][!reiniter]	ignoring: state is not persistent
[ 3][t 1][2021-11-30 07:30:25.171034640][manager-init.cpp:220][!reiniter]	key block candidate: seqno=16448608 is_persistent=false ttl=1638758026 syncbefore=300.000000
[ 3][t 1][2021-11-30 07:30:25.171045226][manager-init.cpp:238][!reiniter]	ignoring: state is not persistent
[ 3][t 1][2021-11-30 07:30:25.171055419][manager-init.cpp:220][!reiniter]	key block candidate: seqno=16432446 is_persistent=false ttl=1638700679 syncbefore=300.000000
[ 3][t 1][2021-11-30 07:30:25.171065488][manager-init.cpp:238][!reiniter]	ignoring: state is not persistent
[ 3][t 1][2021-11-30 07:30:25.171072639][manager-init.cpp:220][!reiniter]	key block candidate: seqno=16430304 is_persistent=true ttl=1638692488 syncbefore=300.000000
[ 2][t 1][2021-11-30 07:30:25.171082802][manager-init.cpp:244][!reiniter]	best handle is [ w=-1 s=9223372036854775808 seq=16430304 pI3JfSmWlgjGmyb2PZ31lhu4MzLJczo3YxjDXQzQnBY= Ohy4vMvykTewISrqdNlKvWHi38Wu71yNG2JmfQWZvyg= ]
[ 2][t 6][2021-11-30 07:30:29.602131162][full-node-shard.cpp:447][!manager]	getnextkey: [Error : 651 : not inited]
[ 2][t 7][2021-11-30 07:30:31.569652408][full-node-shard.cpp:447][!manager]	getnextkey: [Error : 651 : not inited]
[ 2][t 3][2021-11-30 07:30:33.600942553][full-node-shard.cpp:447][!manager]	getnextkey: [Error : 651 : not inited]
[ 2][t 5][2021-11-30 07:30:39.043857577][full-node-shard.cpp:447][!manager]	getnextkey: [Error : 651 : not inited]
[ 2][t 3][2021-11-30 07:30:43.824480592][full-node-shard.cpp:447][!manager]	getnextkey: [Error : 651 : not inited]
[ 2][t 5][2021-11-30 07:30:47.196397876][full-node-shard.cpp:447][!manager]	getnextkey: [Error : 651 : not inited]
[ 2][t 2][2021-11-30 07:30:54.733644999][full-node-shard.cpp:447][!manager]	getnextkey: [Error : 651 : not inited]
[ 2][t 2][2021-11-30 07:30:57.275795514][full-node-shard.cpp:447][!manager]	getnextkey: [Error : 651 : not inited]
[ 2][t 7][2021-11-30 07:31:05.329670858][full-node-shard.cpp:447][!manager]	getnextkey: [Error : 651 : not inited]
[ 2][t 7][2021-11-30 07:31:05.642962858][full-node-shard.cpp:447][!manager]	getnextkey: [Error : 651 : not inited]
[ 2][t 7][2021-11-30 07:31:07.274924095][full-node-shard.cpp:447][!manager]	getnextkey: [Error : 651 : not inited]
[ 2][t 4][2021-11-30 07:31:08.338910881][full-node-shard.cpp:447][!manager]	getnextkey: [Error : 651 : not inited]
[ 2][t 2][2021-11-30 07:31:16.198210458][full-node-shard.cpp:447][!manager]	getnextkey: [Error : 651 : not inited]
[ 2][t 3][2021-11-30 07:31:16.287808287][full-node-shard.cpp:447][!manager]	getnextkey: [Error : 651 : not inited]
[ 2][t 7][2021-11-30 07:31:16.790170287][full-node-shard.cpp:447][!manager]	getnextkey: [Error : 651 : not inited]
[ 2][t 6][2021-11-30 07:31:17.653327391][full-node-shard.cpp:447][!manager]	getnextkey: [Error : 651 : not inited]
[ 2][t 2][2021-11-30 07:31:19.369796073][full-node-shard.cpp:447][!manager]	getnextkey: [Error : 651 : not inited]
[ 2][t 4][2021-11-30 07:31:21.237411990][full-node-shard.cpp:447][!manager]	getnextkey: [Error : 651 : not inited]
[ 2][t 3][2021-11-30 07:31:29.468345364][full-node-shard.cpp:447][!manager] getnextkey: [Error : 651 : not inited]
[ 2][t 6][2021-11-30 07:31:30.278998829][full-node-shard.cpp:447][!manager] getnextkey: [Error : 651 : not inited]
[ 2][t 6][2021-11-30 07:31:33.878901468][full-node-shard.cpp:447][!manager] getnextkey: [Error : 651 : not inited]
[ 2][t 3][2021-11-30 07:31:35.164167147][full-node-shard.cpp:447][!manager]	getnextkey: [Error : 651 : not inited]
[ 2][t 7][2021-11-30 07:31:38.870525570][full-node-shard.cpp:447][!manager]	getnextkey: [Error : 651 : not inited]
[ 2][t 1][2021-11-30 07:31:42.438910033][full-node-shard.cpp:447][!manager]	getnextkey: [Error : 651 : not inited]
[ 2][t 2][2021-11-30 07:31:46.298106581][full-node-shard.cpp:447][!manager]	getnextkey: [Error : 651 : not inited]

<img width="952" alt="image" src="https://user-images.githubusercontent.com/90379223/144008521-2311c074-8349-481d-86dc-258df526a1d7.png">

Firewall checked admin not yet block any port so quite confused on this issue.

Any way I can sync correctly or any step I missed? 

Please help, thanks!

**Comment by EmelyanenkoK** [comment]
This warning is normal for a few hours during initial sync.

**Comment by Sceat** [comment]
It's been 24h my node is running, and i still have the exact same error. Might want to reopen this issue
