### ISSUE TITLE
ru.ton.org  docs русская документация

### ISSUE THREAD

**Issue by optimis3232** [ton-blockchain/ton#327]
Необходима документация на русском языке (в идеале сделать переводы на всех языках).Это даст серьезный толчок к росту Тон, ну а как следствие цены за монетку.
В идеале локализация всего проекта. 

PS: Господа Дуровы, во первых огромный респект и уважуха за то что Вы делаете и уже сделали.
Эта драматическая история с вконтакте, а потом снова успех за успехом. Сначала я думал, кто черт возьми этот Паша, откуда он взялся? Я только придумал идею социальной сети(2000-2010) типа ВК, а он уже это сделал! Оказывается там  есть одаренный старший брат - а это уже команда(1+1>2). И тут на тебе интернет нового поколения! Может быть я был сильно занят своей жизнью интроверта и разработками в области Генетического Программирования ( эволюция в компьютере ), суровой борьбой за выживание в России и пропустил всё, но теперь я заметил Ton и уверен в 100% успехе этого мероприятия. Все что остается - это жадно изучать сорсы. Желаю удачи и процветания этому начинанию. Уверен что Вы прилетели из будущего, ну как там Человечество пережило очередной Апокалипсис? Хахаха. 01.12.21. Роман. И.

**Comment by EmelyanenkoK** [comment]
The concept of infinite sharding is needed in order to make TON global (otherwise, less scalable but simple solutions could be used). In this regard, for the long-term development of the TON ecosystem, closure and localization are harmful.
