### ISSUE TITLE
Test giver account is empty

### ISSUE THREAD

**Issue by AleksMx** [ton-blockchain/ton#33]
Test giver smart contract with the address -1:8156775b79325e5d62e742d9b96c30b6515a5cd2f1f64c5da4b193c03f070e0d is empty in the test network.

![image](https://user-images.githubusercontent.com/4531547/65554764-28a8fb80-df33-11e9-959e-083dabd6157f.png)

> getaccount -1:8156775b79325e5d62e742d9b96c30b6515a5cd2f1f64c5da4b193c03f070e0d
[ 3][t 1][1569363259.357934475][lite-client.cpp:1005][!testnode]	requesting account state for -1:8156775B79325E5D62E742D9B96C30B6515A5CD2F1F64C5DA4B193C03F070E0D with respect to (-1,8000000000000000,121452):27397D3595BC322BEF8FE62C7786A580FD2884776D0BE55997C1094A0E59F806:8AC924E050B10DFDB9DE3503FD198DE8E35889FFCECD2E4B74017AA7782E1520 with savefile `` and mode -1
[ 3][t 2][1569363259.703080654][lite-client.cpp:1131][!testnode]	got account state for -1:8156775B79325E5D62E742D9B96C30B6515A5CD2F1F64C5DA4B193C03F070E0D with respect to blocks (-1,8000000000000000,121452):27397D3595BC322BEF8FE62C7786A580FD2884776D0BE55997C1094A0E59F806:8AC924E050B10DFDB9DE3503FD198DE8E35889FFCECD2E4B74017AA7782E1520
[ 3][t 2][1569363259.703128815][check-proof.cpp:217][!testnode]	got account state for -1 : 8156775B79325E5D62E742D9B96C30B6515A5CD2F1F64C5DA4B193C03F070E0D with respect to blocks (-1,8000000000000000,121452):27397D3595BC322BEF8FE62C7786A580FD2884776D0BE55997C1094A0E59F806:8AC924E050B10DFDB9DE3503FD198DE8E35889FFCECD2E4B74017AA7782E1520
account state is empty

**Comment by akme** [comment]
You are looking for an old testgiver address, it has changed after network restart. It's empty now, but works when filled: -1:fcb91a3a3816d0f7b8c2c76108b8a9bc5a6b7a55bd79f8ab101c52db29232260

**Comment by EmelyanenkoK** [comment]
Is not relevant anymore.
