### ISSUE TITLE
I have the hardware and I have the internet speed!

### ISSUE THREAD

**Issue by teeez** [ton-blockchain/ton#331]
Love this project!! The more I read about it the more I want to be part of it..
Was planning on starting my own validator in Texas but I'm missing the collateral.
Anyone happy to lend out 10k Ton? happy to return with interest.

Yours Truly,
EQC284_ejcYFcHOOBpOVVN-TxvJ95usvyxXea2cZ23Ujc3M1

**Comment by EmelyanenkoK** [comment]
Not relevant to this repository.
