### ISSUE TITLE
TON balance still zero

### ISSUE THREAD

**Issue by junaidscripts** [ton-blockchain/ton#332]
I have 5GH rate,
after 4 days of TON mining my balance is still zero.
https://tonscan.org/address/EQCeNlJ9BpVYGr4CfQl33QTNQ5oePgk5af4jLxD3q8eb7unA

Shows inactive.
Please help

**Comment by Messa1** [comment]
Check your wallet address  in mining client. I got now issue mining ton.

**Comment by EmelyanenkoK** [comment]
Not relevant to this repository.
