### ISSUE TITLE
compile failed

### ISSUE THREAD

**Issue by butterfly1924** [ton-blockchain/ton#335]
[ 84%] Built target tl_api
Scanning dependencies of target src_parser
[ 86%] Building CXX object crypto/CMakeFiles/src_parser.dir/parser/srcread.cpp.o
[ 86%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/utilities/transactions/transaction_db_mutex_impl.cc.o
[ 86%] Building CXX object crypto/CMakeFiles/src_parser.dir/parser/lexer.cpp.o
[ 88%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/utilities/transactions/transaction_util.cc.o
[ 88%] Building CXX object crypto/CMakeFiles/src_parser.dir/parser/symtable.cpp.o
[ 88%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/utilities/transactions/write_prepared_txn.cc.o
[ 88%] Linking CXX static library libsrc_parser.a
[ 88%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/utilities/transactions/write_prepared_txn_db.cc.o
[ 88%] Built target src_parser
Scanning dependencies of target tlbc
[ 88%] Building CXX object crypto/CMakeFiles/tlbc.dir/tl/tlbc.cpp.o
In file included from /home/xf1/CLionProjects/ton/crypto/tl/tlbc.cpp:3061:
/home/xf1/CLionProjects/ton/crypto/tl/tlbc-gen-cpp.cpp: In member function ?bool tlbc::CppTypeCode::generate_get_tag_pfx_distinguisher(std::ostream&, std::string, const std::vector<int>&, bool) const?:
/home/xf1/CLionProjects/ton/crypto/tl/tlbc-gen-cpp.cpp:1050:8: warning: unused variable ?is_pfx_determ? [-Wunused-variable]
 1050 |   bool is_pfx_determ = !trie->find_conflict_path();
      |        ^~~~~~~~~~~~~
In file included from /home/xf1/CLionProjects/ton/crypto/tl/tlbc.cpp:3061:
/home/xf1/CLionProjects/ton/crypto/tl/tlbc-gen-cpp.cpp: In member function ?bool tlbc::CppTypeCode::output_print_simple_field(std::ostream&, const tlbc::Field&, std::string, const tlbc::TypeExpr*)?:
/home/xf1/CLionProjects/ton/crypto/tl/tlbc-gen-cpp.cpp:2171:7: warning: unused variable ?l? [-Wunused-variable]
 2171 |   int l = (sz.is_fixed() ? sz.convert_min_size() : -1);
      |       ^
[ 88%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/utilities/transactions/write_unprepared_txn.cc.o
[ 88%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/utilities/transactions/write_unprepared_txn_db.cc.o
[ 88%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/utilities/ttl/db_ttl_impl.cc.o
[ 88%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/utilities/wal_filter.cc.o
[ 88%] Linking CXX executable tlbc
[ 88%] Built target tlbc
Scanning dependencies of target tlb_generate_block
[ 88%] Generate block tlb source files
[ 88%] Built target tlb_generate_block
Scanning dependencies of target ton_block
[ 88%] Building CXX object crypto/CMakeFiles/ton_block.dir/block/Binlog.cpp.o
[ 88%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/utilities/write_batch_with_index/write_batch_with_index.cc.o
[ 88%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/utilities/write_batch_with_index/write_batch_with_index_internal.cc.o
[ 88%] Building CXX object crypto/CMakeFiles/ton_block.dir/block/block.cpp.o
[ 88%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/utilities/transactions/lock/range/range_tree/lib/locktree/concurrent_tree.cc.o
[ 88%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/utilities/transactions/lock/range/range_tree/lib/locktree/keyrange.cc.o
[ 88%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/utilities/transactions/lock/range/range_tree/lib/locktree/lock_request.cc.o
[ 88%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/utilities/transactions/lock/range/range_tree/lib/locktree/locktree.cc.o
[ 88%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/utilities/transactions/lock/range/range_tree/lib/locktree/manager.cc.o
[ 88%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/utilities/transactions/lock/range/range_tree/lib/locktree/range_buffer.cc.o
[ 90%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/utilities/transactions/lock/range/range_tree/lib/locktree/treenode.cc.o
[ 90%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/utilities/transactions/lock/range/range_tree/lib/locktree/txnid_set.cc.o
[ 90%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/utilities/transactions/lock/range/range_tree/lib/locktree/wfg.cc.o
[ 90%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/utilities/transactions/lock/range/range_tree/lib/standalone_port.cc.o
[ 90%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/utilities/transactions/lock/range/range_tree/lib/util/dbt.cc.o
[ 90%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/utilities/transactions/lock/range/range_tree/lib/util/memarena.cc.o
[ 90%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/port/port_posix.cc.o
[ 90%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/env/env_posix.cc.o
[ 90%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/env/fs_posix.cc.o
[ 90%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/env/io_posix.cc.o
[ 90%] Building CXX object crypto/CMakeFiles/ton_block.dir/block/block-db.cpp.o
[ 90%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/third-party/folly/folly/detail/Futex.cpp.o
[ 90%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/third-party/folly/folly/synchronization/AtomicNotification.cpp.o
[ 90%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/third-party/folly/folly/synchronization/DistributedMutex.cpp.o
[ 90%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/third-party/folly/folly/synchronization/ParkingLot.cpp.o
[ 90%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/third-party/folly/folly/synchronization/WaitOptions.cpp.o
[ 93%] Building CXX object third-party/rocksdb/CMakeFiles/rocksdb.dir/__/__/build_version.cc.o
[ 93%] Building CXX object crypto/CMakeFiles/ton_block.dir/block/block-parse.cpp.o
[ 95%] Building CXX object crypto/CMakeFiles/ton_block.dir/block/check-proof.cpp.o
[ 95%] Linking CXX static library librocksdb.a
[ 95%] Built target rocksdb
Scanning dependencies of target tddb
[ 95%] Building CXX object tddb/CMakeFiles/tddb.dir/td/db/MemoryKeyValue.cpp.o
[ 97%] Building CXX object tddb/CMakeFiles/tddb.dir/td/db/binlog/Binlog.cpp.o
[ 97%] Building CXX object crypto/CMakeFiles/ton_block.dir/block/mc-config.cpp.o
[ 97%] Building CXX object crypto/CMakeFiles/ton_block.dir/block/output-queue-merger.cpp.o
[ 97%] Building CXX object tddb/CMakeFiles/tddb.dir/td/db/binlog/BinlogReaderHelper.cpp.o
[ 97%] Building CXX object tddb/CMakeFiles/tddb.dir/td/db/RocksDb.cpp.o
[ 97%] Building CXX object crypto/CMakeFiles/ton_block.dir/block/transaction.cpp.o
In file included from /home/xf1/CLionProjects/ton/tddb/../third-party/rocksdb/include/rocksdb/iterator.h:23,
                 from /home/xf1/CLionProjects/ton/tddb/../third-party/rocksdb/include/rocksdb/db.h:18,
                 from /home/xf1/CLionProjects/ton/tddb/td/db/RocksDb.cpp:21:
/home/xf1/CLionProjects/ton/tddb/../third-party/rocksdb/include/rocksdb/slice.h:46:20: error: ?string_view? in namespace ?std? does not name a type
   46 |   Slice(const std::string_view& sv) : data_(sv.data()), size_(sv.size()) {}
      |                    ^~~~~~~~~~~
/home/xf1/CLionProjects/ton/tddb/../third-party/rocksdb/include/rocksdb/slice.h:46:15: note: ?std::string_view? is only available from C++17 onwards
   46 |   Slice(const std::string_view& sv) : data_(sv.data()), size_(sv.size()) {}
      |               ^~~
/home/xf1/CLionProjects/ton/tddb/../third-party/rocksdb/include/rocksdb/slice.h:95:8: error: ?string_view? in namespace ?std? does not name a type
   95 |   std::string_view ToStringView() const {
      |        ^~~~~~~~~~~
/home/xf1/CLionProjects/ton/tddb/../third-party/rocksdb/include/rocksdb/slice.h:95:3: note: ?std::string_view? is only available from C++17 onwards
   95 |   std::string_view ToStringView() const {
      |   ^~~
/home/xf1/CLionProjects/ton/tddb/../third-party/rocksdb/include/rocksdb/slice.h: In constructor ?rocksdb::Slice::Slice(const int&)?:
/home/xf1/CLionProjects/ton/tddb/../third-party/rocksdb/include/rocksdb/slice.h:46:48: error: request for member ?data? in ?sv?, which is of non-class type ?const int?
   46 |   Slice(const std::string_view& sv) : data_(sv.data()), size_(sv.size()) {}
      |                                                ^~~~
/home/xf1/CLionProjects/ton/tddb/../third-party/rocksdb/include/rocksdb/slice.h:46:66: error: request for member ?size? in ?sv?, which is of non-class type ?const int?
   46 |   Slice(const std::string_view& sv) : data_(sv.data()), size_(sv.size()) {}
      |                                                                  ^~~~
make[3]: *** [tddb/CMakeFiles/tddb.dir/build.make:121: tddb/CMakeFiles/tddb.dir/td/db/RocksDb.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:7627: tddb/CMakeFiles/tddb.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[ 97%] Building CXX object crypto/CMakeFiles/ton_block.dir/block/block-auto.cpp.o
[ 97%] Linking CXX static library libton_block.a
[ 97%] Built target ton_block
make[1]: *** [CMakeFiles/Makefile2:9648: crypto/CMakeFiles/fift.dir/rule] Error 2
make: *** [Makefile:2547: fift] Error 2

**Comment by eanisei** [comment]
I hope we'll get a solution. I got same mistake

**Comment by m41k3** [comment]
@butterfly1924 Describe your environment (Operating system, etc.) and how you run the command.

**Comment by EmelyanenkoK** [comment]
Please check [workflows](https://github.com/ton-blockchain/ton/tree/master/.github/workflows) as guide.
