### ISSUE TITLE
 db inconsistent error

### ISSUE THREAD

**Issue by konak** [ton-blockchain/ton#338]
Hi team !

I'm getting this kind of error in my logs:

> [ 1][t 1][2022-04-17 11:24:43.980038947][manager-init.cpp:324][!starter]        db inconsistent: last state ( [ w=-1 s=9223372036854775808 seq=18477532 XxvLJP8XYycCIfuQdVK5SMecfVI+Bc4eHUae3vykFJc= cUzpm1a7AFwkZxH2wBom820pZY0H7rn94Q6w8Cn/DoI= ] ) not received

It is happening when you are deleting files from archive folder db/archive.

Is there a way to restart validator db sync process, so it will download archive data one more time ?
This issue can happen when you are making a mistake during extending resources of your server and accidentally starting validator when folders are not mapped to new SSD where you have copied all of the old files ... or forget to change permissions ...

Somekind of resync option should exist for this kind of issues.

**Comment by EmelyanenkoK** [comment]
Currently there is no way to resync db using existing files, you need to sync it from scratch.

**Comment by konak** [comment]
And how to do it ?

Is there any guide or description of steps to do it from scratch ?

Seems I have deleted all of the database files, but sync do not starting ... Maybe I have forgotten something. Is there any document where I can read the files / folders should be deleted to start sync from the scratch ?

**Comment by EmelyanenkoK** [comment]
I recommend to use [MyTonCtrl](https://github.com/ton-blockchain/mytonctrl) which has handy install and unistall scritps

**Comment by joslee7410** [comment]
> I recommend to use [MyTonCtrl](https://github.com/ton-blockchain/mytonctrl) which has handy install and unistall scritps

Am I the only one unable to use **MyTonCtrl** to run Ton Full Node? 

I keep getting this error message in the log.thread files

**Comment by konak** [comment]
No @joslee7410 , but developers recommend to totally uninstall the existing full node and install it from the scratch ... Unfortunately ...

**Comment by joslee7410** [comment]
Sorry Sir @konak @EmelyanenkoK , may I know, is it there have any instruction or step for install from scratch?

**Comment by konak** [comment]
Hi @joslee7410 

https://ton.org/validator

Install script:
wget https://raw.githubusercontent.com/ton-blockchain/mytonctrl/master/scripts/install.sh
sudo bash install.sh -m full

Documentation:
https://github.com/ton-blockchain/mytonctrl
