### ISSUE TITLE
Sync Issue

### ISSUE THREAD

**Issue by joslee7410** [ton-blockchain/ton#351]
Good day Ton,

Here I met some problem during syncing. 

I'm using `MYTONCTRL`, but not sure any configure wrongly that cause unable to sync or what.

**Log**

```
==> /var/ton-work/log.thread11.log <==
[ 2][t11][2022-05-06 10:28:14.956241890][manager-init.cpp:183][!reiniter]       last key block is [ w=-1 s=9223372036854775808 seq=20028231 g9MwG6FUoExquDPTX028y/zZc16F60/2C6n/ontKJn0= qemGCfD8Xkn7Q8K3huxsuA60pD1NEWosO7JSp4MkqYk= ]
[ 2][t11][2022-05-06 10:28:15.304430719][manager-init.cpp:183][!reiniter]       last key block is [ w=-1 s=9223372036854775808 seq=20104803 FlwpWJIr5/nZBxdrHFKzS13YGAFFodpBIrZbwcdYxqE= QwlN8sz+0qH9JBqmJQwwkF0MWqIkLcf7HmA6faSDlVg= ]
[ 2][t11][2022-05-06 10:28:15.644878956][manager-init.cpp:183][!reiniter]       last key block is [ w=-1 s=9223372036854775808 seq=20180958 Rj0edaE46YB0N1kUXSQL3Sjm6vEou5Qs9hoUU5NWK0w= wvblvwg+QIDOynSql38v77R/1gp/e+FnoouSo6EjaAs= ]

==> /var/ton-work/log.thread12.log <==
[ 2][t12][2022-05-06 10:28:17.489111527][manager-init.cpp:183][!reiniter]       last key block is [ w=-1 s=9223372036854775808 seq=20330429 OSkyRrieLG6TJrUugCXO3BK+VHcgR4X9VRoUePZQghs= dVkVW6oFTOPFRsL7f6/dByKJUYMU1Q9FXyQRxeOPU8w= ]

==> /var/ton-work/log.thread4.log <==
[ 2][t 4][2022-05-06 10:28:18.213239375][manager-init.cpp:183][!reiniter]       last key block is [ w=-1 s=9223372036854775808 seq=20349419 GlNDfmXUlQBhOu34v56r0pfolujaOwTHN/A+vJbPNQ0= 19TEjULg3MH+uyaSuS5ew0c4APeVU7UQbsJH4uMf3Ak= ]

==> /var/ton-work/log.thread12.log <==
[ 2][t12][2022-05-06 10:28:19.372263543][manager-init.cpp:244][!reiniter]       best handle is [ w=-1 s=9223372036854775808 seq=20349419 GlNDfmXUlQBhOu34v56r0pfolujaOwTHN/A+vJbPNQ0= 19TEjULg3MH+uyaSuS5ew0c4APeVU7UQbsJH4uMf3Ak= ]

==> /var/ton-work/log.thread11.log <==
[ 2][t11][2022-05-06 10:28:19.629397797][download-state.cpp:232][!downloadstatereq(-1,8000000000000000,20349419)]   failed to download state : [Error : 651 : state not found]
```

Instance Spec:

AWS
- r5.8xlarge
- Ubuntu 20.04.4 LTS
- 1TB storage
- with all port enable (TCP / UDP)
- disabled firewall

**Comment by EmelyanenkoK** [comment]
If you are running liteserver you may try to use [sop branch](https://github.com/ton-blockchain/ton/tree/sop) (in mytonctrl you need to update it first with `update` command, and then use `upgrade https://github.com/ton-blockchain/ton sop` command), for validators we still recommend `master`, though.
On `sop` we also recommend to start with verbosity level 4 (note, you can change this on the fly with `setverbosity` command in validator-engine-console). In this case you can inspect the longest part of the process (state downloading) by searching for `downloading state` logs.
Alternatively, you can check [dump.ton.org](dump.ton.org) to manually download the latest state of the TON.

P.S. If those recommendations will solve your issues - please don't forget to close the issue, thanks in advance.

**Comment by joslee7410** [comment]
@EmelyanenkoK Sir, did you have more detail step to show me? I'm quite confuse on what you mentioned above. My purpose is to run a full node only, not validator, after the node full sync, gonna run with this `https://github.com/toncenter/ton-http-api`

But I need run the endpoint with my own node. not from the toncenter.com

**Comment by EmelyanenkoK** [comment]
Sorry for late answer.
1) The easiest way to run full node is to use https://github.com/ton-blockchain/mytonctrl/
2) Then to switch to another branch you can type `upgrade https://github.com/ton-blockchain/ton testnet` (don't be afraid about "testnet" word, it is about codebase not the network
3) Wait for the sync
4) Generate config `mytonctrl` -> `installer` -> `clcf`
5) Use config to run ton-http-api
