### ISSUE TITLE
How do I join the main network

### ISSUE THREAD

**Issue by leezijie** [ton-blockchain/ton#369]
How do I join the main network

**Comment by EmelyanenkoK** [comment]
Check the docs: https://ton.org/docs/#/nodes/run-node

**Comment by leezijie** [comment]
> Check the docs: https://ton.org/docs/#/nodes/run-node

Thanks.I learned that TON is a sharded blockchain,Is there some sort of gateway that can get the latest transactions for all the shards.Instead of looping to capture transactions in the last block of each shard.

**Comment by awesome-doge** [comment]
I guess you want Archive Node

Here are the related links:
* https://tonwhales.com/docs/node
