### ISSUE TITLE
FunC incorrectly return from condition in inline functions

### ISSUE THREAD

**Issue by EmelyanenkoK** [ton-blockchain/ton#370]
The following code
```
int f1(a) inline {
  if (a > -1) {
    return 3;
  } 
  return 2;
}

int main() {
  return 1 + f1(2); 
}
```
will be compiled into
```
PROGRAM{
  DECLPROC f1
  DECLPROC main
  f1 PROC:<{
    //  a
    -1 GTINT	//  _2
    IFJMP:<{	// 
      3 PUSHINT	//  _3=3
    }>	// 
    2 PUSHINT	//  _4=2
  }>
  main PROC:<{
    // 
    2 PUSHINT	//  _1=2
    f1 INLINECALLDICT	//  _2
    INC	//  _3
  }>
}END>c
```
and upon execution 
`<b b> 0 "some.fif" include <s <b b> runvm 2drop swap drop`
will return 3 instead of 4.

This bug happens due to the fact that funC compiler inserts `IFJMP` for ifs with returns (in `f1` in example above) and being inlined `IFJMP` jumps out not from the function it caused (`f1`) but from the function which inlined function with if (`main`).

There are two approaches to combat this behavior:
1) detect on funC level that function is inlined and do not use IFJMPs in that case
2) redefine INLINECALLDICT such it will wrap inline functions into `PUSHCONT { ... } EXECUTE` (this will, however, consume excessive space even for the cases when it is not necessary).

**Comment by alireza237237** [comment]
Submit
