### ISSUE TITLE
Asm.fif: splitting of large function bodies incorrectly interfere with inlines

### ISSUE THREAD

**Issue by EmelyanenkoK** [ton-blockchain/ton#375]
```
PROGRAM{
  DECLPROC foo
  DECLPROC main
  foo PROC:<{
    { NOP } 1000 times
  }>
  main PROC:<{
    foo INLINECALLDICT
    123456789 PUSHINT
  }>
}END>c
```
The following code will return nothing instead of `123456789`: it is result that inserted due to split `JMPREF`s will jump out of the main.

Possible solution is to wrap large inline functions with `<{ }> PUSHCONT EXECUTE` or `CALLREF`.
Issue was found by @SpyCheese

**Comment by Maxim17081983** [comment]
[SpyCheese:func-inline-return](https://t.me/c/1490369917/31357)

**Comment by basmbasmd** [comment]
ساعدني لجعل العمل يعمل بسهوله وامنا واصلاح جميع المشاكل والدمج بين كل محافظي وحمايتها من الاحتيال وتزويدي بالتقرير الكامل بمساهمه كامله وربط وتحسين وحمايه وتطوير ودعم وفق برامج جيثب واليته المتطوره المدعومه بلذكاء المثطور للقيام بجميع الاعمال وترتيبها وزياده الارباح والحمايه من الخساره والحد من الانفاق والتبذير والاسراف
