### ISSUE TITLE
ton-global.config.json file not found

### ISSUE THREAD

**Issue by umarfarooqitgcuf** [ton-blockchain/ton#389]
ton-global.config.json file not available at the give link of ton.org i.e from
wget https://ton.org/ton-global.config.json page not found .
where to get thagtt config file for runing full node.

**Comment by andreypfau** [comment]
https://ton.org/global-config.json

**Comment by awesome-doge** [comment]
There are two main sources
* https://ton.org/global-config.json
* https://ton-blockchain.github.io/global.config.json

This source should be deprecated
* https://newton-blockchain.github.io/global.config.json

**Comment by awesome-doge** [comment]
> @EmelyanenkoK Both the links in lite-client-docs and FullNode-HOWTO are oudated
> 
> https://github.com/ton-blockchain/ton/blob/master/doc/FullNode-HOWTO https://github.com/ton-blockchain/ton/tree/master/lite-client-docs

Hahaha. This is an ancient document.

**Comment by umarfarooqitgcuf** [comment]
So these should be updated now with current links
