### ISSUE TITLE
Test giver empty

### ISSUE THREAD

**Issue by matjek-chen** [ton-blockchain/ton#40]
Test giver seems to be empty again. Actually its not, it seems to have 15253916 nanograms, however, when requesting a transfer to this, or lesser amount, nothing happens. Is this behavior correct?

**Comment by 1ex** [comment]
Hello, i faced same issue, account kf_8uRo6OBbQ97jCx2EIuKm8Wmt6Vb15-KsQHFLbKSMiYIny stuck on **seqno 0x1729** and **5865959**, not able to get ANY amount of Gram even 0.000001.

**Comment by ton-blockchain** [comment]
Somebody steals all money from the TestGiver using a lot of bots, so it does not make sense to replenish it. Use Telegram bot https://t.me/test_ton_bot instead.

**Comment by EmelyanenkoK** [comment]
Giver is not relevant anymore.
