### ISSUE TITLE
How to install fift with libraries on Ubuntu?

### ISSUE THREAD

**Issue by ghost** [ton-blockchain/ton#402]
When I am running a fift file, it shows:

[ 1][t 0][2022-06-12 09:27:48.410802255][fift-main.cpp:180]     Error interpreting standard preamble file `Fift.fif`: cannot locate file `Fift.fif`
Check that correct include path is set by -I or by FIFTPATH environment variable, or disable standard preamble by -n.

I don't want to use -I. Instead I hope to use make install to install fift dependencies to /usr/bin?

**Comment by awesome-doge** [comment]
Details are here
https://ton.org/docs/#/howto/step-by-step?id=_3-compiling-a-new-smart-contract

Keywords `FIFTPATH`
