### ISSUE TITLE
Customize repository

### ISSUE THREAD

**Issue by Vladimir-Khm** [ton-blockchain/ton#407]
It would be great if this repositry had some [topics](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics) (e.g.: blockchain, ton, telegram, cryptocurrency). 

It would attract new developers specializing in a particular topic. Also this small decoration would make this repository look more professional and friendly

**Comment by EmelyanenkoK** [comment]
Good idea, thanks!
