### ISSUE TITLE
abseil compilation error

### ISSUE THREAD

**Issue by lux01sv** [ton-blockchain/ton#420]
Cause of old version off abseil cmake wont let you compile TON (Probably)

Compiling lite-client

Nothing compiled

Compile TON

Last from github

Intel core i5 with Arch Linux

Add `#include <limits>` to ![image](https://user-images.githubusercontent.com/77214650/178162561-33615649-a4c8-46d6-ab1f-12c4d2fa73f4.png)

**Comment by EmelyanenkoK** [comment]
You can use testnet branch for now (it is compatible with mainnet).

**Comment by EmelyanenkoK** [comment]
Should be fixed in https://github.com/ton-blockchain/ton/pull/433
