### ISSUE TITLE
Setting custom Full node How to add Ip in config file

### ISSUE THREAD

**Issue by umarfarooqitgcuf** [ton-blockchain/ton#424]
I'm setting a custom FullNode and wants to add add ip in config file but in config file ip is given in different format that is 
""ip": -1307380867, " i'm confused in that which format is this and how to convert ip to this format .

**Comment by EmelyanenkoK** [comment]
Check this set of scripts https://github.com/sonofmom/ton-tools/blob/master/node/ip2dec.py
