### ISSUE TITLE
new-wallet smart contract `FunC` source

### ISSUE THREAD

**Issue by VladimirPal** [ton-blockchain/ton#43]
Hi!
Sorry in advance if issues of this repo are not suitable for such questions, but I could not find any another place where I can ask it.

In new-wallet.fif exists Fift assembler code for "Create new simple wallet"
https://github.com/ton-blockchain/ton/blob/master/crypto/smartcont/new-wallet.fif#L16
```
// Create new simple wallet
<{ SETCP0 DUP IFNOTRET // return if recv_internal
   DUP 85143 INT EQUAL IFJMP:<{ // "seqno" get-method
     DROP c4 PUSHCTR CTOS 32 PLDU  // cnt
   }>
   INC 32 THROWIF  // fail unless recv_external
   512 INT LDSLICEX DUP 32 PLDU   // sign cs cnt
   c4 PUSHCTR CTOS 32 LDU 256 LDU ENDS  // sign cs cnt cnt' pubk
   s1 s2 XCPU            // sign cs cnt pubk cnt' cnt
   EQUAL 33 THROWIFNOT   // ( seqno mismatch? )
   s2 PUSH HASHSU        // sign cs cnt pubk hash
   s0 s4 s4 XC2PU        // pubk cs cnt hash sign pubk
   CHKSIGNU              // pubk cs cnt ?
   34 THROWIFNOT         // signature mismatch
   ACCEPT
   SWAP 32 LDU NIP 
   DUP SREFS IF:<{
     // 3 INT 35 LSHIFT# 3 INT RAWRESERVE    // reserve all but 103 Grams from the balance
     8 LDU LDREF         // pubk cnt mode msg cs
     s0 s2 XCHG SENDRAWMSG  // pubk cnt cs ; ( message sent )
   }>
   ENDS
   INC NEWC 32 STU 256 STU ENDC c4 POPCTR
}>c // >libref
```
I'm struggling to understand, this FunC contracts are the same thing?
https://github.com/ton-blockchain/ton/blob/master/crypto/smartcont/simple-wallet-code.fc
https://github.com/ton-blockchain/ton/blob/master/crypto/smartcont/wallet-code.fc

**Comment by ton-blockchain** [comment]
No, but simple-wallet-code.fc compiles to almost the same code. You could use `"simple-wallet.fif" include` instead of <{ ... }>c in new-wallet.fif, the resuilting smart contract would be just a bit larger (contained in three cells instead of one).
