### ISSUE TITLE
Tracing transaction by MasterChain, but missed some transaction in shards's block.

### ISSUE THREAD

**Issue by bobbychen** [ton-blockchain/ton#435]
Hello ,I have a use case is:

Tracing all transaction happened in Ton, My solution is keep track master chain block height, and scan the block and related shard's block(by /api/v2/shards).

But I found some tx are missed, What is the problem? The reason is  I found some blocks in shards cannot relate by master's block.

Can you give some suggestions?

**Comment by EmelyanenkoK** [comment]
Note, you scanner need to implement the following logic:
1) get info about new shard tips from masterchain blocks
2) scan all blocks in shards from tip to previously known block
3) process transactions in obtained block

This algo is implemented here
https://github.com/toncenter/tonweb/blob/master/src/providers/blockSubscription/BlockSubscription.js
