### ISSUE TITLE
Blockchain contest - lack of the feedback

### ISSUE THREAD

**Issue by matjek-chen** [ton-blockchain/ton#44]
Hello,

Is there a communication channel or mailing list, whatever, regarding the blockchain contest? Something that is monitored by the TON team regularly? 

Is this issues tracker such a place or its not?

You can't carry out such a contest w/o communication with the participants can't you?

Thank you.

**Comment by igroman787** [comment]
Maybe it will be useful for you: https://t.me/contest

**Comment by sharikovvladislav** [comment]
https://t.me/contests
