### ISSUE TITLE
lite-client

### ISSUE THREAD

**Issue by Walbr** [ton-blockchain/ton#46]
lite-client -a 192.168.0.3:2222 -p liteserver.pub

`[ 2][t 0][1569568590.073853016][terminal.cpp:92][!terminal io]	disabling readline
[ 1][t 1][1569568590.077298641][lite-client.h:186][!testnode]	conn ready
[ 1][t 2][1569568600.086337328][lite-client.cpp:156][!query]	failed query: [Error : 652 : adnl query timeout]
[ 1][t 2][1569568600.086455822][lite-client.cpp:250][!testnode]	cannot get server version and time (server too old?)
[ 1][t 2][1569568600.086476564][lite-client.cpp:262][!testnode]	server version is too old (at least 1.1 with capabilities 1 required), some queries are unavailable
[ 1][t 1][1569568610.090414524][lite-client.cpp:156][!query]	failed query: [Error : 652 : adnl query timeout]
[ 1][t 1][1569568610.090453625][lite-client.cpp:292][!query]	cannot get masterchain info from server`

**Comment by akme** [comment]
Are you sure that your fullnode is fully synced? Liteserver won't work until fullnode synced with the network.

**Comment by ashkov** [comment]
Hi! How long it takes to fully sync node? How I can test the sync status? Thanks.
