### ISSUE TITLE
There is no method complementary to tonlib_api:createNewKey()

### ISSUE THREAD

**Issue by olegvg** [ton-blockchain/ton#48]
subj. have to use tonlib_api:changeLocalPassword() to decrypt using new_local_password but have side effect with storing decrypted key in key storage. need dedicated method to decrypt key, return-n-forget (public_key, secret)

**Comment by ton-blockchain** [comment]
Key is stored on disk encrypted with `secret` and `local password`.
tonlib chooses `secret` and a user chooses 'local password'.

But a mode that allows tonlib to work in-memory could be useful and is planned to be implemented.

**Comment by EmelyanenkoK** [comment]
Current tonlib version allows in-memory mode (requires to set corresponding flag in init message).
