### ISSUE TITLE
How to start your TON files???

### ISSUE THREAD

**Issue by colotoon** [ton-blockchain/ton#482]
Hello!
I`m trying to running entry proxy on remote computer from ur manual
https://ton.org/docs/#/web3/sites-and-proxy?id=running-entry-proxy-on-remote-computer
And, i`m create new VPS server with Ubuntu 20.04
When, i run this commands from ur manual:
apt update
apt install cmake g++ zlib1g-dev libssl-dev libc6

Next, i get Ubuntu 20.04 Binaries from https://github.com/ton-blockchain/ton/actions?query=branch%3Amaster+is%3Acompleted
as in ur manual
make all files with 0755 rights and try to run any binary file and got an error: Illegal instruction

So, whats wrong???

Guys, we need easy manual for VPS servers, not manual for C++ devs or linux gurus, plz, its need for TON communities!
We all asking u, plz, make it work for any1. tnx

I`m expect easy run app! 

RAM: 512Mb

CPU:
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 13
model name      : QEMU Virtual CPU version 2.5+
stepping        : 3
microcode       : 0x1
cpu MHz         : 1999.999
cache size      : 16384 KB

UPDATE:

1. i install ubuntu 20.04 and make upgrade to latest 22.04
2. get ubuntu 22.04 files from TON autobuilds
3. and - same error!!!

```
root@vps:~# cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
root@vps:~# cd ton
root@vps:~/ton# ./generate-random-id -m adnlid
Illegal instruction
root@vps:~/ton#
```

And i`m also checked files for windows 2019 server, file "generate-random-id" works fine but "rldp-http-proxy" file running but not working, no logfile created, no errors, no udp port 3333 opened!
commands used form ur manual:
rldp-http-proxy/rldp-http-proxy -a 777.777.777.777:3333 -L '*' -C global.config.json -A vcqmha5j3ceve35ammfrhqty46rkhi455otydstv66pk2tmf7rl25f3 -d -l tonsite.log
and
rldp-http-proxy/rldp-http-proxy -a 777.777.777.777:3333 -R '*'@333.333.333.333:80 -C global.config.json -A vcqmha5j3ceve35ammfrhqty46rkhi455otydstv66pk2tmf7rl25f3 -d -l tonsite.log

ofcoz with my IP and key!

Stupidness! Sorry!

Make ur files working plz, we need it!
And next time double check ur files and give as easy way to run it, mabe bash script with autoinstall files or something, coz now its nots working!

Checked on windows 2019 server, debian 9-11, ubuntu 20-22... so sad...

**Comment by internetchk** [comment]
Yes we need a simple tutorial to run this entry proxy.

**Comment by colotoon** [comment]
No answers from DEV team? Nice project! ...

**Comment by hikariatama** [comment]
Binaries are built for a specific platform (CPU). In case you didn't find any appropriate ones, you need to compile them manually - https://ton.org/docs/develop/howto/compile

**Comment by colotoon** [comment]
maybe you forgot, but this platform should be run on VPS servers and not on workstations (where, by the way, the code is compiled, but there is no sense from it, because by transferring it to VPS it does not work, why I think it is not necessary to explain!). I tried to compile files on a VPS with different configurations of operating systems and RAM - everything fails by 33% due to the fact that the process was killed because it did not respond for a long time, and it apparently did not respond for about half an hour, who is to blame for this?
let's go further, I checked all your files for different operating systems and everywhere the same error is an illegal instruction! God only knows on what processors you are doing this! 
and I repeat, this system should be freely runable on any computers if you want it to be popular, no one will buy a VPS in order to compile your files with at least 8 gigabytes of RAM, this is complete nonsense! for example, if you take the files of any linux package from github, for some reason they are always compiled and do not require huge resources! why? because everything is brought to mind, you have everything so raw that no one can run your files!
and before you send someone and somewhere to study something how to compile, first provide us with a video of how you collect all this on a VPS and then we will look and repeat after you, but for now all your links are not a working pile of garbage!
if you need to prove that I'm telling the truth - I myself will record a video with attempts to repeat everything according to your instructions, see for yourself, but then you will definitely burn with shame, even from the fact that your instructions miss a lot of moments, take at least dependencies that result in other errors, which take a very long time to find and fix.

hence my question: why the hell do we need your system with such a complicated installation? if you run everything there on your home PC, this does not mean that it works for everyone, before putting the project into public access, you would have bothered to repeat your steps yourself on a new VPS!

**Comment by hikariatama** [comment]
> 
> maybe you forgot, but this platform should be run on VPS servers and not on workstations (where, by the way, the code is compiled, but there is no sense from it, because by transferring it to VPS it does not work, why I think it is not necessary to explain!). I tried to compile files on a VPS with different configurations of operating systems and RAM - everything fails by 33% due to the fact that the process was killed because it did not respond for a long time, and it apparently did not respond for about half an hour, who is to blame for this?
> let's go further, I checked all your files for different operating systems and everywhere the same error is an illegal instruction! God only knows on what processors you are doing this! 
> and I repeat, this system should be freely runable on any computers if you want it to be popular, no one will buy a VPS in order to compile your files with at least 8 gigabytes of RAM, this is complete nonsense! for example, if you take the files of any linux package from github, for some reason they are always compiled and do not require huge resources! why? because everything is brought to mind, you have everything so raw that no one can run your files!
> and before you send someone and somewhere to study something how to compile, first provide us with a video of how you collect all this on a VPS and then we will look and repeat after you, but for now all your links are not a working pile of garbage!
> if you need to prove that I'm telling the truth - I myself will record a video with attempts to repeat everything according to your instructions, see for yourself, but then you will definitely burn with shame, even from the fact that your instructions miss a lot of moments, take at least dependencies that result in other errors, which take a very long time to find and fix.
> 
> hence my question: why the hell do we need your system with such a complicated installation? if you run everything there on your home PC, this does not mean that it works for everyone, before putting the project into public access, you would have bothered to repeat your steps yourself on a new VPS!

I literally compiled rldp proxy binaries for both my home laptop's windows (4 gb ram), and VERY picky arm64 vds today. It works just fine.

**Comment by colotoon** [comment]
> > maybe you forgot, but this platform should be run on VPS servers and not on workstations (where, by the way, the code is compiled, but there is no sense from it, because by transferring it to VPS it does not work, why I think it is not necessary to explain!). I tried to compile files on a VPS with different configurations of operating systems and RAM - everything fails by 33% due to the fact that the process was killed because it did not respond for a long time, and it apparently did not respond for about half an hour, who is to blame for this?
> > let's go further, I checked all your files for different operating systems and everywhere the same error is an illegal instruction! God only knows on what processors you are doing this!
> > and I repeat, this system should be freely runable on any computers if you want it to be popular, no one will buy a VPS in order to compile your files with at least 8 gigabytes of RAM, this is complete nonsense! for example, if you take the files of any linux package from github, for some reason they are always compiled and do not require huge resources! why? because everything is brought to mind, you have everything so raw that no one can run your files!
> > and before you send someone and somewhere to study something how to compile, first provide us with a video of how you collect all this on a VPS and then we will look and repeat after you, but for now all your links are not a working pile of garbage!
> > if you need to prove that I'm telling the truth - I myself will record a video with attempts to repeat everything according to your instructions, see for yourself, but then you will definitely burn with shame, even from the fact that your instructions miss a lot of moments, take at least dependencies that result in other errors, which take a very long time to find and fix.
> > hence my question: why the hell do we need your system with such a complicated installation? if you run everything there on your home PC, this does not mean that it works for everyone, before putting the project into public access, you would have bothered to repeat your steps yourself on a new VPS!
> 
> I literally compiled rldp proxy binaries for both my home laptop's windows (4 gb ram), and VERY picky arm64 vds today. It works just fine.

what does "I launched on my PC" have to do with it??? Have you carefully read what I wrote above? what does your PC and website hosting via TONE have to do with it? do you even think what you're writing, raising a proxy tone is not the same as raising a website, and that's what this network is interesting for, what's the point of raising a proxy if it's not possible to launch a website Tone? I'm talking about VPS, if you don't know what it is, Google it for decency...

**Comment by hikariatama** [comment]
> > > maybe you forgot, but this platform should be run on VPS servers and not on workstations (where, by the way, the code is compiled, but there is no sense from it, because by transferring it to VPS it does not work, why I think it is not necessary to explain!). I tried to compile files on a VPS with different configurations of operating systems and RAM - everything fails by 33% due to the fact that the process was killed because it did not respond for a long time, and it apparently did not respond for about half an hour, who is to blame for this?
> > > let's go further, I checked all your files for different operating systems and everywhere the same error is an illegal instruction! God only knows on what processors you are doing this!
> > > and I repeat, this system should be freely runable on any computers if you want it to be popular, no one will buy a VPS in order to compile your files with at least 8 gigabytes of RAM, this is complete nonsense! for example, if you take the files of any linux package from github, for some reason they are always compiled and do not require huge resources! why? because everything is brought to mind, you have everything so raw that no one can run your files!
> > > and before you send someone and somewhere to study something how to compile, first provide us with a video of how you collect all this on a VPS and then we will look and repeat after you, but for now all your links are not a working pile of garbage!
> > > if you need to prove that I'm telling the truth - I myself will record a video with attempts to repeat everything according to your instructions, see for yourself, but then you will definitely burn with shame, even from the fact that your instructions miss a lot of moments, take at least dependencies that result in other errors, which take a very long time to find and fix.
> > > hence my question: why the hell do we need your system with such a complicated installation? if you run everything there on your home PC, this does not mean that it works for everyone, before putting the project into public access, you would have bothered to repeat your steps yourself on a new VPS!
> > 
> > 
> > I literally compiled rldp proxy binaries for both my home laptop's windows (4 gb ram), and VERY picky arm64 vds today. It works just fine.
> 
> what does "I launched on my PC" have to do with it??? Have you carefully read what I wrote above? what does your PC and website hosting via TONE on VPS server have to do with it? do you even think what you're writing, raising a proxy tone is not the same as raising a website, and that's what this network is interesting for, what's the point of raising a proxy if it's not possible to launch a website Tone? I'm talking about VPS, if you don't know what it is, Google it for decency...

Stop bragging shit and raging here. I litreally told, that I started RLDP on my VDS server. FYI, hikariatama.ton is the website I started yesterday. If you've provided more **useful** information **regarding the issue**, I would've helped you, but since you're just screaming "you don't understand me", sure, go ahead, scream whatever you want. When you're calm again, update you packages according to the guide, build the proxy **following the guide**. If it doesn't work, try with docker (this option didn't work for me tho), and only then **attach logs from cmake** to your issue.
