### ISSUE TITLE
Update C++ standard 14 -> 20

### ISSUE THREAD

**Issue by zloylos** [ton-blockchain/ton#503]
TON is using C++ 14, but actual version is C++ 20. Update can bring cool features and replace many tg lib things to native ones like:
- `std::optional`
- `std::string_view`
- `std::span`
- `std::filesystem`
- `std::variant`
- `constexpr`
- etc

and it should be just faster, because many issues related to performance were fixed (copy elision for instance https://en.cppreference.com/w/cpp/language/copy_elision) and more safety as well. 

We can start with adding support into CMakeFiles and then rewriting code here and there step by step.

**Comment by tvorogme** [comment]
Great idea. We add c++20 support to CmakeFiles in our closed-source version ~half a year ago, all work correctly.

**Comment by 0x1DA9438** [comment]
+1
@EmelyanenkoK bump. It would be nice to ship it
