### ISSUE TITLE
Improve readme by adding documentation links

### ISSUE THREAD

**Issue by zloylos** [ton-blockchain/ton#505]
It's good to have links for quick start.
- add link to the ton.org for the repo & in the readme
- add link to compile guides like https://ton.org/docs/#/compile?id=how-to-compile
- add readme files with short description and links to doc for specific components inside folders `adnl` -> https://ton.org/docs/#/networking/index?id=adnl etc

These steps will improve developers experience and decrease time to start for new contributors

**Comment by zloylos** [comment]
partially related to https://github.com/ton-blockchain/ton/issues/393

**Comment by EmelyanenkoK** [comment]
Partially solved in 
https://github.com/ton-blockchain/ton/commit/436b9f127d16c5d7d78f15347054e75ba00e38f8
https://github.com/ton-blockchain/ton/commit/4873bd77cdb75b72eea3aa14957a11d0acbb46e7
