### ISSUE TITLE
Func compiler fails on file with \r\n line endings

### ISSUE THREAD

**Issue by bny6613** [ton-blockchain/ton#52]
When you try to compile a file saved on Windows platform (with \r\n) line ending, func compiler produces an error. It looks like the issue is here https://github.com/ton-blockchain/ton/blob/master/crypto/parser/srcread.cpp#L158 - getline leaves \r at the end of the line and later lexer fails to recognize the token. Can we add a fix to strip that char?

**Comment by bny6613** [comment]
I see that there is a fix for that in fift interpreter https://github.com/ton-blockchain/ton/blob/master/crypto/fift/IntCtx.cpp#L102

**Comment by ton-blockchain** [comment]
Thanks for pointing this issue to us. The new version (after commit ecb3e06a06628c358b42ac43c96168d51dbb92e3 ) should work with CP/M-compatible line breaks, please check.
