### ISSUE TITLE
Tonlib init wallet onLiteServerQueryResult error

### ISSUE THREAD

**Issue by webresult** [ton-blockchain/ton#57]
Hi. I use tonlib from Golang. When I was trying to init wallet with `wallet.init` method I saw
`[ 1][t 1][1569847823.922829151][TonlibClient.cpp:368][!Tonlib]	wallet_init {
  private_key = inputKey {
    key = key {
      public_key = "PuaZ_zcK185H2beiHhYcBqsodIw5hBTkhFVmmdL5hFyJ9G_G"
      secret = <secret>
    }
    local_password = <secret>
  }
}
[ 1][t 1][1569847823.922928333][EncryptedKey.cpp:28][!Tonlib]	decrypt
[ 1][t 1][1569847823.996538162][ExtClient.h:58][!Tonlib]	send query to liteserver: liteServer_sendMessage {
  body = bytes [251] { B5 EE 9C 72 01 04 03 01 00 00 00 00 ED 00 02 D7 88 00 E8 9C B5 95 C7 85 CD F4 6D 37 28 68 D5 16 31 18 46 D2 31 28 40 7F 98 52 CE 19 4B A1 84 7C 09 B2 11 8E 1E DA ED 5A 93 2C C5 96 A1 07 7C 81 ...}
}`
in the console and 
`{"@type":"updateSendLiteServerQuery","id":"1","data":"3waMef4AAQCC1App+7XunHIBBAMBAAAAAO0AAteIAOictZXHhc30bTcoaNUWMRhG0jEoQH+YUs4ZS6GEfAmyEY4e2u1akyzFlqEHfIEd6+iLlC2CIoKGWkufE2emyMJt+KH9hkVWZ09sn2dQtwNRN19r2OxWzFhct0o2DqZ/iKHgAAAAH/////ABAgCq/wAg3SCCAUyXupcw7UTQ1wsf4KTyYIMI1xgg0x/THwH4I7vyY+1E0NMf0//RUTG68qED+QFUEEL5EPKi+AACkyDXSpbTB9QC+wDo0aTIyx/L/8ntVABIAAAAAJn/NwrXzkfZt6IeFhwGqyh0jDmEFOSEVWaZ0vmEXIn0"}` in the response. 

So I was trying to run updateSendLiteServerQuery with needed struct.
Finaly I saw 
`[ 1][t 1][1569847823.996713877][TonlibClient.cpp:368][!Tonlib]	onLiteServerQueryResult {
  id = 1
  bytes = bytes [352] { 33 77 61 4D 65 66 34 41 41 51 43 43 31 41 70 70 2B 37 58 75 6E 48 49 42 42 41 4D 42 41 41 41 41 41 4F 30 41 41 74 65 49 41 4F 69 63 74 5A 58 48 68 63 33 30 62 54 63 6F 61 4E 55 57 4D 52 68 47 ...}
}
[ 1][t 1][1569847823.996734619][common-utils.hpp:186][!Tonlib]	Can't parse: 
4d617733 41346665 43435141 70704131 7558372b 4249486e 424d4142 41414141 41304f41 49657441 63694f41 48585a74 30336368 6f635462 57554e61 4768524d
6f456a30 592b4851 5a347355 45473653 796d4166 65345945 61317532 467a796b 4845716c 64454966 4c692b36 4332436c 474b6f49 66756b57 6d653245 744a4d79
39484b2b 57566b68 7339305a 5164326e 524e7774 7239314e 57784f32 6368467a 326f3074 2f5a7144 67484b69 41414141 2f2f2f48 42412f2f 71436741 6741772f
43435333 58795541 77637075 51545537 66737731 79544b34 494d4959 67677831 542f7830 34487748 79763749 45312b59 664d4e30 522f2f30 36475455 44457138
5546512b 354c4545 694b5045 4341412b 5844796b 54627053 43513942 6f44772b 49546130 4c2f7879 746e382f 49424156 41414141 2f6e4a41 5872774e 5a666b7a
65493674 47776846 30687971 456d446a 45534f46 5a615756 456d7630 306e4958
[ 4][t 0][1569847823.996793509][Client.cpp:82][&tonlib_requests]	End to wait for updates, returning object 3 0x7f65ec004cb0
` in console and
`{"@type":"error","code":500,"message":"Wrong constructor found"}` in response.

I run all requests with asynchronously mode. 
I have some questions:

1. Why I have to run onLiteServerQueryResult after most requests like raw.getAccountState, raw.getTransactions.? 
2. What was wrong with this attempt, what does it mean, "wrong constructor found"?

**Comment by ton-blockchain** [comment]
Which Golang bindings do you use? There might be a problem with them not being compatible with the latest big TONLib update (at this stage, the backward compatibility of the internal TONLib interface is not maintained).

**Comment by webresult** [comment]
I use cgo for binging. I update tonlib to latest version. Not all requests contain updateSendLiteServerQuery. For example createNewKey or init requests work as it was before. Only createNewKey starts returning a response from second tonlib_client_json_receive


        C.tonlib_client_json_send(client.client, cs)
	result := C.tonlib_client_json_receive(client.client, DEFAULT_TIMEOUT)
        // nil in result for createNewKey
	for result == nil {
		time.Sleep(1 * time.Second)
		result = C.tonlib_client_json_receive(client.client, DEFAULT_TIMEOUT)
	}
        // after second attempt result contains public key and secret

What does it mean
> at this stage, the backward compatibility of the internal TONLib interface is not maintained

Can I use tonlib as library inside golang code?

**Comment by ton-blockchain** [comment]
You can't send updateSendLiteServerQuery as a query. It is an object, not a function. It means that you have to send this query to a lite server and to respond with `onLiteServerQueryResult` or `onLiteServerQueryError`.

But actually you do not need to handle it at all. You just have to pass `false` during initialization in `use_callbacks_for_network` field. In that case, all network will be handled by tonlib.
