### ISSUE TITLE
Issue in fift assembler|fifC compiler

### ISSUE THREAD

**Issue by danog** [ton-blockchain/ton#59]
Hello!
I've wanted to report a small bug in the FIFT assembler: it seems that simplified definitions for the WHILEEND instruction are missing.
The operation is defined, but the WHILEEND:<{ or }>WHILEEND aliases aren't defined in Asm.fif, leading to compilation errors (especially since the funC compiler actually generates WHILEEND:<{ instructions in some cases).
I just wanted to report this bug I found while studying for the contest.

Thank you.

**Comment by ton-blockchain** [comment]
Thanks. The Fift assembler is in fact correct. The correct construct is WHILE:<{ ... }>DO: ..., not WHILEEND:<{ ... }>, and it has been always supported (and mentioned in p.66 of fiftbase.pdf):

<{ ZERO WHILE:<{ OVER 1 INT AND ISZERO }>DO: INC SWAP 1 RSHIFT# SWAP }>s =: D
 ok
D csr.
x{70952171B0C000E9A401AB0001}
 ok
144 D runvmcode .s
...
9 4 0
ok

 The FunC compiler was slightly incorrect.
