### ISSUE TITLE
Проблема со смарт контрактом

### ISSUE THREAD

**Issue by ownerguthn** [ton-blockchain/ton#591]
Выполнял торги через платформу fragment,сделал ставку в последний момент и перебить не успел,но средства списались и ушли на контракт токена,это недопустимая ошибка в работе,прошу исправить это

https://tonapi.io/transaction/7fd45149c2cd4d3f97a3a724a53d287c4b6af8782813663ed401b981a2fa0bcb

**Comment by EmelyanenkoK** [comment]
В данном нфт у владельца есть возможность пополнить баланс нфт. Именно это и произошло в вашем случае: аукцион кончился и "ставка" засчиталась как пополнение потому что вы владелец. Однако, деньги не потерялись, а остались на балансе нфт и вы как владелец можете их снять в любой момент. Для этого достаточно переслать нфт самому себе.

В любом случае, этот контракт написан Fragment'ом и логика относится к нему, а не к самому блокчейну ТОН которум посвящен этот репозиторий.  Поэтому подобные issues следует поднимать на https://github.com/TelegramMessenger/telemint
