### ISSUE TITLE
A node runs with a lot of log errors 651, 652

### ISSUE THREAD

**Issue by begetan** [ton-blockchain/ton#6]
My node is running on the VM. It utilizes 100-150% of the 2 CPU core and up to 20-30 Mbps of the network.  I can see  10-20 network peers with traffic. So I consider it is working somehow for a quick look.

Anyway there a bunch of errors in logs files ( I have 7 in parallels) with the following errors:

```bash
[ 2][t 1][1568044048.543319702][validate-broadcast.cpp:31][!broadcast][&VALIDATOR_WARNING] aborting validate broadcast query for [ w=0 s=4323455642275676160 seq=138434 JwZ0/mxYvjnsyQJ0Gd4OwM7I82BtJ8YTS3g6Epw0tNg=ofTfUWkPBbr8fcPvkmkgYzPKnuHMnd7DXroE1BBhcss= ]: [Error : 621 : bad signature set]
[ 2][t 1][1568044049.387357950][validate-broadcast.cpp:31][!broadcast][&VALIDATOR_WARNING] aborting validate broadcast query for [ w=0 s=3701958893698547712 seq=144595 z2qSLNClXH7G80o0vTrpk9itD283uvmllFvP4dn18HE=8X8HsyN54EGrOSWQlk8ZmEXmFVvU+2uQRmXB2tJ2xCg= ]: [Error : 621 : bad signature set]
[ 2][t 1][1568044076.846911669][wait-block-data.cpp:103][!waitdata] failed to get block [ w=0 s=3679440895561695232 seq=120721 bt98i8Qj26eZhOoC9gyYYHNjxpqEEK+Gkf2J3vG6b3Q= naVcyN96hS8Vl2gT12enePcTG02zGnv6DNp1KsaQYEQ= ] data from net: [Error : 652 : net error: adnl query timeout]
[ 2][t 1][1568044097.352007627][wait-block-data.cpp:103][!waitdata] failed to get block [ w=0 s=16140901064495857664 seq=142724 P+SW1G23vQlXDVsFpwJjRqM1v8nwsXnFuznCQI8kAT4= 1ihT5TZZQuJ01lQJdsmtckb4YaM3T82cRF+lx5sWPHI= ] data from net: [Error : 652 : net error: adnl querytimeout]
```

**Comment by andresKM** [comment]
+1 Same probles, even on [last](https://github.com/ton-blockchain/ton/commit/d8244eff5367bbfd4cb2873b5c24c75206d98821)  commit.

```
[ 2][t 7][1568205924.800526142][full-node-shard.cpp:326][!manager]	getnextkey: [Error : 651 : not inited]
[ 2][t 7][1568205928.188508272][manager-init.cpp:129][!next]	failed to download key blocks: [Error : 652 : adnl query timeout]
[ 2][t 7][1568205932.357642174][manager-init.cpp:129][!next]	failed to download key blocks: [Error : 652 : adnl query timeout]
[ 2][t 7][1568205936.384830713][manager-init.cpp:129][!next]	failed to download key blocks: [Error : 652 : adnl query timeout]

==> log/error.log.thread6.log <==
[ 2][t 6][1568205940.590332031][manager-init.cpp:129][!next]	failed to download key blocks: [Error : 652 : adnl query timeout]

==> log/error.log.thread5.log <==
[ 2][t 5][1568205942.076242447][full-node-shard.cpp:326][!manager]	getnextkey: [Error : 651 : not inited]

==> log/error.log.thread6.log <==
[ 2][t 6][1568205944.045525074][full-node-shard.cpp:326][!manager]	getnextkey: [Error : 651 : not inited]

==> log/error.log.thread7.log <==
[ 2][t 7][1568205944.802240372][manager-init.cpp:129][!next]	failed to download key blocks: [Error : 652 : adnl query timeout]

==> log/error.log.thread2.log <==
[ 2][t 2][1568205946.544906378][full-node-shard.cpp:326][!manager]	getnextkey: [Error : 651 : not inited]

```

**Comment by begetan** [comment]
Here is the log file after commit https://github.com/ton-blockchain/ton/commit/13140ddf2929e55d3e3ac1b83854a511f146b2da

```
[ 2][t 1][1568908273.207360029][full-node-shard.cpp:326][!manager]      getnextkey: [Error : 651 : not inited]
[ 2][t 1][1568908278.197808743][manager-init.cpp:129][!next]    failed to download key blocks: [Error : 651 : received answer with error]
[ 2][t 1][1568908279.840953350][manager-init.cpp:129][!next]    failed to download key blocks: [Error : 651 : received answer with error]
[ 2][t 1][1568908289.183000088][full-node-shard.cpp:326][!manager]      getnextkey: [Error : 651 : not inited]
[ 2][t 1][1568908299.632665873][full-node-shard.cpp:326][!manager]      getnextkey: [Error : 651 : not inited]
[ 2][t 1][1568908299.716285944][full-node-shard.cpp:326][!manager]      getnextkey: [Error : 651 : not inited]
[ 2][t 1][1568908301.853675604][full-node-shard.cpp:326][!manager]      getnextkey: [Error : 651 : not inited]
[ 2][t 1][1568908306.068066597][full-node-shard.cpp:326][!manager]      getnextkey: [Error : 651 : not inited]
[ 2][t 1][1568908311.093549490][full-node-shard.cpp:326][!manager]      getnextkey: [Error : 651 : not inited]
[ 2][t 1][1568908321.409241199][full-node-shard.cpp:326][!manager]      getnextkey: [Error : 651 : not inited]
[ 2][t 1][1568908322.630741596][full-node-shard.cpp:326][!manager]      getnextkey: [Error : 651 : not inited]
```

**Comment by gruff4l0** [comment]
In my case, I am getting log lines like this: 

```
[ 3][t 1][1569756384.984505415][state-serializer.cpp:220][!serializer][&VALIDATOR_NOTICE]       failure: [Error : 651 : state not in db]
```

and lite-client is getting issues to connect to the server as follow: 

```
 1][t 2][1569755774.965904236][lite-client.cpp:156][!query]  failed query: [Error : 652 : adnl query timeout]
[ 1][t 2][1569755774.966276407][lite-client.cpp:250][!testnode]  cannot get server version and time (server too old?)
```

**Comment by begetan** [comment]
`cannot get server version and time (server too old?)`

It is quite straightforward that you have to rebuild your node and (or) clean up the database

**Comment by ashkov** [comment]
> It is quite straightforward that you have to rebuild your node and (or) clean up the database
How can one clean up the database?
Such situation can be in the case of lack of syncronization. How can one test the case?

**Comment by begetan** [comment]
> Such situation can be in the case of lack of syncronization. How can one test the case?

As for any node you can get current status via cli and compare with the official blockchain explorer, e.g. https://test.ton.org/testnet/last

**Comment by torwig** [comment]
I have the same issue. A lot of 
`[ 3][t 5][1570706879.946240664][state-serializer.cpp:220][!serializer][&VALIDATOR_NOTICE]	failure: [Error : 651 : state not in db]`
and 
`[ 2][t 5][1570706891.426037788][Timer.cpp:82][!checkprooflink][&duration > max_duration_]	SLOW: [name:checkproof][duration:163.4ms]`
and
`[ 2][t 7][1570707062.756895304][Timer.cpp:82][!checkprooflink][&duration > max_duration_]	SLOW: [name:checkproof][duration:176.0ms]`
from validator-engine.
I also have errors using lite-client:
`[ 1][t 2][1570707281.441722393][lite-client.cpp:156][!query]	failed query: [Error : 652 : adnl query timeout]`
`[ 1][t 2][1570707281.441843510][lite-client.cpp:250][!testnode]	cannot get server version and time (server too old?)`
`[ 1][t 2][1570707281.441892147][lite-client.cpp:262][!testnode]	server version is too old (at least 1.1 with capabilities 1 required), some queries are unavailable
`.
Could anyone confirm that lack of CPU power leads to this?

**Comment by sorokinvld** [comment]
``
[ 2][t 1][1571042587.813598871][full-node-shard.cpp:380][!manager]      getnextkey: [Error : 651 : not inited]
[ 2][t 1][1571042589.647569180][full-node-shard.cpp:380][!manager]      getnextkey: [Error : 651 : not inited]
[ 2][t 1][1571042590.415119886][full-node-shard.cpp:380][!manager]      getnextkey: [Error : 651 : not inited]
``

how could I avoid such issue?

**Comment by ponchik69** [comment]
I will subscribe because I have the same problem:
```
[ 2][t 6][1571213247.519571781][full-node-shard.cpp:380][!manager]      getnextkey: [Error : 651 : not inited]
[ 2][t 6][1571213251.563624620][full-node-shard.cpp:380][!manager]      getnextkey: [Error : 651 : not inited]
[ 2][t 6][1571213317.673738241][full-node-shard.cpp:380][!manager]      getnextkey: [Error : 651 : not inited]
[ 2][t 6][1571213335.775568485][full-node-shard.cpp:380][!manager]      getnextkey: [Error : 651 : not inited]
[ 2][t 6][1571213344.045414686][full-node-shard.cpp:380][!manager]      getnextkey: [Error : 651 : not inited]

```

**Comment by ashkov** [comment]
@torwig 
> Could anyone confirm that lack of CPU power leads to this?
YES, it leads. Good AWS configuration is r5d.8xlarge (32 core, 256GiB).
Synchronization last for night
Worse configuration (synchronization lasts about a week) is m5ad.2xlarge | 8 cores | 32GiB
t2.large can't synchronize at all.
https://aws.amazon.com/ec2/instance-types/?nc1=h_ls

**Comment by torwig** [comment]
@ashkov  thank you for sharing your experience with different AWS instances.
How can I figure out that synchronization has been finished?
I've launched a full node and a lite client. I'm using [LiteClient-HOWTO](https://github.com/ton-blockchain/ton/blob/master/doc/LiteClient-HOWTO) but I'm not able to receive any grams from giver account. There were no errors but smart contract's balance hasn't changed. Giver account's field _last_trans_lt_ hasn't changed as well. 
I'm wondering if this happened because of unfinished synchronization.

**Comment by ashkov** [comment]
@torwig Using the `last` command in the lite client, you will see that the time of the last block is about 6-10 seconds ago, or something like that. Not thousands of seconds ago.
