### ISSUE TITLE
Как образовались неактивные кошельки в сети TON или как намайнить в /dev/null

### ISSUE THREAD

**Issue by Stanislav-Povolotsky** [ton-blockchain/ton#603]
Просто хочу поделиться тем, откуда взялась часть кошельков из списка https://tontech.io/stats/early-miners
На примере своего кошелька: **EQCJNvEAo1uoeU5Ir-hdu-nlsqMq6JrZq4tkQhFz-KuMineu** (на котором остались навсегда заблокированными 1400 TON).
Раз сообщество хочет навсегда деактивировать такие кошельки ( https://t.me/tonblockchain/178 ), то оно должно знать, откуда они взялись (не знаю на счёт всех, но уверен, что часть из них).

Шаги, как можно было прийти к успеху:
- Шаг 1: Запускаем **tonlib-cli** (без параметров)
- Шаг 2: Выполняем команду "**genkey**" (generate new secret key)
- Шаг 3: месяц майним на кошелёк, который выводит утилита **tonlib-cli** (команда *keys*)
  ![image](https://user-images.githubusercontent.com/19610545/214105135-cbefce62-6aa2-460d-8bd7-4e00ef05b99a.png)
- Шаг 4: Месяц прошёл, намайнили TONов, пробуем перевести что-нибудь на другой кошелёк, импортировав секретную фразу в какой-нибудь кошелёк. 
  Результат: оказывается адрес кошелька то у нас совершенно **другой :(**. И совсем не совпадает с тем, на который майнили целый месяц.
  ![image](https://user-images.githubusercontent.com/19610545/214106500-1b7eb5e8-0e8f-434c-ad66-5c55dedb56d5.png)
- Шаг 5: Читам документацию, и выясняем, что адрес кошелька, оказывается, зависит от того, с какими параметрами запускался **tonlib-cli**. И что узнать правильный адрес своего кошелька можно только если запустить утилиту **tonlib-cli** с параметром *-c global.config.json*. И в зависимости от этого параметра получаются совершенно разные адреса кошельков (хотя публичные ключи одинаковые):
  ![image](https://user-images.githubusercontent.com/19610545/214108107-1bb77191-b921-4d61-a0d8-dc6cd39f59b3.png)
- Шаг 6: Profit. Урра! Теперь у вас есть секретный ключ к кошельку в несуществующей сети TON, а в главной сети TON есть кошелёк с xxxx TON, к которому ни у кого нет ключа. + Конечно, у вас есть все 5 стадий по очереди: отрицание, гнев, торг, депрессию и принятие.

PS. Сомневаюсь, что сообщество может как-либо посодействовать в получении намайненного (согласен, сам дурак). Но зато могу оценить боль человека с адресом *Ef_mlXHnufWO3-vvopflR_NpIFMiidvp_xt20Qf8usMBBKzB* (с 112400306 TON на нём).
PSS. Привет остальным top 200 неудачникам из списка https://tontech.io/stats/early-miners. Расскажите про ваш секрет успеха?!

**Comment by Stanislav-Povolotsky** [comment]
Happy end! @thekiba - волшебник - помог :)
PS. Надо будет глубже разобраться в TON, чтобы понять как это всё устроено.

**Comment by EmelyanenkoK** [comment]
Note, that tonlib-cli has tools to send coins:
```
transfer[f][F][e][k][c] <from_key_id> (<to_key_id> <value> <message>|<file_name>) - make transfer from <from_key_id>
	 'f' modifier - allow send to uninited account
	 'F' modifier - read list of messages from <file_name> (in same format <to_key_id> <value> <message>, one per line)
	 'e' modifier - encrypt all messages
	 'k' modifier - use fake key
	 'c' modifier - just esmitate fees
```
which allows to send mined coins in-place (without difficulties of "exporting/importing" of keys).

**Comment by aSpite** [comment]
> PS. Надо будет глубже разобраться в TON, чтобы понять как это всё устроено.

Если коротко, то из одного публичного ключа можно получать много адресов при помощи subwallet_id (wallet_id). При отсутствии конфига (global_config.json) по дефолту выставляется workchain = 0, wallet_id = 0, а во всех (как минимум, в основных) нынешних библиотеках (собственно, на котором и работают сами кошельки) wallet_id = 698983191. Это можно проверить, вызывая GET метод (get_subwallet_id) любого кошелька в сети.  

**Почему меняется адрес в зависимости от этого числа?** Адрес любого контракта в TON зависит от нескольких факторов, среди которых stateInit, содержащий в себе код контракта (а кошельки это и есть смарт контракты) и начальную дату. Данное число вносится в Data (туда ещё закладывается seqno, публичный ключ), после чего из всего этого берётся хеш и вместе с другими факторами (различные флаги, workchain) получается адрес кошелька. 

Смарт контракт кошелька при получении external сообщения проверяет этот самый id и если он не совпадает - отклоняет транзакцию: https://github.com/ton-blockchain/wallet-contract/blob/4111fd9e3313ec17d99ca9b5b1656445b5b49d8f/func/wallet-v4-code.fc#L81.

Таким образом необходимо при генерации external сообщения закладывать именно нужный wallet_id для того, чтобы сперва задеплоить контракт с необходимым адресом, после чего вытащить оттуда средства.
