### ISSUE TITLE
Too much fees for one message

### ISSUE THREAD

**Issue by TvoroG** [ton-blockchain/ton#61]
Hi there!

I've created new wallet with code similar to `crypto/smartcont/new-wallet.fif` but with own smart contract code. Send `1 gram` and initialized it by constructor message.

Wallet is initialized but it kept taking fees. After some time it's stopped and i left with only `413079852 nanograms`.

Then I've updated code with second message and again wallet is left with `1833582 nanograms`.

Is it normal? If you need i can paste code here.

**Comment by ton-blockchain** [comment]
The most likely explanation is that you did not take any provisions for your initializing external message to be rejected after the smart contract has been already initialized, and you have got infinitely many transactions processing the same external message.

All smart contracts must take provisions to reject duplicate external messages, for example, by using (always increasing) sequence numbers.

**Comment by TvoroG** [comment]
Got it! Thanks a lot for the explanation.
