### ISSUE TITLE
A Community Proposal for Tokenomics Optimization - Open letter

### ISSUE THREAD

**Issue by emiliana32** [ton-blockchain/ton#615]
Hi,
I do not know if this is the right place to discuss "A Community Proposal for Tokenomics Optimization". Unfortunately, I could not find where it was made and discussed, only [this message](https://t.me/tonblockchain/178) in the TON Foundation's Telegram channel.
Therefore I wrote an [open letter](https://telegra.ph/A-Community-Proposal-for-Tokenomics-Optimization-02-07) addressed to the TON Foundation which aims to shed light on the proposal before it is voted on by the validators. 
Thank you,
Emilia

**Comment by emiliana32** [comment]
Hi,
unfortunately, no one from the TON Foundation has yet answered our questions. Also, because we are really interested in the project, we decided to do our own extensive research and then write the letter translated into 4 languages (English, Russian, Spanish and Italian) directly to the TON Foundation.

In the interest of the TON Community and consequently also of the TON Foundation, it is better to avoid making important votes such as blocking the early miners' inactive wallets for 48 months if there are alternative ways to solve the problem of determining the circulating supply.
We believe that it is possible to solve the problem with two simple steps:

1. Provide an explorer that has data on circulating supply. This explorer already exists is [tontech.io](https://tontech.io/stats/) and is in fact the one included in the [TON Foundation proposal](https://t.me/tonblockchain/178). The other verified explorers tonscan, tonapi and ton whales do not have this data (very strange that none of the official explorers have such data for a blockchain in the top 25).
2. Communicate the data provided by tontech.io to CMC and CoinGecko by filling out these 2 forms ([CMC](https://docs.google.com/spreadsheets/d/1ON2o9fZtdj6aa_uaT7ALtGx1VxFnIDUi8-uS-fWji0o/edit#gid=1300521795) and [CoinGecko](https://docs.google.com/forms/d/e/1FAIpQLSfpIPMsCvVokn7l6OpjJmJoYRxvpArYpO4rvcps-0XQxLQ7DQ/viewform)) so that the circulating supply values are up to date.

Before contacting the TON Foundation via the email on ton.org, the various Telegram and gitHub groups mentioned above, we personally tried to contact CMC and CoinGecko directly asking for explanations on the sources from which they take the circulating supply data (in particular, CoinGecko takes the data from an explorer [ton.cx](https://ton.cx/api/supply) not present on ton.org. Another very strange fact). Both replied that they are willing to update the data if the forms above are filled in and if they are contacted directly by members of the TON Foundation.

As you can see, we don't have any precious time to waste and we don't want to waste yours either. If we are doing all this, it is because we firmly believe in the TON project and the current initiative is our contribution to improving the ecosystem. You can find [here](https://telegra.ph/A-Community-Proposal-for-Tokenomics-Optimization-02-07-2) the research we have collected from independent researchers on the distribution of coins by mining the most important and well-known project in the world of cryptocurrencies that represents the gold standard, Bitcoin. They show that the situation is no different from TON.
Unfortunately, we are sorry to say, based on the current behaviour of the TON Foundation it seems that the motivation to update the value of the circulating supply is just an excuse to cover up their political choice.
Let us hope we are wrong.

**Comment by igorditerni** [comment]
Instead of blocking wallets for no real reason, the TON Foundation needs to clarify these questions, resolve them, and non-liberal, anti-freedom of the blockchain, wallets blocking will no longer be needed.

**Comment by emiliana32** [comment]
We have had long discussions about the validators' vote on blocking the early miners' inactive wallets. I believe that this vote is very important and will be a watershed in the history of TON as was the renaming of testnet2 to mainnet. That is why the vote should be avoided if there are possible alternatives and that the proposal of the Italian community should be considered.
What I do not like is the lack of transparency in the TON Foundation's proposal:
1. The "mystery" of tontech being used as a reliable source for the [early miners' inactive wallets](https://tontech.io/stats/early-miners) while not considered reliable for the calculation of [circulating supply](https://tontech.io/api/status).
2. CoinGecko's use of a ton.cx explorer that was present among the [official ones](https://t.me/toncoin/198), but now is no [longer](https://ton.app/explorers).
3. The refusal to communicate the real circulating supply to the aggregators CMC and CoinGecko claiming that the early miners' inactive wallets are different from those of the early Bitcoin miners (Nakamoto and similar).
This is why the choice is political and the fact of determining the circulating supply is only a pretext.

**Comment by emiliana32** [comment]
At the moment on [ton.vote](https://ton.vote/) 1,688 out of 2,175,997 total wallets holding 1.65 M TON out of 1.221 G TON (alleged) circulating supply and 5.047 G TON of total supply or 0.08% of the wallets and 0.14% - 0.03% of the circulating supply - total supply voted.

According to [Ton Whales](https://tonwhales.com/staking/stats/validators) there are 279 validators, altogether they have about 191.6 M TON or 15.69% of the circulating supply (alleged) and 3.8% of the total supply. If we limit ourselves to the first 188 who have over 600k TON, the numbers are 151.7 M TON or 12.42% and 3.01%.
On TON Nominator there are 27.84 M TON or 14.53% and on TON Whales 18.73 M TON or 9.78% (of the total in staking).

In the best case we are talking about 0.08% of the wallets and 0.14% of the stake and for validators 15.69% of the stake.
**Long live democracy and decentralisation!**

**Comment by igorditerni** [comment]
This is not decentralization.
This is not democracy.

If the TON Foundation will answer [these questions](https://telegra.ph/A-Community-Proposal-for-Tokenomics-Optimization-02-07) no more voting will be needed.

**Comment by EmelyanenkoK** [comment]
Not relevant anymore

**Comment by igorditerni** [comment]
> Not relevant anymore

It is always relevant because after the vote the TON problems are exactly the same, our questions about explorers, circulating supply ... Nothing has been solved.

**Comment by emiliana32** [comment]
Finally, CMC verified TON circulating supply on [14 June](https://coinmarketcap.com/currencies/toncoin/historical-data/) and we are waiting for CoinGecko to do so as well. The values are in line with those of [tontech.io](https://tontech.io/stats/), as expected.
However, some open questions remain:
1. Considering the frozen wallet for 48 months of 1.08 B Toncoin, there is still about 0.53 B Toncoin left. The [TON Foundation 2 wallet](https://tonwhales.com/explorer/top) contains exactly 0.53 B Toncoin while TON Foundation wallet 0.035 B Toncoin. Why are they not considered circulating coin since they are not frozen?
2. Why is tontech.io not yet among the official sources on ton.org? There is still no blockchain level explorer which is in the top-15 and virtually in the top-10 if we consider the coins already issued. I spoke to the developers of the new status network, currently offline, which originated from the [TON Footstep](https://github.com/ton-society/ton-footsteps/issues/11) and they told me they are working on a general overhaul. However, after two months still nothing.
3. In the [official Telegram primer](https://relayto.com/relayto/telegram-open-network-ton-ico-whitepaper-6kf4rycn/K06AXhpp16), 52% of Gram was allocated to the TON Reserve.
According to tontech.io, the initiated supply went from 0 to 2.45 G Toncoin from 18 to 20 July 2022 (why? Mining had been over for a month) and then slowly rose to 2.63 G Toncoin (which is about 52% of the total supply, a strange coincidence). What does this supply represent since it is unique to the TON blockchain? Which wallets are included? Even taking into account the frozen wallets and those of the TON Foundation there is no more than 1.62 G Toncoin.
4. Why did CMC only update it now, since it has been almost four months since the [validators vote](https://t.me/toncoin/760) on tokenomics?

I think that for the benefit of the project, these points should be clarified.
Thank you

**Comment by igorditerni** [comment]
> I think that for the benefit of the project, these points should be clarified. Thank you

Agree.
