### ISSUE TITLE
Let's rewrite ton in Rust

### ISSUE THREAD

**Issue by EnvOut** [ton-blockchain/ton#619]
In Rust writtent a lot of memory safety programs. Basicaly most of daps and modern blockchains uses Rust. Let's rewtire TON in Rust!

Benefits here:

https://www.reddit.com/r/cpp/comments/c5bnme/what_are_the_advantages_of_c_over_rust/

**Comment by EmelyanenkoK** [comment]
You may find https://github.com/tonlabs/ever-node interest, but in this repository we focus on C++ implementation
