### ISSUE TITLE
Not Complete JNI Interface generation 

### ISSUE THREAD

**Issue by phil-dolgolev** [ton-blockchain/ton#62]
Looks like that for some entities from TL don't generated special objects in tonlib_api.cpp, and this cause warns:
* [tonlib_api.cpp:67]	Unknown constructor found: -722616727
* [tonlib_api.cpp:67]	Unknown constructor found: 860930426
* [tonlib_api.cpp:67]	Unknown constructor found: -1041955397
* ....

In tonlib_api_json.cpp I'll found next:
* {"ok", -722616727}
* {"testGiver.accountState", 860930426}
* {"generic.accountStateTestWallet", -1041955397}

How exactly I can fix it, or better just wait solution?

**Comment by ton-blockchain** [comment]
Probably tonlib_api.cpp has not been regenerated after the scheme changed.

To regenerate one should build `prepare_cross_compiling` target like `export.sh` script does.
https://github.com/ton-blockchain/ton/blob/master/example/android/export.sh#L6

It won't help, you may try to delete `tl/generate/auto/tl/tonlib_api.*` and regenerate again.

**Comment by phil-dolgolev** [comment]
I'm remove `tl/generate/auto` and regenerate thats all, but get same result.
Possibly, do I need regenerate `tonlib_api.tlo` with `update-tlo.sh`?
But I can't find `tl-parser` binaries, which way is better to get/compile them and use for `*.tlo` regeneration?

**Comment by ton-blockchain** [comment]
Do you use bindings from `example/android`?

How exactly are you using jni interface?

**Comment by phil-dolgolev** [comment]
Yeah, exactly. I'm generate all bindings in similar way in example/android.
Generate and use shared library based on native-lib.cpp, load them through System.loadLibrary("native-lib") in Client.java

But in tonlib_api.cpp some logic for constructing objects are presented, some absent. 

Example problem part of tonlib_api.cpp, from 24 row due 70

````object_ptr<Object> Object::fetch(JNIEnv *env, jobject &p) {
  if (p == nullptr) { return nullptr; }
  auto id = env->CallIntMethod(p, td::jni::GetConstructorID);
  switch (id) {
    case accountAddress::ID:
      return accountAddress::fetch(env, p);
    case config::ID:
      return config::fetch(env, p);
    case error::ID:
      return error::fetch(env, p);
    case exportedEncryptedKey::ID:
      return exportedEncryptedKey::fetch(env, p);
    case exportedKey::ID:
      return exportedKey::fetch(env, p);
    case exportedPemKey::ID:
      return exportedPemKey::fetch(env, p);
    case inputKey::ID:
      return inputKey::fetch(env, p);
    case key::ID:
      return key::fetch(env, p);
    case keyStoreTypeDirectory::ID:
      return keyStoreTypeDirectory::fetch(env, p);
    case keyStoreTypeInMemory::ID:
      return keyStoreTypeInMemory::fetch(env, p);
    case logStreamDefault::ID:
      return logStreamDefault::fetch(env, p);
    case logStreamFile::ID:
      return logStreamFile::fetch(env, p);
    case logStreamEmpty::ID:
      return logStreamEmpty::fetch(env, p);
    case options::ID:
      return options::fetch(env, p);
    case unpackedAccountAddress::ID:
      return unpackedAccountAddress::fetch(env, p);
    case internal_transactionId::ID:
      return internal_transactionId::fetch(env, p);
    case raw_initialAccountState::ID:
      return raw_initialAccountState::fetch(env, p);
    case testWallet_initialAccountState::ID:
      return testWallet_initialAccountState::fetch(env, p);
    case wallet_initialAccountState::ID:
      return wallet_initialAccountState::fetch(env, p);
    default:
      LOG(WARNING) << "Unknown constructor found: " << id;
      return nullptr;
  }
}```

But in same time all Functions/Objects are successfully generated in TonApi.java

**Comment by ton-blockchain** [comment]
Oh, got it. It is some kind of optimization. Downside - `toString` won't work sometimes.

Could you please try this change
```
-#ifndef TD_ENABLE_JNI  // we need to parse all types in order to implement toString
+#ifndef TONLIB_ENABLE_JNI  // we need to parse all types in order to implement toString
```
at this line
https://github.com/ton-blockchain/ton/blob/master/tl/generate/tl_writer_td.cpp#L71

**Comment by phil-dolgolev** [comment]
Looks like this is help resolve problem, `tonlib_api.cpp` currently contains previously absent code, thanks! 

Now I build native-lib and check that all works fine

**Comment by phil-dolgolev** [comment]
Builded library works fine, but I found some minor issues, like that:
`GenericGetAccountState` actually return `GenericAccountStateTestWallet` when expected `GenericAccountState`.

For this type of problems is better create new issues and close this(possibly after proposed fix by you)?

**Comment by ton-blockchain** [comment]
`generic.getAccountState` should return any of the following
`generic.accountStateRaw`, `generic.accountStateTestWallet`, `generic.accountStateWallet`, `generic.accountStateTestGiver` or `generic.accountStateUninited`.

And for example `GenericAccountStateTestWallet` is inherited from `GenericAccountState`.

But yes, a separate issue would be nice.
