### ISSUE TITLE
[Feature Request] Add ability to send any BOC message via tonlib

### ISSUE THREAD

**Issue by APshenkin** [ton-blockchain/ton#63]
currently we can send only message created by Genesis Account
https://github.com/ton-blockchain/ton/blob/ecb3e06a06628c358b42ac43c96168d51dbb92e3/tonlib/tonlib/TonlibClient.cpp#L864

It would be great if we will be able to send any created BOC message that was created outside of tonlib (e.g. boc created by fift interpreter)

**Comment by ton-blockchain** [comment]
If you want to send an external message with a known body, to a known account, then raw_sendMessage is what you need.
It wraps the body of the message and the address of the account into `Message X` and sends it to the server.

You want something like `sendfile` in liteclient for cases when you already have serialized `Message X`?

**Comment by APshenkin** [comment]
@ton-blockchain exactly

something like sendfile to be able to send any message generated by `fift`

**Comment by ton-blockchain** [comment]
I will add this feature for convenience.

Just what to emphasize that one may generate with `fift` a bit smaller message, than `wallet.fif` generates. And then send it with `raw.sendMessage`.
