### ISSUE TITLE
WASM builds in Actions

### ISSUE THREAD

**Issue by 0x1DA9438** [ton-blockchain/ton#634]
I checked the building WASM script and there are strange things:

https://github.com/ton-blockchain/ton/blob/fc9542f5e223140fcca833c189f77b1a5ae2e184/.github/script/fift-func-wasm-build-ubuntu.sh#L28-L34

```
# clone ton repo
git clone --recursive https://github.com/the-ton-tech/ton-blockchain.git

# only to generate auto-block.cpp
cd ton-blockchain
git pull
git checkout 1566a23b2bece49fd1de9ab2f35e88297d22829f
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DZLIB_LIBRARY=/usr/lib/x86_64-linux-gnu/libz.so -DZLIB_INCLUDE_DIR=$ZLIB_DIR -DOPENSSL_ROOT_DIR=$OPENSSL_DIR -DOPENSSL_INCLUDE_DIR=$OPENSSL_DIR/include -DOPENSSL_CRYPTO_LIBRARY=$OPENSSL_DIR/libcrypto.so -DOPENSSL_SSL_LIBRARY=$OPENSSL_DIR/libssl.so ..
make -j4 fift
```

why do you clone the fork `the-ton-tech/ton-blockchain.git` there?

**Comment by neodiX42** [comment]
This is a known issue and will be fixed in the upcoming release. The correct version of this script in the testnet branch right now https://github.com/ton-blockchain/ton/blob/testnet/.github/script/fift-func-wasm-build-ubuntu.sh

**Comment by EmelyanenkoK** [comment]
Closing for now, will reopen if still be relevant after merge
