### ISSUE TITLE
Unable to retrieve test grams from test giver

### ISSUE THREAD

**Issue by leedioxin** [ton-blockchain/ton#64]
Was following the HOWTO instructions for the Lite client.

It looks like I'm able to create an account (file at least).

I can create an request from the test giver.

tonton@ip-10-5-1-8:~/source$ crypto/fift -I /home/tonton/source/ton/crypto/fift/lib:/home/tonton/source/ton/crypto/smartcont -s testgiver.fif 0f8UzcrAr2EeGEs4U-BKS4hQjFyI8oaWz4CEnm7DT40YRZnI 5923 19.92 pike_request
Test giver address = -1:fcb91a3a3816d0f7b8c2c76108b8a9bc5a6b7a55bd79f8ab101c52db29232260 
kf_8uRo6OBbQ97jCx2EIuKm8Wmt6Vb15-KsQHFLbKSMiYIny
Requesting GR$19.92 to account 0f8UzcrAr2EeGEs4U-BKS4hQjFyI8oaWz4CEnm7DT40YRZnI = -1:14cdcac0af611e184b3853e04a4b88508c5c88f28696cf80849e6ec34f8d1845 seqno=0x1723 bounce=0 
enveloping message: x{0000172301}
 x{427F8A66E56057B08F0C259C29F02525C428462E4479434B67C0424F3761A7C68C22A8251A98A000000000000000000000000000000000000047494654}

resulting external message: x{89FFF9723474702DA1EF71858EC211715378B4D6F4AB7AF3F1562038A5B6524644C0000000B9180C_}
 x{427F8A66E56057B08F0C259C29F02525C428462E4479434B67C0424F3761A7C68C22A8251A98A000000000000000000000000000000000000047494654}

B5EE9C7241040201000000006A00014F89FFF9723474702DA1EF71858EC211715378B4D6F4AB7AF3F1562038A5B6524644C0000000B9180C01007A427F8A66E56057B08F0C259C29F02525C428462E4479434B67C0424F3761A7C68C22A8251A98A0000000000000000000000000000000000000474946547FB2388C
(Saved to file pike_request.boc)

==
When I send the file via the Lite client, it appears to accept it.

sendfile pike_request.boc
[ 1][t 2][1569951849.222630501][lite-client.cpp:973][!testnode] sending query from file pike_request.boc
[ 3][t 2][1569951849.222983360][lite-client.cpp:983][!query]    external message status is 1

But I don't the see the sequence number of the giver contract advance.

Is there a way to get more information on what might be breaking here?  The node logs just confirm that a message was sent, but nothing else.

Thanks!

**Comment by ton-blockchain** [comment]
You can see that the Testgiver has balance less than 19.92 test Grams, because some greedy people have used bots to transfer almost all of its original balance to themselves: [https://test.ton.org/testnet/account?account=kf_8uRo6OBbQ97jCx2EIuKm8Wmt6Vb15-KsQHFLbKSMiYIny](
https://test.ton.org/testnet/account?account=kf_8uRo6OBbQ97jCx2EIuKm8Wmt6Vb15-KsQHFLbKSMiYIny)
That's why your query fails.
If you really need test Grams, you can use Telegram bot [https://t.me/test_ton_bot](https://t.me/test_ton_bot).
