### ISSUE TITLE
Possible regression in tonlibjson::deleteKey

### ISSUE THREAD

**Issue by olegvg** [ton-blockchain/ton#65]
Guess, after the latest big update ecb3e06 there is regression in `deleteKey key:key = Ok;` of subj. It has become an error to call deleteKey with valid arguments, it can't delete key because looking for it at wrong path:
`{'@type': 'error', 'code': 2, 'message': 'Can\'t unlink "A7303931B9F4B4077DAD43605A291C0DB44E3BCC24AFA9FEE487B5FAA214DBEF"'}`
where library is configured using this config snippet:
`{'@type': 'keyStoreTypeDirectory', 'directory': '***/ton_client/testsuite/../tmp/'}`

**Comment by ton-blockchain** [comment]
There is a problem, but only for keys stored in a deprecated format. So this probably won't be fixed.

`deleteKey` should work for new keys though.

**Comment by olegvg** [comment]
Okay, and how do a new keys have to create? And most important question is how to distinguish it from each other? You mentioned tonlib-generated keys here https://github.com/ton-blockchain/ton/issues/22#issuecomment-536180978 Is it what you meant?

More general question is on further plans of support '3rd party' keys, i.e. not generated by library. What is their fate? I'm an author of https://github.com/formony/ton_client/ and I'm a bit uncomfortable seeing library API changes each odd day. And planning to release bip-32/44 etc approach.

**Comment by ton-blockchain** [comment]
You may generate a new key with `createNewKey`.
Then you may export it as a list of words with `exportKey`.
Some examples could be found here https://github.com/ton-blockchain/ton/blob/master/tonlib/test/offline.cpp#L428

If you wish to generate key on your side, you may do this, but the only way to import this key to tonlib is with `importKeyPem`. It must be a Ed25519 private key encoded in pem format.

tonlib API is definitely not final. But there won't be breaking changes in the part related to keys generation.

**Comment by ton-blockchain** [comment]
Also, thank you. I can confirm that there is a bug in the current version.

**Comment by ton-blockchain** [comment]
It should be fixed now.
