### ISSUE TITLE
TON Storage - System requirements

### ISSUE THREAD

**Issue by air3ijai** [ton-blockchain/ton#678]
Is there any information about [storage-demon](https://docs.ton.org/participate/ton-storage/storage-daemon) system requirements?

We run 2 nodes on AWS - [t3a.nano](https://aws.amazon.com/ec2/instance-types/t3/) and observed the following
1. One of the node became unresponsive, until OOM killer killed storage-demon
    ```
    Apr 25 05:40:14 peer kernel: [344537.099233] Out of memory: Killed process 24143 (storage-daemon) total-vm:190408kB, anon-rss:167956kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:404kB oom_score_adj:0
    ```
2. On AWS monitoring at same time we see a spike in CPU usage - can be related to the OOM killer activity an overall instance load
3. In general, storage-demon running in tmux, just stop to work at some point without any information in the app or OS logs (will address that in a separate issue)

We will increase memory to at least 1GB - t3a.micro, to see how it works

**Questions are following**
1. Is storage-daemon CPU intensive - any general recommendations?
2. Is storage-daemon Memory intensive - any general recommendations?
3. Any other recommendations like minimal disk space, network bandwidth, Public IP or at least forwarded TPC/UDP port?
4. Anything above addressed in the documentation?

Thanks!

**Comment by neodiX42** [comment]
The minimum system requirements for storage-daemon would be:

- Processor: 1 GHz with two cores
- Memory: 2 GB RAM
- Storage: 2 GB SSD (not including space for torrents)
- 10Mb/s network bandwidth with static IP 

we will update the documentation accordingly.

**Comment by air3ijai** [comment]
> static IP

It would be good to handle dynamic IP cases, when we run instances in the Cloud and after reboot, node may get a different one.

As it was [already mentioned](674#issuecomment-1517688521), we should set Public IP at `storage-daemon` run. And if it was changes we should handle it by the IAC configuration in automatic way or manually.

In some cases it may be enough to make just an outgoing connection to some Publicly accessible peer to download the data or even for upload?

**Comment by air3ijai** [comment]
Information is already in the documentation - [Hardware requirements](https://docs.ton.org/participate/ton-storage/storage-daemon#hardware-requirements).
