### ISSUE TITLE
tonlib wallet.init doesn't work

### ISSUE THREAD

**Issue by akme** [ton-blockchain/ton#69]
Trying to use tonlib-cli for wallet creation and initialization.
Steps:
1. Genkey - ok
2. TopUp init address - ok
3. wallet.init - says ok, but state on the network remains uninited.
```
[ 1][t 1][1570030054.678366899][TonlibClient.cpp:368][!Tonlib]	wallet_init {
  private_key = inputKey {
    key = key {
      public_key = "PuaP7m2A45nOk5WIGK2l-g_BBEm0IMbrfku4coM51asy55lO"
      secret = <secret>
    }
    local_password = <secret>
  }
}
[ 1][t 1][1570030054.678586960][EncryptedKey.cpp:28][!Tonlib]	decrypt
[ 1][t 1][1570030054.790073395][ExtClient.h:58][!Tonlib]	send query to liteserver: liteServer_sendMessage {
  body = bytes [251] { B5 EE 9C 72 01 04 03 01 00 00 00 00 ED 00 02 D7 88 00 B5 2E D7 81 3B 9B 1C 77 CD E3 C1 02 0F 90 39 6A 93 75 F4 1E C5 DB B1 56 35 15 32 5C 2D BA C4 9A 11 92 73 C5 C5 AC E5 DB 22 5C 23 02 4D 80 ...}
}
[ 1][t 2][1570030054.823308945][TonlibClient.cpp:880][!Tonlib]	info: liteServer_sendMsgStatus {
  status = 1
}
ok {
}
```
4. getAccountState
```
generic_accountStateUninited {
  account_state = uninited_accountState {
    balance = 20000000000
    last_transaction_id = internal_transactionId {
      lt = 477114000003
      hash = bytes [32] { 42 7E DC FA 0A C5 FD F6 EE 16 46 87 56 99 F2 D6 0A CC 1D 05 40 DE 9C 2B CA D9 AB D2 7D E5 5B 67 }
    }
    sync_utime = 1570030052
  }
}
```

**Comment by ton-blockchain** [comment]
wallet.init was sent at 1570030054

generic.getAccountState was requested immediately after
One can notice it by looking at `sync_utime` of `account_state`. Which is even less than the time when wallet.init was sent.

You should wait for some time before the change will be visible — usually about 10 seconds.

Also, you don't need `wallet.init`. The wallet will be inited automatically during the first `generic.sendGrams` from it.

**Comment by akme** [comment]
Ok, everything worked fine, but will you add a method to tonlib to get non-bounceable address? like unpackAddress but for init purposes..

**Comment by ton-blockchain** [comment]
You may use `transferf` in tonlib-cli to transfer funds to an uninited account with a bounceable address.

In tonlib there is `packAddress` method which together with `unpackAddress` could be used to get a non-bounceable address from bounceable.

**Comment by akme** [comment]
I see `packAddress` in spec, but there is no such method in tonlib-cli.
Btw, `transferf` worked well, thanks for info.

**Comment by akme** [comment]
Tried to use `packAddress` and `unpackAddress`, but can't get non-bounceable address, could you please show an example?

**Comment by ton-blockchain** [comment]
Something like this:
```
    auto addr =
        sync_send(client,      
                  make_object<tonlib_api::unpackAccountAddress>("Ef9Tj6fMJP-OqhAdhKXxq36DL-HYSzCc3-9O6UNzqsgPfYFX"))
            .move_as_ok();

    ASSERT_EQ(true, addr->bounceable_);
    
    addr->bounceable_ = false;
      
    auto addr_str = sync_send(client, make_object<tonlib_api::packAccountAddress>(std::move(addr))).move_as_ok();
    ASSERT_EQ("Uf9Tj6fMJP-OqhAdhKXxq36DL-HYSzCc3-9O6UNzqsgPfdyS", addr_str->account_address_);                                                                                           
```

**Comment by akme** [comment]
Great! thanks, that helped!
