### ISSUE TITLE
Testnet: cannot sync the node (cannot unpack block header in the Merkle proof)

### ISSUE THREAD

**Issue by fmira21** [ton-blockchain/ton#706]
Hi guys!

I've run into an issue with my Testnet node, please see the logs attached:

```
[ 3][t 4][2023-05-22 09:54:44.785218082][download-archive-slice.cpp:195][!archive]	finished downloading arcrive slice #9631840: total=1488229
[ 3][t 4][2023-05-22 09:54:44.785279281][manager.cpp:1661][!manager]	downloaded archive slice: /var/ton-work/db/tmp/tmpXXXXKAE5ug
[ 2][t 4][2023-05-22 09:54:44.789354054][check-proof.cpp:46][!checkproof/st][&VALIDATOR_WARNING]	aborting check proof for [ w=-1 s=9223372036854775808 seq=9631846 QfjQCYZn7vbsGURte/FK7wuBIC3IYWXUlAecsYtUALY= BbW8l9YMpcxN27rNX7nAvUzSCssA95IetmlrDVnaScI= ] query: [Error : -666 : cannot unpack block header in the Merkle proof]
[ 3][t 3][2023-05-22 09:54:44.789395903][import-db-slice.cpp:378][!archiveimport]	[Error : -666 : cannot unpack block header in the Merkle proof]
```

The trivia is, that I cannot sync it after the archive slice `9631840` - look like it's corrupted or the Testnet version is different.
Can you advise on it?

Thank you in advance!

**Comment by EmelyanenkoK** [comment]
Hi! Please check commit version of your node.
Testnet nodes work on https://github.com/ton-blockchain/ton/tree/testnet branch.

It is worth subscribing to https://t.me/testnetstatus if you are going to maintain nodes in testnet.

**Comment by fmira21** [comment]
Hi @EmelyanenkoK,
Thank you for this! I think, I will close this issue with this comment.
