### ISSUE TITLE
fift does not handle vm::CellBuilder::CellCreateError exception

### ISSUE THREAD

**Issue by bny6613** [ton-blockchain/ton#72]
For example, when you try to convert string (> 1023 bits) to slice, interpreter crashes:
```
root@19379b75ee42:/data/build# echo '"" { +"A" } 128 times $>s' | fift
terminate called after throwing an instance of 'vm::CellBuilder::CellCreateError'
Aborted
```

**Comment by ton-blockchain** [comment]
Thanks! This is not too critical for the scripting purposes, but definitely not good. We'll fix this in the next update.
