### ISSUE TITLE
Permissions for remote control

### ISSUE THREAD

**Issue by akme** [ton-blockchain/ton#73]
Could you please describe permissions setting for fullnode control?
```
"control" : [
  { "id" : "bp/RCfduCLVxBEXHLSxf7eBKljV9qk7A3a6gJe06w/c=",
    "port" : <CONSOLE-PORT>,
    "allowed" : [
      { "id" : "i7pPj818xO9XO5/0jcY7ISqOkpK4H8A1m127hxnERlY=",
        "permissions" : 15
      }
    ]
  }
],
```
I assume that `15` is giving full control, but how can we set permissions more precisely?

**Comment by ton-blockchain** [comment]
+0 = usual lite-client queries
+1 = full node statistics queries
+2 = full code configuration modification queries
+4 = potentially dangerous queries (such as private key export or signing arbitrary strings)
+8 = reserved for future extensions (does nothing at the moment)

**Comment by akme** [comment]
What permissions should be set so we can safely let nominators sign requests to participate in elections? Or it'll be too dangerous?
What is the safest way to let the nominator stake on behalf of a validator? Just generate validator-query.boc by ourselves and give it to the nominator?
