### ISSUE TITLE
Deflationary mechanism black hole address

### ISSUE THREAD

**Issue by emiliana32** [ton-blockchain/ton#747]
Hi,
I have already asked this question in the Telegram dev group without getting a satisfactory answer. It seems that the Elector smart contract does not send half of network fees to black hole address. Moreover, the [burn address](https://tonscan.org/address/EQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAM9c#transactions) supposedly dedicated to burning contains only 321 TON, far from the 12750 burned coins reported by tonstat. The [.ton DNS address](https://tonscan.org/address/EQC3dNlesgVD8YbAazcauIrXBPfiVhMMr5YYk2in0Mtsz0Bz), which is supposed to contain the frozen TON resulting from the domain purchase contains 5.15 M, again different from the 6.09 M reported by tonstat. I wonder where tonstat (tonapi) gets its data from.
In particular, according to the [network config](https://explorer.toncoin.org/config#configparam5) the parameter 5 is the black hole address, however it is not present in the [documentation](https://docs.ton.org/develop/howto/blockchain-configs), probably because it is outdated (26/05/23).
According to the [article](https://blog.ton.org/ton-community-proposal-to-implement-toncoin-real-time-burn) in the TON Blog:
_After the launch of the deflation mechanism, the Elector will send only half of the transaction fees to the validators. Elector will send the remaining 50% to a black hole address, removing the coins from circulation._
I am not familiar with the code, but according to the [commit](https://github.com/ton-blockchain/ton/commit/ef64b92f087a41c5dc9c74085bdab152856039a6#diff-0fd3fcfc35f0e3e2a5260e3a52ca5ae4ea0c1d1ae8482a8361831cca7a09b321) that introduced the burning mechanism, some files have been changed. In particular, a burning address is used at least [here](https://github.com/ton-blockchain/ton/blob/master/validator/impl/validate-query.cpp#L4568) and [here](https://github.com/ton-blockchain/ton/blob/master/validator/impl/collator.cpp#L2217).
Could someone clarify my previous questions about the inconsistency of values?
Thank you

**Comment by EmelyanenkoK** [comment]
1. Burning of network fees is handled before fees get to the elector: only half of collected fees gets there. Thus there are no Elector->Blackhole messages.
2. Black hole address is `Ef___________________________________________7Sg` , not `EQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAM9c`. Balance of black hole address won't be increased when you send funds there, instead TON will disappear. Besides, again fee burning is implemented not through sending to blackhole.
`EQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAM9c` is used in many application as address with provably unknown contract/key.
3. When you buy domain on .ton DNS your auction bid amount sends to dns root after domain claiming. Many domains were bought but not claimed yet and bid are still on domain nft. Apparently tonstat calculate this funds as well.

**Comment by emiliana32** [comment]
Thank you for your reply.

1. So you are confirming that the [article](https://blog.ton.org/ton-community-proposal-to-implement-toncoin-real-time-burn) is misleading:
_After the launch of the deflation mechanism, the Elector will send only half of the transaction fees to the validators. Elector will send the **remaining 50% to a black hole address**, removing the coins from circulation._
2. I checked the config [here](https://explorer.toncoin.org/config) and, according to the [documentation](https://docs.ton.org/develop/howto/blockchain-configs), the param 2->-1:hex_address->[System](https://tonscan.org/address/Ef8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAU) and 0:hex_address->[Burn address](https://tonscan.org/address/EQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAM9c)->Why? It should only be the System. While the param 5 is the blackhole address->-1:hex_address->[wallet1](https://tonscan.org/address/Ef___________________________________________7Sg). I am  sorry, but I am still confused.
3. Now it is clearer, we are talking about the [.ton DNS address](https://tonscan.org/address/EQC3dNlesgVD8YbAazcauIrXBPfiVhMMr5YYk2in0Mtsz0Bz) not the root DNS param 4->[Root DNS](https://tonscan.org/address/Ef_lZ1T4NCb2mwkme9h2rJfESCE0W34ma9lWp7-_uY3zXDvq)
