### ISSUE TITLE
Get Archive Node Dump Data

### ISSUE THREAD

**Issue by TonyS001** [ton-blockchain/ton#750]
I want to run an archive node. The instructions show I need to get ID/Pass through telegram chat. But I am not convenient to use telegram. Are there other ways to get ID/Pass, like email?

**Comment by wangjiangw** [comment]
me too，i hava asked in the telegram，but no one gives an answer, can anyone tell us how to get id/pass ?

**Comment by EmelyanenkoK** [comment]
At the moment there are no such options.
