### ISSUE TITLE
Transfer 10000 $

### ISSUE THREAD

**Issue by new-light-106** [ton-blockchain/ton#757]
EQApzemU5DnFQnm4JB2X9vbvNaHQ8CGrExmV7v2OC9mRV4N3

**Comment by new-light-106** [comment]
Transfer 10000$

**Comment by Haan2410** [comment]
Transfer10000

**Comment by Haan2410** [comment]
EQApzemU5DnFQnm4JB2X9vbvNaHQ8CGrExmV7v2OC9mRV4N3
