### ISSUE TITLE
Need wallet name in "d" param for send coins from stacking

### ISSUE THREAD

**Issue by gurovofficial** [ton-blockchain/ton#763]
I propose add wallet name in "d" parameter.
So the profit from stacking will be sent to the new parameter(wallet).
Example, "d:EQCzPAK2ZOx8xaqZgCrc2sUjWBXJhcCcgvSK2z0bE8ReqZ34".

**Comment by EmelyanenkoK** [comment]
Seems like not appropriate here. Probably it is issue for nominator-pool, locker or something else.
