### ISSUE TITLE
Broken transaction is reproducibly added to mainnet

### ISSUE THREAD

**Issue by mcnckc** [ton-blockchain/ton#770]
This is how it looks in explorer, check last transaction: https://tonviewer.com/EQATtsrQY9ave-h8qwWS6ZoO-ew--iZraAHc7nfuTrXTly68

This happens the following way: transfer is send directly to liteservers(not toncenter), for a deployed account (wallet_v3R2, but this shouldn't be important), and the account has enough funds to cover the `transfer value` + what is called `total fees`, but not the
`transfer value`+`total fees`+`fwd_fee`. 

This is possible because `total fees` usually do not include the `fwd_fee`.
To illustrate this, look at this account - https://tonwhales.com/ru/explorer/address/EQCcgPKAP3YtvcVd1il5MP_mTXwwBJKSHJcMPl6UpzmQCYxa
If you take the incoming value, subtract both total fees and the transfer value(it is actually 1 nanoton), it doesn't match up with the
remaining balance. Though, it will match up, if you also subtract the `fwd_fee` of the transfer.

Usually, `total fees` is slightly less than `0.005 TON`, but `total fees` + `fwd_fee` is bigger than `0.005 TON` (this value may change,
when you'll be reading this text, if issue wouldn't reproduce, replace `0.005 TON` with more actual upper bound for `total fees`).
So one can reproduce this the following way:

1. Create an account
2. Fund it with `0.005 TON`*`2`= `0.01 TON`. or slightly less
3. Deploy it
4. Send a transfer to any address, carrying 1 nanoTON

The transfer will result in a "broken" transaction. It will be added to blockchain, your account will be charged with fee, 
about the typical value of `total fees`, but no outgoing messages will be added, like here https://tonwhales.com/explorer/address/EQATtsrQY9ave-h8qwWS6ZoO-ew--iZraAHc7nfuTrXTly68/40962211000001_8397d73b1942499ff85da84dfba852ce85ddecbec7a7c0e9d93daadec9f2a62d, and 
the `fwd_fee` obviously won't be charged.

I used [`tonweb`](https://github.com/toncenter/tonweb) to create transactions BOC and [`ton-kotlin`](https://github.com/andreypfau/ton-kotlin) to send them to liteservers, but I'am sure it will also work with other clients.

I consider this a problem, because, when user sends a transfer he/she expects the transaction to be in one of two states:

1. Transaction is rejected, and nothing happens
2. Transaction is accepted, funds are transferred

But not the third state, where funds are not delivered, but the fee is charged, and, importantly, the client receives a complete "ok" from the liteservers. Thus, to understand if a transaction is actually broken, the user needs to look in blockchain explorer.

I admit, that this won't happen when account has large amounts of TON (but TON price may increase), and the wallet can check the estimated fee, before sending to liteservers - usually estimated fee includes `fwd_fee`, and not allowing user to send such transfer makes this "broken" transaction unlikely to happen (but not impossible).

Still, I believe that guaranteeing the transaction to be in one of 2 states is responsibility of the nodes, not wallet developers, 
and such things never happen in a reliable system, working with finances.

**Comment by EmelyanenkoK** [comment]
This peculiarity is known, in particular TON ALLOWS to do an unsafe things. Simultaneously, it allows to do the same things safely if you want. For instance you can check in contract that balance is enough prior to accepting external messages. Note that although message is not sent there could be side-effects such as contract deployment, so it is not clear whether "transactions is truly rejected" 
In wallet-contracts to minimize gas fees such checks are made offchain by wallet software.
