### ISSUE TITLE
Unlimited time for TON DNS

### ISSUE THREAD

**Issue by gurovofficial** [ton-blockchain/ton#774]
Currently, the DNS must be renewed every year. It is very uncomfortable.
I propose to make dns unlimited in time.
This will be a big advantage over regular domain dns.

**Comment by justdmitry** [comment]
[Why domains are not bought forever?](https://github.com/ton-blockchain/TEPs/blob/master/text/0081-dns-standard.md#why-domains-are-not-bought-forever)

> There is a possibility that access to wallet which owns a domain will be lost, so domain will be lost forever. In TON DNS, it is required to prolong domains each year by sending at least 0.005 TON (minimal amount of TONs for message to be processed) to the contract.

**Comment by howardpen9** [comment]
That can't prevent situations of oligarchy or "territorial dominance".

You can read more articles from Vitalik Buterin; he has mentioned this before.
