### ISSUE TITLE
Reentrancy issue for initializer

### ISSUE THREAD

**Issue by melnikaite** [ton-blockchain/ton#79]
I created simple contract on Solidity with initializer and deployed it multiple times with the same keyPair
```
	constructor() public {
		deployTime = uint32(now);
	}
```
Every time I got the same contract address but initializer mutated state differently
This makes contract state unpredictable and unreliable for the same address
Contract address should be different after each deploy

**Comment by ton-blockchain** [comment]
We don't know anything about this Solidity compiler you are using. Please ask these questions wherever you have got the Solidity compiler, not here. We cannot help you.
