### ISSUE TITLE
Official docker image

### ISSUE THREAD

**Issue by ZergsLaw** [ton-blockchain/ton#792]
I expected to find an official Docker image for TON Proxy or TON Storage in the project. However, currently, there is no official Docker image available.

If you have any additional information that might be helpful, please provide it here. And, if I make docker image for it, can we add it to master by PR?

**Comment by ZergsLaw** [comment]
And you have instructions for running ton proxy - https://docs.ton.org/ko/participate/web3/sites-and-proxy

But third point - Download generate-random-id from [TON Auto Builds](https://github.com/ton-blockchain/ton/releases/latest).


But, where is this tool? Because I can't find this name (generate-random-id)

**Comment by EmelyanenkoK** [comment]
@ZergsLaw Check zip archives for your architecture

**Comment by ZergsLaw** [comment]
@EmelyanenkoK yeah, found generate-random-id

But what about dockers?
