### ISSUE TITLE
Can't change state and transfer in the same function

### ISSUE THREAD

**Issue by melnikaite** [ton-blockchain/ton#81]
```
	function method() public {
		m_value = msg.sender;
		msg.sender.transfer(amount);
	}
```
When I split this method to two functions it works fine, but it doesn't work together
I'm not sure about balance, but state keeps previous value

**Comment by ton-blockchain** [comment]
Again, please ask these questions to the developers of the Solidity compiler you are using, not to us. We cannot help you here.
