### ISSUE TITLE
TonlibClient: Action & Compute Phases

### ISSUE THREAD

**Issue by crazyministr** [ton-blockchain/ton#813]
I have a question aka feature request.
Is it possible or is it planning to add info about Action & Compute Phases into response of `blocks.getTransactionsExt` method (or similar) ?

**Comment by crazyministr** [comment]
Or let me know if it is possible to get it via current implementation of TonlibClient

**Comment by dungeon-master-666** [comment]
It is possible by deserializing `transaction.data` boc and parsing it according to `Transaction` in [block.tlb](https://github.com/ton-blockchain/ton/blob/master/crypto/block/block.tlb#L271)
