### ISSUE TITLE
LITE_SERVER_NOTREADY: seqno not in db

### ISSUE THREAD

**Issue by zhy827827** [ton-blockchain/ton#832]
I deploy the Ton full node through mytonctrl(sudo bash install.sh -m full -d) and Enable Liteserver mode.
 Deploy ton-http-api and point the service to my own lite server

#curl -X 'POST'    -H 'Content-Type: application/json' -d '{"method": "getConsensusBlock","params": {},"id": "1", "jsonrpc": "2.0"}'  http://127.0.0.1:8998/jsonRPC|jq
```
{
  "ok": true,
  "result": {
    "consensus_block": 34832588,
    "timestamp": 1702884001.302868
  },
  "jsonrpc": "2.0",
  "id": "1"
}
```

 #curl -X 'GET'  'http://127.0.0.1:8998/getBlockTransactions?workchain=0&shard=4611686018427387904&seqno=40664737&count=40' -H 'accept: application/json'|jq
```
{
  "ok": false,
  "error": "LITE_SERVER_NOTREADY: seqno not in db",
  "code": 500
}
```

getConsensusBlock is ok but getBlockTransactions has an error 500.
how to fix this issues:LITE_SERVER_NOTREADY seqno not in db 

The first deployment of the ton chain, please advise me a lot，Thanks

**Comment by EmelyanenkoK** [comment]
By default TON node download only most recent state of blockchain, so you can not get historic data.
Check https://dump.ton.org/ to get more deep history dump.

**Comment by zhy827827** [comment]
Thank you~ @EmelyanenkoK
