### ISSUE TITLE
Fift error: no hashB and no interactive shell

### ISSUE THREAD

**Issue by ashkov** [ton-blockchain/ton#86]
`fift -I crypto/fift/lib/ -i`
[ 1][t 0][1570178518.109343290][words.cpp:2784] Fift.fif:28: hashB: -?
[ 1][t 0][1570178518.109453678][fift-main.cpp:174]      Error interpreting standard preamble file `Fift.fif`: error interpreting included file `Fift.fif` : Fift.fif:28: hashB: -?
Check that correct include path is set by -I or by FIFTPATH environment variable, or disable standard preamble by -n.

`fift -n -i`
Result: interactive shell ends instantly without any messages.

**Comment by igroman787** [comment]
If my memory serves me, then after the option -I should indicate the absolute path (not the relative)
Also, there should be no space between the option -I and the absolute path.

Example: 
```
/home/igroman787/Documents/git/myTestTon/liteclient-build/crypto/fift -I/home/igroman787/Documents/git/myTestTon/lite-client/crypto/fift/lib -i
```

**Comment by ashkov** [comment]
This problem appeared only in the last commit and only on the certain computer. It is seems that some compilation problem happend.

**Comment by ton-blockchain** [comment]
It seems likely that you have installed the Fift binary to a separate directory (e.g., /usr/bin/), and did not update that binary after compiling the recent version of Fift from sources.

**Comment by ashkov** [comment]
You are right, after update /usr/bin/fift it works well! Sorry for my mistake
