### ISSUE TITLE
Get balance inside a smart contract

### ISSUE THREAD

**Issue by stdi0** [ton-blockchain/ton#88]
Hi there!

How to find out the current gram balance from inside a smart contract?
I find MYADDR in the primitive configuration, should there be something similar?

I also tried: c7; FIRST; INDEX <?>, but I don’t know what index number

Thanks!

**Comment by ton-blockchain** [comment]
The simplest way is to observe that it is passed in the stack as an argument to `recv_internal` and `recv_external`, as explained in 4.4.5. of the [TON Blockchain Documentatiion](https://test.ton.org/tblkch.pdf). If you use funC, you could simply declare
```
() recv_internal(int acc_balance, int inmsg_balance, cell msg, slice msg_body) impure {
  ...
} 
```
Alternatively, you could inspect the layout of the parameters passed in c7 in 4.4.10, and find out that the balance (represented by a pair consisting of an Integer and a Cell?) is stored as parameter #7. So, `c7 PUSH; FIRST; 7 INDEX; FIRST` or `7 GETPARAM; FIRST` would give you the Gram balance.
