### ISSUE TITLE
Testnet  server is out of sync

### ISSUE THREAD

**Issue by JIoJIaJIu** [ton-blockchain/ton#93]
All new transactions are not processed by testnet TON
```
> last
[ 3][t 1][1570345526.900796175][lite-client.cpp:322][!query]    last masterchain block is (-1,8000000000000000,308562):7AD0FFE3BC39F9C09E0964BA39CAD8CC27B0EF71D388651917461C0
58CD494F8:1D09266E18C47EA659A325BB91083C23AD10CA6DC63C096C730D0924BBCE6486
[ 3][t 2][1570345526.900885105][lite-client.cpp:283][!testnode] server time is 1570345526 (delta 0)
[ 2][t 2][1570345526.900937557][lite-client.cpp:368][!testnode] server appears to be out of sync: its newest masterchain block is (-1,8000000000000000,308562):7AD0FFE3BC39F9C
09E0964BA39CAD8CC27B0EF71D388651917461C058CD494F8:1D09266E18C47EA659A325BB91083C23AD10CA6DC63C096C730D0924BBCE6486 created at 1570312292 (33234 seconds ago according to the s
erver's clock)
```

**Comment by JIoJIaJIu** [comment]
Now the issue is gone and transactions pass well, hence I'm closing the issue

**Comment by ashkov** [comment]
Hi! Is it gone by itself? I'm experiencing the same now. What I can do?

**Comment by JIoJIaJIu** [comment]
@ashkov I think got the problem was gone by itself, or maybe some magic unicorn did something. Right now as I see it works fine, is it?

**Comment by Regno** [comment]
@JIoJIaJIu I follow instructions at https://test.ton.org/HOWTO.txt.

When I try to create new account with new-wallet.fif smart contract I'm getting a new address. But when I check it with getaccount command I get "account state is empty" state. Also at ton browser I get an 404 error when try to find the account: [Error : 404 : FATAL: cannot deserialize account state[Error : 0 : bag of cells is expected to have exactly one root]].

Could be my issue be connected with out of sync problem? Or I made something wrong?

**Comment by JIoJIaJIu** [comment]
Hello @Regno 
Based on my experience (I'm just the guy who is participating in TON challenge) looks like you haven't transferred grams on the account. Before you init your account with FIFT code you MUST put few grams there (with \@test_ton_bot), your account will go in [uninit_state](https://github.com/ton-blockchain/ton/blob/f67f5d879ba0a395367a703dcd75f3b87c6ad535/crypto/block/block.tlb#L245). After that you may send external message with [StateInit](https://github.com/ton-blockchain/ton/blob/f67f5d879ba0a395367a703dcd75f3b87c6ad535/crypto/block/block.tlb#L233) for providing code and data to the account
I recommend you to take a look on references provided on https://test.ton.org/ . 
You may start from [this section](https://test.ton.org/tblkch.pdf#subsection.1.7) for getting an overview
Hope it helps

**Comment by Regno** [comment]
@JIoJIaJIu You're right.

But yesterday bot answer me with error. So it confused me. Today bot works just fine.

Thanks.
