### ISSUE TITLE
Guide how to launch indepenedent TON blockchain

### ISSUE THREAD

**Issue by JIoJIaJIu** [ton-blockchain/ton#94]
## Case
I would like to create independent TON network locally and connect to `lite-client` to it rather to `testnet` TON

> ${DB_ROOT}/static -- A directory with files that cannot be downloaded from the network, such as the "zerostate" (corresponding to the Genesis block of other blockchain architectures) of the masterchain and active workchains. Normally you don't have to initialize this directory unless you want to run your own instance of the TON Blockchain (for example, for testing or development purposes). Full nodes of existing instances of the TON Blockchain (such as the "testnet" and the "mainnet") will be able to download all required files from already running full nodes.

It would be great to have extended guide [doc/FullNode-HOWTO](https://github.com/ton-blockchain/ton/blob/master/doc/FullNode-HOWTO) with steps how to setup and launch local development TON

**Comment by EmelyanenkoK** [comment]
You can check (MyLocalTON)[https://ton.org/docs/#/nodes/local-ton] approach and sources.

**Comment by AVert** [comment]
> ## Case
> 
> I would like to create independent TON network locally and connect to `lite-client` to it rather to `testnet` TON
> 
> > ${DB_ROOT}/static -- A directory with files that cannot be downloaded from the network, such as the "zerostate" (corresponding to the Genesis block of other blockchain architectures) of the masterchain and active workchains. Normally you don't have to initialize this directory unless you want to run your own instance of the TON Blockchain (for example, for testing or development purposes). Full nodes of existing instances of the TON Blockchain (such as the "testnet" and the "mainnet") will be able to download all required files from already running full nodes.
> 
> It would be great to have extended guide [doc/FullNode-HOWTO](https://github.com/ton-blockchain/ton/blob/master/doc/FullNode-HOWTO) with steps how to setup and launch local development TON

how you succeed? i very need local chain
