### ISSUE TITLE
Extend runvm with top-of-stack Integer

### ISSUE THREAD

**Issue by JIoJIaJIu** [ton-blockchain/ton#99]
## Description
I would like to be able to pass subroutine index into `runvm` as `runvmcode` does but also initialize `c4` register

## Case
I'm using extensively `runvm` + `fift` for testing my smartcontract execution and I need to be able to simulate few message calls, so for that purpose I am initializing `c4` and would like to execute custom subroutines
only the way I've found right how is to do the subroutine call from `main()` but it doesn't allow me cover different subroutines with tests dynamically

## Proposal
1. Extend `runvm`
```
FROM: ...args code c4 runvm
...
TO: ...args code c4 -1 runvm
```
2. Or provide additional method for it
```
....args code c4 -1 runvmext
```

If there is another approach to achieve it - share please

**Comment by JIoJIaJIu** [comment]
Found the duplicate issue - https://github.com/ton-blockchain/ton/pull/60

> to simplify local testing of smart contracts, we have also added new words runvmctx and gasrunvmctx

**Comment by ton-blockchain** [comment]
Already done in commit 29deff15c3cfbdfdb73cae37cde0831e9f079e01
