### ISSUE TITLE
Cannot load Fift binary file on MAC OS ARM M1

### ISSUE THREAD

**Issue by dev1line** [ton-blockchain/ton#995]
My Mac M1 is still accpet fift executeable file in this repo
In want to the author can update new binaries Mac ARM Fift file

Pop up MacOS return:
macOS cannot verify that this app is free from malware.

Hope update soon
Thanks

**Comment by neodix42** [comment]
Hi, the binaries in release are not signed. You can use binaries provided by brew, see instructions here: https://github.com/ton-blockchain/packages?tab=readme-ov-file#install-via-brew
